/**
 * Shared export helpers (T-13).
 *
 * SHAPE: pure builders + thin DOM wrappers. Everything that decides what the bytes look
 * like — CSV escaping, the workbook, the JSON envelope, the README sheet — is a pure
 * function, unit-tested by scripts/test-export-utils.mjs. The wrappers do nothing but
 * hand a Blob to `triggerDownload`.
 *
 * WHY `triggerDownload` IS EXPORTED (gap EXP-21). It used to be private, so six other
 * files re-implemented the same anchor-click boilerplate: BackupRestore, SocietySetup
 * (x2), GstSummary (x2), GSTR9, plus EWayBill, PfEsi and tds26q. Each copy is a place
 * where a download can quietly behave differently.
 *
 * WHY `downloadJSON` DOES NOT WRAP BY DEFAULT. Two of those callers emit STATUTORY
 * payloads that imitate the NIC / GSTN offline-utility shape (GstSummary's GSTR-1 and
 * GSTR-3B, GSTR9's draft). Wrapping them in an envelope would corrupt the very thing
 * they exist to produce. So `downloadJSON(payload, filename)` writes the payload
 * verbatim — byte-identical to the `JSON.stringify(x, null, 2)` those sites hand-roll
 * today — and only wraps when a caller explicitly asks for an envelope.
 *
 * WHY THE README SHEET IS OPT-IN (gap EXP-26). The blueprint wants every XLSX export to
 * carry a README sheet (society, FY, generated-at, filters, row counts). But this module
 * has no access to the society, and 45 existing callers pass none. Silently appending an
 * empty README to all of them would be a behaviour change dressed up as a feature. So it
 * appears only when `meta` is supplied, and it goes LAST, so the sheet Excel opens on is
 * still the data.
 */
import * as XLSX from 'xlsx';

/** Bumped when the JSON envelope's shape changes. Consumers key off this. */
export const EXPORT_SCHEMA_VERSION = '1.0';

export type Cell = string | number | null | undefined;

export interface Sheet {
  name: string;
  headers: string[];
  rows: Cell[][];
}

/** Provenance recorded on an export. `generatedAt` is injectable so tests stay deterministic. */
export interface ExportMeta {
  societyName?: string;
  registrationNo?: string;
  financialYear?: string;
  generatedAt?: string;              // ISO 8601
  generatedBy?: string;
  mode?: string;                     // standard | full | redacted | statutory
  filters?: Record<string, unknown>; // date range, includeDeleted, …
}

// ─── Pure builders ───────────────────────────────────────────────────────────────────

/**
 * PURE — RFC-4180-ish CSV. Every field is quoted (so commas, newlines and Devanagari
 * need no special casing) and embedded quotes are doubled. Rows joined with CRLF.
 * Does NOT prepend the BOM; `downloadCSV` does, because only the file needs it.
 */
export function buildCsv(headers: string[], rows: Cell[][]): string {
  const escape = (v: Cell) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  return [headers, ...rows]
    .map(row => row.map(escape).join(','))
    .join('\r\n');
}

/**
 * PURE — the README sheet. Two columns, one row per fact, then a row count per data
 * sheet. Returns null when there is nothing worth saying.
 */
export function buildReadmeSheet(meta: ExportMeta, sheets: Sheet[]): Sheet | null {
  const facts: [string, string][] = [];
  const add = (k: string, v: unknown) => {
    if (v === undefined || v === null || v === '') return;
    facts.push([k, typeof v === 'object' ? JSON.stringify(v) : String(v)]);
  };

  add('Society', meta.societyName);
  add('Registration No.', meta.registrationNo);
  add('Financial Year', meta.financialYear);
  add('Generated At', meta.generatedAt);
  add('Generated By', meta.generatedBy);
  add('Export Mode', meta.mode);
  if (meta.filters && Object.keys(meta.filters).length > 0) {
    for (const [k, v] of Object.entries(meta.filters)) add(`Filter: ${k}`, v);
  }
  if (facts.length === 0) return null;

  facts.push(['', '']);
  for (const s of sheets) facts.push([`Rows in "${s.name}"`, String(s.rows.length)]);

  return { name: 'README', headers: ['Field', 'Value'], rows: facts as Cell[][] };
}

/**
 * PURE — build the workbook. Column widths are sized to the widest cell, as before.
 * Sheet names are truncated to Excel's 31-character limit.
 */
export function buildWorkbook(sheets: Sheet[], meta?: ExportMeta): XLSX.WorkBook {
  const all = [...sheets];
  if (meta) {
    const readme = buildReadmeSheet(meta, sheets);
    if (readme) all.push(readme);   // LAST: Excel opens on the first sheet, keep it data
  }

  const wb = XLSX.utils.book_new();
  for (const sheet of all) {
    const ws = XLSX.utils.aoa_to_sheet([sheet.headers, ...sheet.rows]);
    ws['!cols'] = sheet.headers.map((h, i) => ({
      wch: Math.max(h.length, ...sheet.rows.map(r => String(r[i] ?? '').length)) + 2,
    }));
    XLSX.utils.book_append_sheet(wb, ws, sheet.name.slice(0, 31));
  }
  return wb;
}

/**
 * PURE — wrap a payload in a schema-versioned envelope. This is the shape the future
 * export API serves. Callers that must emit a foreign schema (statutory files) skip it.
 */
export function buildJsonEnvelope(payload: unknown, meta: ExportMeta = {}) {
  return {
    schemaVersion: EXPORT_SCHEMA_VERSION,
    generatedAt: meta.generatedAt ?? new Date().toISOString(),
    society: meta.societyName ?? null,
    registrationNo: meta.registrationNo ?? null,
    financialYear: meta.financialYear ?? null,
    generatedBy: meta.generatedBy ?? null,
    mode: meta.mode ?? null,
    filters: meta.filters ?? null,
    data: payload,
  };
}

// ─── DOM wrappers ────────────────────────────────────────────────────────────────────

/**
 * Hand a Blob to the browser as a download. Exported so nothing re-implements it
 * (gap EXP-21). The object URL is always revoked, including if the click throws.
 */
export function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  try {
    a.click();
  } finally {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}

/**
 * Download data as CSV. UTF-8 BOM so Excel opens Hindi correctly.
 * @param filename - without extension
 */
export function downloadCSV(headers: string[], rows: Cell[][], filename: string): void {
  // '\uFEFF' as an escape, not a literal: a bare BOM character is invisible and gets
  // silently eaten by editors and encoding round-trips.
  const blob = new Blob(['\uFEFF' + buildCsv(headers, rows)], { type: 'text/csv;charset=utf-8;' });
  triggerDownload(blob, filename + '.csv');
}

/**
 * Download data as Excel (.xlsx). Pass several sheets to get a multi-sheet workbook.
 * Supply `meta` to append a README sheet recording who exported what, when.
 */
export function downloadExcel(sheets: Sheet[], filename: string, meta?: ExportMeta): void {
  XLSX.writeFile(buildWorkbook(sheets, meta), filename + '.xlsx');
}

/** Convenience: single-sheet Excel. */
export function downloadExcelSingle(
  headers: string[],
  rows: Cell[][],
  filename: string,
  sheetName = 'Report',
  meta?: ExportMeta,
): void {
  downloadExcel([{ name: sheetName, headers, rows }], filename, meta);
}

/**
 * Download a JSON file.
 *
 * By default the payload is written VERBATIM — `JSON.stringify(payload, null, 2)` —
 * because several callers must emit a foreign schema (GSTR-1/3B, GSTR-9, e-Way Bill)
 * that an envelope would corrupt. Pass `meta` only when the file is a SahakarLekha
 * export and should carry provenance.
 *
 * @param filename - without extension
 */
export function downloadJSON(payload: unknown, filename: string, meta?: ExportMeta): void {
  const body = meta ? buildJsonEnvelope(payload, meta) : payload;
  const blob = new Blob([JSON.stringify(body, null, 2)], { type: 'application/json' });
  triggerDownload(blob, filename + '.json');
}
