import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { SocietySettings, AccountBalance, CashBookEntry, BankBookEntry, LedgerAccount, Member, MemberLedgerEntry, ReceiptsPaymentsData, Loan, Asset, AuditObjection, Employee, SalaryRecord } from '@/types';
import { ACCOUNT_IDS } from '@/lib/storage';
import { getVoucherLines } from '@/lib/voucherUtils';
import { fmtDate } from '@/lib/dateUtils';
import { INDIAN_STATES } from '@/lib/constants';
import { getStateAuditFormat } from '@/lib/stateAuditFormats';


// G1 FIX: Use Rs. prefix — Helvetica font lacks the ₹ glyph, causing garbled output
const fmt = (amount: number): string =>
  'Rs. ' + new Intl.NumberFormat('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount);

const preparedOn = (): string => {
  const d = new Date();
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
};

/** All PDFs use English only — helvetica font always. */
function setupFont(_doc: jsPDF): string {
  return 'helvetica';
}

// G5: Generate unique Report ID
function generateReportId(reportCode: string): string {
  const date = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const rand = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `SL-${reportCode}-${date}-${rand}`;
}

// G12: Look up full state name from code
function getStateName(code: string): string {
  const state = INDIAN_STATES.find(s => s.value === code);
  return state ? state.label : code;
}

// G10: Standardized PDF file naming
export function pdfFileName(reportType: string, society: SocietySettings, fromDate?: string, toDate?: string): string {
  const sanitize = (s: string) => s.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_').substring(0, 40);
  const societySlug = sanitize(society.name);
  const fmtDt = (d: string) => d.split('-').reverse().join('-'); // YYYY-MM-DD → DD-MM-YYYY
  if (fromDate && toDate) {
    return `${reportType}_${societySlug}_${fmtDt(fromDate)}_${fmtDt(toDate)}.pdf`;
  }
  return `${reportType}_${societySlug}_FY_${society.financialYear}.pdf`;
}

// G9: Empty data message
export function addNoDataMessage(doc: jsPDF, font: string, y: number): void {
  const pageW = doc.internal.pageSize.width;
  doc.setFontSize(11);
  doc.setFont(font, 'italic');
  doc.setTextColor(150);
  doc.text('No Data Available', pageW / 2, y + 20, { align: 'center' });
  doc.setFontSize(8);
  doc.text('This report has no transactions for the selected period.', pageW / 2, y + 28, { align: 'center' });
  doc.setTextColor(0);
  doc.setFont(font, 'normal');
}

/**
 * Right-align amount columns in head, body AND foot.
 * jspdf-autotable's columnStyles only applies to body by default.
 * This callback forces halign:'right' on specified column indices across all sections.
 */
export function rightAlignAmountColumns(...colIndices: number[]) {
  return (data: any) => {
    if (colIndices.includes(data.column.index)) {
      data.cell.styles.halign = 'right';
    }
  };
}

/** G7 FIX: Add page numbers + confidentiality footer to every page. Call AFTER all content is added. */
export function addPageNumbers(doc: jsPDF, font: string, societyName?: string): void {
  const total = doc.getNumberOfPages();
  const pageW = doc.internal.pageSize.width;
  const pageH = doc.internal.pageSize.height;
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    // Thin separator line above footer
    doc.setDrawColor(200);
    doc.setLineWidth(0.2);
    doc.line(15, pageH - 14, pageW - 15, pageH - 14);
    // Footer line 1: Confidentiality (centered)
    if (societyName) {
      doc.setFontSize(6);
      doc.setFont(font, 'normal');
      doc.setTextColor(160);
      doc.text(`Confidential \u2014 For authorized use of ${societyName} only`, pageW / 2, pageH - 10, { align: 'center' });
    }
    // Footer line 2: Generated by (left) | Page X of Y (right)
    doc.setFontSize(7);
    doc.setTextColor(120);
    doc.text('Generated by SahakarLekha.com', 15, pageH - 6);
    doc.text(`Page ${i} of ${total}`, pageW - 15, pageH - 6, { align: 'right' });
    doc.setTextColor(0);
  }
}

/**
 * Get signatory names from society settings. Falls back to empty strings if not configured.
 */
export function getSignatoryNames(society: SocietySettings): { accountant: string; secretary: string; president: string } {
  const sig = society.signatories || {};
  return {
    accountant: sig.accountant?.name || '',
    secretary: sig.secretary?.name || '',
    president: sig.president?.name || '',
  };
}

/**
 * Add a 3-column signature block with optional signatory names above designation labels.
 * labels: e.g. ['Accountant', 'Secretary', 'President']
 * names: optional array of actual person names to print above the designation
 * Returns the Y position used.
 */
export function addSignatureBlock(doc: jsPDF, font: string, labels: string[], startY: number, note?: string, names?: string[]): number {
  const pageW = doc.internal.pageSize.width;
  const pageH = doc.internal.pageSize.height;
  // If not enough space on current page, add new page
  if (startY + 35 > pageH - 20) {
    doc.addPage();
    startY = 20;
  }
  // Inset signatures with proper margins (40px from each edge)
  const marginIn = 40;
  const positions = labels.map((_, i) => marginIn + (i * (pageW - marginIn * 2) / (labels.length - 1 || 1)));
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  if (note) {
    doc.setFontSize(7.5);
    doc.setTextColor(80);
    doc.text(note, pageW / 2, startY, { align: 'center' });
    doc.setTextColor(0);
    startY += 6;
  }
  labels.forEach((lbl, i) => {
    const x = labels.length === 1 ? pageW / 2 : positions[i];
    const lblLines = lbl.split('\n').length;  // count lines in label (e.g., "Secretary\n(Seal)" = 2)
    const extraGap = (lblLines - 1) * 4;     // 4px per extra line
    doc.setDrawColor(80);
    doc.setLineWidth(0.3);
    doc.line(x - 25, startY + 8, x + 25, startY + 8);
    // Print actual name above designation (if configured)
    const name = names?.[i];
    if (name) {
      doc.setFontSize(8);
      doc.setFont(font, 'bold');
      doc.text(name, x, startY + 13, { align: 'center' });
      doc.setFont(font, 'normal');
      doc.setFontSize(7.5);
      doc.text(lbl, x, startY + 18, { align: 'center' });
      doc.setFontSize(7);
      doc.setTextColor(100);
      doc.text('Date: __________', x, startY + 24 + extraGap, { align: 'center' });
    } else {
      doc.setFontSize(7.5);
      doc.text(lbl, x, startY + 13, { align: 'center' });
      doc.setFontSize(7);
      doc.setTextColor(100);
      doc.text('Date: __________', x, startY + 19 + extraGap, { align: 'center' });
    }
    doc.setTextColor(0);
  });
  return startY + 26;
}

/**
 * Auditor's Certificate block — per Cooperative Societies Act requirements.
 * Printed at bottom of Balance Sheet / I&E Account.
 */
function addAuditorCertificate(doc: jsPDF, font: string, society: SocietySettings, reportName: string, startY: number): void {
  const pageW = doc.internal.pageSize.width;
  const pageH = doc.internal.pageSize.height;
  if (startY + 50 > pageH - 15) {
    doc.addPage();
    startY = 15;
  }
  doc.setDrawColor(41, 82, 163);
  doc.setLineWidth(0.3);
  doc.line(15, startY, pageW - 15, startY);
  startY += 5;

  doc.setFontSize(8);
  doc.setFont(font, 'bold');
  doc.text("AUDITOR'S CERTIFICATE", pageW / 2, startY, { align: 'center' });
  startY += 5;

  doc.setFont(font, 'normal');
  doc.setFontSize(7.5);
  // G13 FIX: Use state-specific act name instead of hardcoded Haryana
  const stateFormat = getStateAuditFormat(society.state || 'hr');
  const certText =
    `We have examined the ${reportName} of ${society.name} (Reg. No. ${society.registrationNo}) ` +
    `for the Financial Year ${society.financialYear} and certify that the same is drawn up in accordance ` +
    `with the provisions of the ${stateFormat.actName} and the rules made thereunder ` +
    `and presents a true and fair view of the state of affairs of the Society as on 31st March.`;
  const lines = doc.splitTextToSize(certText, pageW - 30);
  doc.text(lines, 15, startY);
  startY += lines.length * 4 + 4;

  const certSig = getSignatoryNames(society);
  addSignatureBlock(doc, font,
    ['Statutory Auditor\n(Name & Membership No.)', 'Secretary\n(Seal)', 'President\n(Seal)'],
    startY, undefined,
    ['', certSig.secretary, certSig.president]  // Auditor name left blank (filled manually)
  );
}

/** Enhanced addHeader — society info, GSTIN, Report ID, Generated By, state full name. */
export function addHeader(
  doc: jsPDF, title: string, society: SocietySettings, subtitle?: string,
  options?: { reportCode?: string; generatedBy?: string }
): { startY: number; font: string; reportId: string } {
  const font = setupFont(doc);
  const pageW = doc.internal.pageSize.width;
  const cx = pageW / 2;
  const marginR = pageW - 15;

  // Society name
  doc.setFontSize(14);
  doc.setFont(font, 'bold');
  doc.text(society.name, cx, 15, { align: 'center' });

  // Reg No + FY (center)
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  const regLine = `Reg. No: ${society.registrationNo} | FY: ${society.financialYear}`;
  doc.text(regLine, cx, 21, { align: 'center' });
  doc.setTextColor(0);

  // Address line — G12: use full state name
  const stateName = society.state ? getStateName(society.state) : '';
  const addrParts = [society.address, society.district, stateName].filter(Boolean);
  if (society.pinCode) addrParts.push(`PIN: ${society.pinCode}`);
  if (addrParts.length > 0) {
    doc.setFontSize(7.5);
    doc.setTextColor(60);
    doc.text(addrParts.join(', '), cx, 26, { align: 'center' });
    doc.setTextColor(0);
  }

  // G2: GSTIN / PAN line
  const taxIds: string[] = [];
  if ((society as any).gstin) taxIds.push(`GSTIN: ${(society as any).gstin}`);
  if (society.entityPan) taxIds.push(`PAN: ${society.entityPan}`);
  if (society.tan) taxIds.push(`TAN: ${society.tan}`);
  if (taxIds.length > 0) {
    doc.setFontSize(7);
    doc.setTextColor(80);
    doc.text(taxIds.join('  |  '), cx, 30, { align: 'center' });
    doc.setTextColor(0);
  }
  const taxIdOffset = taxIds.length > 0 ? 4 : 0;

  // Report title
  doc.setFontSize(13);
  doc.setFont(font, 'bold');
  doc.text(title, cx, 33 + taxIdOffset, { align: 'center' });

  if (subtitle) {
    doc.setFontSize(8.5);
    doc.setFont(font, 'normal');
    doc.text(subtitle, cx, 39 + taxIdOffset, { align: 'center' });
  }

  // Report ID (left) + Prepared on (right) — same line, just above separator
  const metaY = 39 + taxIdOffset;
  doc.setFontSize(6.5);
  doc.setTextColor(130);
  const reportId = options?.reportCode ? generateReportId(options.reportCode) : '';
  if (reportId) {
    doc.text(`Report ID: ${reportId}`, 15, metaY);
  }
  doc.text(`Prepared on: ${preparedOn()}`, marginR, metaY, { align: 'right' });
  doc.setTextColor(0);

  doc.setDrawColor(41, 82, 163);
  doc.setLineWidth(0.5);
  const lineY = 42 + taxIdOffset;
  doc.line(15, lineY, marginR, lineY);
  return { startY: lineY + 4, font, reportId };
}

export function generateCashBookPDF(
  entries: CashBookEntry[],
  society: SocietySettings,
  openingBalance: number,
  language: 'hi' | 'en'
) {
  const doc = new jsPDF();
  const { startY, font } = addHeader(doc, 'Cash Book', society, `Financial Year: ${society.financialYear}`, { reportCode: 'CB' });

  // G9: Empty data guard
  if (entries.length === 0) {
    addNoDataMessage(doc, font, startY);
    addPageNumbers(doc, font, society?.name);
    doc.save(pdfFileName('CashBook', society));
    return;
  }

  const totalReceipts = entries.filter(e => e.type === 'receipt').reduce((s, e) => s + e.amount, 0);
  const totalPayments = entries.filter(e => e.type === 'payment').reduce((s, e) => s + e.amount, 0);
  const closingBalance = entries.length > 0 ? entries[entries.length - 1].runningBalance : openingBalance;

  const body = [
    ['', 'OB', 'Opening Balance', fmt(openingBalance), '', fmt(openingBalance)],
    ...entries.map(e => [
      fmtDate(e.date),
      e.voucherNo,
      e.particulars,
      e.type === 'receipt' ? fmt(e.amount) : '',
      e.type === 'payment' ? fmt(e.amount) : '',
      fmt(e.runningBalance),
    ]),
  ];

  autoTable(doc, {
    startY,
    head: [['Date', 'Voucher No.', 'Particulars', 'Receipt (Dr)', 'Payment (Cr)', 'Balance']],
    body,
    foot: [['', '', 'Total', fmt(totalReceipts), fmt(totalPayments), fmt(closingBalance)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(3, 4, 5),
  });

  const sigY = (doc as any).lastAutoTable.finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], sigY, undefined,
    [sig.accountant, sig.secretary, sig.president]);

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('CashBook', society));
}

export function generateBankBookPDF(
  entries: BankBookEntry[],
  society: SocietySettings,
  openingBalance: number,
  language: 'hi' | 'en'
) {
  const doc = new jsPDF();
  const { startY, font } = addHeader(doc, 'Bank Book', society, `Financial Year: ${society.financialYear}`, { reportCode: 'BB' });

  const totalDeposits = entries.filter(e => e.type === 'deposit').reduce((s, e) => s + e.amount, 0);
  const totalWithdrawals = entries.filter(e => e.type === 'withdrawal').reduce((s, e) => s + e.amount, 0);
  const closingBalance = entries.length > 0 ? entries[entries.length - 1].runningBalance : openingBalance;

  const body = [
    ['', 'OB', 'Opening Balance', fmt(openingBalance), '', fmt(openingBalance)],
    ...entries.map(e => [
      fmtDate(e.date),
      e.voucherNo,
      e.particulars,
      e.type === 'deposit' ? fmt(e.amount) : '',
      e.type === 'withdrawal' ? fmt(e.amount) : '',
      fmt(e.runningBalance),
    ]),
  ];

  autoTable(doc, {
    startY,
    head: [['Date', 'Voucher No.', 'Particulars', 'Deposit', 'Withdrawal', 'Balance']],
    body,
    foot: [['', '', 'Total', fmt(totalDeposits), fmt(totalWithdrawals), fmt(closingBalance)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(3, 4, 5),
  });

  const sigY = (doc as any).lastAutoTable.finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], sigY, undefined,
    [sig.accountant, sig.secretary, sig.president]);

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('BankBook', society));
}

export function generateTrialBalancePDF(balances: AccountBalance[], society: SocietySettings, asOnDate: string, language: 'hi' | 'en') {
  const doc = new jsPDF();
  const { startY, font } = addHeader(doc, 'Trial Balance', society, `As on: ${fmtDate(asOnDate)} | FY: ${society.financialYear}`, { reportCode: 'TB' });

  // G9: Empty data guard
  if (balances.length === 0) {
    addNoDataMessage(doc, font, startY);
    addPageNumbers(doc, font, society?.name);
    doc.save(pdfFileName('TrialBalance', society));
    return;
  }

  const totalDebit = balances.reduce((s, b) => s + b.totalDebit, 0);
  const totalCredit = balances.reduce((s, b) => s + b.totalCredit, 0);

  const body = balances.map((b, i) => [
    String(i + 1),
    b.account.name, // Always English in PDF
    b.account.type.charAt(0).toUpperCase() + b.account.type.slice(1),
    b.totalDebit > 0 ? fmt(b.totalDebit) : '',
    b.totalCredit > 0 ? fmt(b.totalCredit) : '',
  ]);

  autoTable(doc, {
    startY,
    head: [['#', 'Account Name', 'Type', 'Debit (Dr)', 'Credit (Cr)']],
    body,
    foot: [['', '', 'Total', fmt(totalDebit), fmt(totalCredit)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(3, 4),
  });

  const tbFinalY = (doc as any).lastAutoTable.finalY + 10;
  const tbBalanced = Math.abs(totalDebit - totalCredit) < 1;
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.setTextColor(tbBalanced ? 22 : 220, tbBalanced ? 163 : 38, tbBalanced ? 74 : 38);
  doc.text(
    tbBalanced ? '✓ Trial Balance is Balanced — Debit total equals Credit total.' : `✗ Trial Balance is NOT balanced. Difference: ${fmt(Math.abs(totalDebit - totalCredit))}`,
    15, tbFinalY
  );
  doc.setTextColor(0);
  const tbSig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], tbFinalY + 6,
    'Certified that the above Trial Balance has been prepared from the Books of Account of the Society.',
    [tbSig.accountant, tbSig.secretary, tbSig.president]
  );
  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('TrialBalance', society));
}

export function generateIncomeExpenditurePDF(
  incomeItems: { name: string; nameHi: string; amount: number }[],
  expenseItems: { name: string; nameHi: string; amount: number }[],
  society: SocietySettings,
  language: 'hi' | 'en',
  reserveFund: number = 0
) {
  const doc = new jsPDF('landscape');
  const { startY, font } = addHeader(doc, 'Income & Expenditure Account', society, `Financial Year: ${society.financialYear}`, { reportCode: 'IE' });

  const totalIncome = incomeItems.reduce((s, i) => s + i.amount, 0);
  const totalExpenses = expenseItems.reduce((s, i) => s + i.amount, 0);
  const netProfit = totalIncome - totalExpenses;
  const isSurplus = netProfit >= 0;
  const distributableSurplus = isSurplus ? netProfit - reserveFund : 0;

  // Both sides of T-account must show the same grand total
  const grandTotal = isSurplus ? totalIncome : totalExpenses;

  const expBody: string[][] = [
    ...expenseItems.map(i => [i.name, fmt(i.amount)]),
    ...(isSurplus && reserveFund > 0 ? [[`Statutory Reserve Fund (${society.reserveFundPct ?? 25}%)`, fmt(reserveFund)]] : []),
    ...(isSurplus ? [['Surplus carried to Balance Sheet', fmt(distributableSurplus)]] : [['Deficit carried to Balance Sheet', fmt(Math.abs(netProfit))]]),
  ];
  const incBody: string[][] = [
    ...incomeItems.map(i => [i.name, fmt(i.amount)]),
    ...(!isSurplus ? [['Deficit carried from Expenditure', fmt(Math.abs(netProfit))]] : []),
  ];

  // Expenditure side (left half)
  autoTable(doc, {
    startY,
    margin: { left: 15, right: 158 },
    head: [['Expenditure (Dr)', 'Amount']],
    body: expBody,
    foot: [['Total', fmt(grandTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [220, 53, 69], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(1),
  });
  const expFinalY = (doc as any).lastAutoTable.finalY;

  // Income side (right half)
  autoTable(doc, {
    startY,
    margin: { left: 154, right: 15 },
    head: [['Income (Cr)', 'Amount']],
    body: incBody,
    foot: [['Total', fmt(grandTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(1),
  });

  const ieFinalY = Math.max(expFinalY, (doc as any).lastAutoTable.finalY) + 10;
  // M-2: Auditor's Certificate
  addAuditorCertificate(doc, font, society, 'Income & Expenditure Account', ieFinalY);
  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('IncomeExpenditure', society));
}

export function generateReceiptsPaymentsPDF(data: ReceiptsPaymentsData, society: SocietySettings) {
  const doc = new jsPDF('landscape');
  const { startY, font } = addHeader(doc, 'Receipts & Payments Account', society, `Financial Year: ${society.financialYear}`, { reportCode: 'RP' });

  const { openingCash, openingBank, receipts, payments, closingCash, closingBank } = data;
  const totalReceipts = receipts.reduce((s, r) => s + r.amount, 0);
  const totalPayments = payments.reduce((s, p) => s + p.amount, 0);
  const drTotal = openingCash + openingBank + totalReceipts;
  const crTotal = totalPayments + closingCash + closingBank;

  // Dr side: Opening Balance + Receipts
  const drBody: string[][] = [
    ['To Balance b/d (Opening)', ''],
    ['  Cash in Hand', fmt(openingCash)],
    ['  Cash at Bank', fmt(openingBank)],
    ...receipts.map(r => [`To ${r.accountName}`, fmt(r.amount)]),
  ];

  // Cr side: Payments + Closing Balance
  const crBody: string[][] = [
    ...payments.map(p => [`By ${p.accountName}`, fmt(p.amount)]),
    ['By Balance c/d (Closing)', ''],
    ['  Cash in Hand', fmt(closingCash)],
    ['  Cash at Bank', fmt(closingBank)],
  ];

  // Dr (Receipts) side — left half
  autoTable(doc, {
    startY,
    margin: { left: 15, right: 158 },
    head: [['Dr — Receipts', 'Amount']],
    body: drBody,
    foot: [['Total', fmt(drTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(1),
  });
  const drFinalY = (doc as any).lastAutoTable.finalY;

  // Cr (Payments) side — right half
  autoTable(doc, {
    startY,
    margin: { left: 154, right: 15 },
    head: [['Cr — Payments', 'Amount']],
    body: crBody,
    foot: [['Total', fmt(crTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [220, 53, 69], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(1),
  });

  const rpFinalY = Math.max(drFinalY, (doc as any).lastAutoTable.finalY) + 10;
  const rpSig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], rpFinalY,
    'Certified that the above Receipts & Payments Account is correct as per the Books of Account of the Society.',
    [rpSig.accountant, rpSig.secretary, rpSig.president]
  );
  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('ReceiptsPayments', society));
}

export function generateBalanceSheetPDF(
  assetBalances: AccountBalance[],
  liabilityBalances: AccountBalance[],
  netProfit: number,
  society: SocietySettings,
  language: 'hi' | 'en',
  reserveFund: number = 0
) {
  const doc = new jsPDF('landscape');
  const { startY, font } = addHeader(doc, 'Balance Sheet', society, `As at 31st March 20${society.financialYear.split('-')[1]}`, { reportCode: 'BS' });

  const totalAssets = assetBalances.reduce((s, b) => s + b.netBalance, 0);
  // C-1 FIX: Use -netBalance (not Math.abs) so contra-equity accounts (e.g. Dividend Distribution)
  // correctly reduce the equity total instead of being added to it.
  const totalLiabilities = liabilityBalances.reduce((s, b) => s + (-b.netBalance), 0) + netProfit;
  const distributableSurplus = netProfit > 0 ? netProfit - reserveFund : 0;
  const pyBalances = society.previousYearBalances || {};
  const pyYear = society.previousFinancialYear || '';
  const hasPY = pyYear && Object.keys(pyBalances).length > 0;
  const getPY = (id: string) => pyBalances[id] ?? 0;

  const liabHead = hasPY
    ? [['Capital & Liabilities', pyYear, society.financialYear]]
    : [['Capital & Liabilities', 'Amount']];
  const assetHead = hasPY
    ? [['Assets', pyYear, society.financialYear]]
    : [['Assets', 'Amount']];

  const liabBody = [
    ...liabilityBalances
      .filter(b => b.netBalance !== 0 || getPY(b.account.id) !== 0)
      .map(b => {
        // Contra-equity (debit-nature equity, e.g. Dividend Distribution): netBalance > 0 → show in parentheses
        const isContra = b.netBalance > 0;
        const displayVal = isContra ? `(${fmt(b.netBalance)})` : fmt(Math.abs(b.netBalance));
        const label = isContra ? `${b.account.name} (Dr)` : b.account.name;
        return hasPY
          ? [label, getPY(b.account.id) ? fmt(getPY(b.account.id)) : '—', displayVal]
          : [label, displayVal];
      }),
    ...(netProfit > 0 && reserveFund > 0
      ? [hasPY ? [`Statutory Reserve Fund ${society.reserveFundPct ?? 25}%`, '—', fmt(reserveFund)] : [`Statutory Reserve Fund — ${society.reserveFundPct ?? 25}%`, fmt(reserveFund)]]
      : []),
    ...(netProfit > 0
      ? [hasPY ? ['Distributable Surplus', '—', fmt(distributableSurplus)] : ['Distributable Surplus', fmt(distributableSurplus)]]
      : []),
    ...(netProfit < 0
      ? [hasPY ? ['Deficit (Current Year)', '—', `(${fmt(Math.abs(netProfit))})`] : ['Deficit (Current Year)', `(${fmt(Math.abs(netProfit))})`]]
      : []),
  ];

  const assetBody = assetBalances
    .filter(b => b.netBalance !== 0 || getPY(b.account.id) !== 0)
    .map(b => {
      const display = b.netBalance < 0 ? `(${fmt(Math.abs(b.netBalance))})` : fmt(b.netBalance);
      return hasPY
        ? [b.netBalance < 0 ? `${b.account.name} (Cr)` : b.account.name, getPY(b.account.id) ? fmt(getPY(b.account.id)) : '—', display]
        : [b.netBalance < 0 ? `${b.account.name} (Cr)` : b.account.name, display];
    });

  const pyLiabTotal = liabilityBalances.reduce((s, b) => s + getPY(b.account.id), 0);
  const pyAssetTotal = assetBalances.reduce((s, b) => s + getPY(b.account.id), 0);

  const colStyles = hasPY
    ? { 1: { halign: 'right' as const }, 2: { halign: 'right' as const } }
    : { 1: { halign: 'right' as const } };

  // Capital & Liabilities (left half)
  autoTable(doc, {
    startY,
    margin: { left: 15, right: 158 },
    head: liabHead,
    body: liabBody,
    foot: [hasPY ? ['Total', fmt(pyLiabTotal), fmt(totalLiabilities)] : ['Total', fmt(totalLiabilities)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: colStyles,
    didParseCell: rightAlignAmountColumns(...(hasPY ? [1, 2] : [1])),
  });
  const liabFinalY = (doc as any).lastAutoTable.finalY;

  // Assets (right half)
  autoTable(doc, {
    startY,
    margin: { left: 154, right: 15 },
    head: assetHead,
    body: assetBody,
    foot: [hasPY ? ['Total', fmt(pyAssetTotal), fmt(totalAssets)] : ['Total', fmt(totalAssets)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: colStyles,
    didParseCell: rightAlignAmountColumns(...(hasPY ? [1, 2] : [1])),
  });
  const assetFinalY = (doc as any).lastAutoTable.finalY;

  // Use the taller of the two side-by-side tables to avoid overlap
  const bsFinalY = Math.max(liabFinalY, assetFinalY) + 10;
  // M-1: Auditor's Certificate
  addAuditorCertificate(doc, font, society, 'Balance Sheet', bsFinalY);
  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('BalanceSheet', society));
}

export function generateLedgerPDF(
  entries: { date: string; voucherNo: string; particulars: string; debit: number; credit: number; balance: number; balanceType: 'Dr' | 'Cr' }[],
  account: LedgerAccount,
  society: SocietySettings,
  language: 'hi' | 'en',
  fromDate?: string,
  toDate?: string
) {
  const doc = new jsPDF();
  const subtitle = fromDate && toDate
    ? `Account: ${account.name} | ${fmtDate(fromDate)} to ${fmtDate(toDate)}`
    : `Account: ${account.name} | FY: ${society.financialYear}`;
  const { startY, font } = addHeader(doc, 'Ledger Account Statement', society, subtitle, { reportCode: 'LDG' });

  const totalDebit = entries.reduce((s, e) => s + e.debit, 0);
  const totalCredit = entries.reduce((s, e) => s + e.credit, 0);
  const closing = entries[entries.length - 1];

  const body = entries.map(e => [
    fmtDate(e.date),
    e.voucherNo,
    e.particulars,
    e.debit > 0 ? fmt(e.debit) : '',
    e.credit > 0 ? fmt(e.credit) : '',
    `${fmt(e.balance)} ${e.balanceType}`,
  ]);

  autoTable(doc, {
    startY,
    head: [['Date', 'Voucher No.', 'Particulars', 'Debit (Dr)', 'Credit (Cr)', 'Balance']],
    body,
    foot: [['', '', 'Total', fmt(totalDebit), fmt(totalCredit), closing ? `${fmt(closing.balance)} ${closing.balanceType}` : '']],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(3, 4, 5),
  });

  const sigY = (doc as any).lastAutoTable.finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], sigY, undefined,
    [sig.accountant, sig.secretary, sig.president]);

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName(`Ledger_${account.name.replace(/\s+/g, '_')}`, society));
}

export function generateMemberPassbookPDF(
  member: Member,
  entries: MemberLedgerEntry[],
  society: SocietySettings
) {
  const doc = new jsPDF();
  const { startY, font } = addHeader(doc, 'Member Share Ledger', society, `Member: ${member.name} | ID: ${member.memberId}`, { reportCode: 'MSL' });

  // Member info box
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.text(`Father/Husband: ${member.fatherName || '-'}`, 15, startY + 2);
  doc.text(`Phone: ${member.phone}`, 15, startY + 7);
  doc.text(`Address: ${member.address || '-'}`, 15, startY + 12);
  doc.text(`Join Date: ${fmtDate(member.joinDate)}`, 120, startY + 2);
  doc.text(`Status: ${member.status.toUpperCase()}`, 120, startY + 7);

  const totalCredit = entries.reduce((s, e) => s + e.credit, 0);
  const totalDebit = entries.reduce((s, e) => s + e.debit, 0);
  const closing = entries[entries.length - 1];

  const body = entries.map(e => [
    fmtDate(e.date),
    e.voucherNo,
    e.particulars,
    e.credit > 0 ? fmt(e.credit) : '',
    e.debit > 0 ? fmt(e.debit) : '',
    fmt(e.balance),
  ]);

  autoTable(doc, {
    startY: startY + 18,
    head: [['Date', 'Voucher No.', 'Particulars', 'Credit (Cr)', 'Debit (Dr)', 'Balance']],
    body,
    foot: [['', '', 'Total', fmt(totalCredit), fmt(totalDebit), closing ? fmt(closing.balance) : '']],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(3, 4, 5),
  });

  // Signature line
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(9);
  doc.text('Member Signature: ___________________', 15, finalY);
  doc.text('Secretary: ___________________', 120, finalY);

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName(`MemberPassbook_${member.memberId}`, society));
}

// ─── Share Register PDF ─────────────────────────────────────────────────────
export function generateShareRegisterPDF(members: Member[], society: SocietySettings): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'SHARE REGISTER', society, `Financial Year: ${society.financialYear}`, { reportCode: 'SR' });

  const rows = members.map((m, i) => [
    String(i + 1),
    m.memberId,
    m.name,
    m.fatherName || '',
    fmtDate(m.joinDate),
    m.shareCertNo || '',
    m.shareCount != null ? String(m.shareCount) : '',
    m.shareFaceValue != null ? fmt(m.shareFaceValue) : '',
    fmt(m.shareCapital),
    m.nomineeName || '',
    m.nomineeRelation || '',
    m.status === 'active' ? 'Active' : 'Inactive',
  ]);

  autoTable(doc, {
    startY: startY + 2,
    head: [['S.No', 'Member ID', 'Name', 'Father/Husband', 'Join Date', 'Cert. No.', 'Shares', 'Face Val.', 'Total Capital', 'Nominee', 'Relation', 'Status']],
    body: rows,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 7: { halign: 'right' }, 8: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(7, 8),
  });

  const srSummaryY = (doc as any).lastAutoTable.finalY + 8;
  const totalCap = members.reduce((s, m) => s + m.shareCapital, 0);
  doc.setFontSize(9);
  doc.setFont(font, 'bold');
  doc.text(`Total Members: ${members.length}   |   Total Share Capital: ${fmt(totalCap)}`, 15, srSummaryY);

  // M-5: Secretary certification
  const srCertY = srSummaryY + 8;
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.setTextColor(60);
  const certLine = 'Certified that the above is a true and correct Register of Members and Share Capital of the Society as maintained in the books.';
  doc.text(certLine, 15, srCertY);
  doc.setTextColor(0);
  addSignatureBlock(doc, font, ['Secretary / Manager\n(with Seal)', 'President\n(with Seal)'], srCertY + 8);
  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('ShareRegister', society));
}

// ─── Loan Register PDF ────────────────────────────────────────────────────────
export function generateLoanRegisterPDF(loans: Loan[], members: Member[], society: SocietySettings): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'LOAN REGISTER', society, `Financial Year: ${society.financialYear}`, { reportCode: 'LR' });

  const getMemberName = (id: string) => members.find(m => m.id === id)?.name || id;
  const loanTypeLabel = (t: string) => t === 'short-term' ? 'S/T' : t === 'medium-term' ? 'M/T' : 'L/T';

  const rows = loans.map(l => [
    l.loanNo,
    getMemberName(l.memberId),
    loanTypeLabel(l.loanType),
    l.purpose || '',
    fmt(l.amount),
    `${l.interestRate}%`,
    fmtDate(l.disbursementDate),
    fmtDate(l.dueDate),
    fmt(l.repaidAmount),
    fmt(l.amount - l.repaidAmount),
    l.status.toUpperCase(),
  ]);

  autoTable(doc, {
    startY: startY + 2,
    head: [['Loan No.', 'Member', 'Type', 'Purpose', 'Amount', 'Rate', 'Disbursed', 'Due Date', 'Repaid', 'Outstanding', 'Status']],
    body: rows,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 4: { halign: 'right' }, 8: { halign: 'right' }, 9: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(4, 8, 9),
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const totalDisbursed = loans.reduce((s, l) => s + l.amount, 0);
  const totalOutstanding = loans.filter(l => l.status !== 'cleared').reduce((s, l) => s + (l.amount - l.repaidAmount), 0);
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text(`Total Loans: ${loans.length}   |   Total Disbursed: ${fmt(totalDisbursed)}   |   Outstanding: ${fmt(totalOutstanding)}`, 15, finalY);

  const sigY = finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], sigY, undefined,
    [sig.accountant, sig.secretary, sig.president]);

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('LoanRegister', society));
}

// ─── Asset Register PDF ────────────────────────────────────────────────────────
export function generateAssetRegisterPDF(assets: Asset[], society: SocietySettings): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'ASSET REGISTER', society, `As on: ${new Date().toLocaleDateString('en-IN')} | Depreciation Method: SLM`, { reportCode: 'AR' });

  const calcBookValue = (a: Asset): number => {
    if (!a.purchaseDate || !a.depreciationRate) return a.cost;
    const now = new Date();
    const yearEnd = now.getMonth() >= 3 ? new Date(now.getFullYear(), 2, 31) : new Date(now.getFullYear() - 1, 2, 31);
    const yearsElapsed = Math.max(0, (yearEnd.getTime() - new Date(a.purchaseDate).getTime()) / (365.25 * 24 * 3600 * 1000));
    return Math.max(0, a.cost - a.cost * (a.depreciationRate / 100) * yearsElapsed);
  };

  const rows = assets.map((a, i) => {
    const bookVal = calcBookValue(a);
    return [
      String(i + 1),
      a.assetNo,
      a.name,
      a.category,
      a.location || '',
      fmtDate(a.purchaseDate),
      fmt(a.cost),
      `${a.depreciationRate}%`,
      fmt(a.cost - bookVal),
      fmt(bookVal),
      a.status === 'active' ? 'Active' : 'Disposed',
    ];
  });

  autoTable(doc, {
    startY: startY + 2,
    head: [['S.No', 'Asset No.', 'Asset Name', 'Category', 'Location', 'Purchase Date', 'Cost', 'Dep%', 'Acc. Dep.', 'Book Value', 'Status']],
    body: rows,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 6: { halign: 'right' }, 7: { halign: 'center' }, 8: { halign: 'right' }, 9: { halign: 'right' } },
    foot: [[
      '', '', '', '', '', 'Total',
      fmt(assets.reduce((s, a) => s + a.cost, 0)),
      '',
      fmt(assets.reduce((s, a) => s + (a.cost - calcBookValue(a)), 0)),
      fmt(assets.reduce((s, a) => s + calcBookValue(a), 0)),
      '',
    ]],
    footStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    didParseCell: rightAlignAmountColumns(6, 8, 9),
  });

  const sigY = (doc as any).lastAutoTable.finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], sigY, undefined,
    [sig.accountant, sig.secretary, sig.president]);

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('AssetRegister', society));
}

// ─── Audit Rectification Register PDF ─────────────────────────────────────────
export function generateAuditRegisterPDF(objections: AuditObjection[], society: SocietySettings): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'AUDIT RECTIFICATION REGISTER', society, `Prepared on: ${new Date().toLocaleDateString('en-IN')}`, { reportCode: 'AUR' });

  const statusLabel = (s: string) => s === 'rectified' ? 'Rectified' : s === 'partial' ? 'Partial' : 'Pending';

  const rows = objections.map(o => [
    o.objectionNo,
    o.auditYear,
    o.paraNo,
    o.category.toUpperCase(),
    o.objection.length > 60 ? o.objection.substring(0, 60) + '...' : o.objection,
    o.amountInvolved > 0 ? fmt(o.amountInvolved) : '—',
    o.dueDate ? fmtDate(o.dueDate) : '—',
    o.actionTaken ? (o.actionTaken.length > 40 ? o.actionTaken.substring(0, 40) + '...' : o.actionTaken) : '—',
    o.rectifiedDate ? fmtDate(o.rectifiedDate) : '—',
    statusLabel(o.status),
  ]);

  autoTable(doc, {
    startY: startY + 2,
    head: [['Objn. No.', 'Audit Year', 'Para', 'Category', 'Objection', 'Amount', 'Due Date', 'Action Taken', 'Rect. Date', 'Status']],
    body: rows,
    styles: { fontSize: 7.5 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      4: { cellWidth: 55 },
      7: { cellWidth: 45 },
      5: { halign: 'right' },
    },
    didDrawCell: (data) => {
      // Color status column
      if (data.section === 'body' && data.column.index === 9) {
        const val = data.cell.raw as string;
        if (val === 'Rectified') { doc.setTextColor(22, 163, 74); }
        else if (val === 'Partial') { doc.setTextColor(217, 119, 6); }
        else { doc.setTextColor(220, 38, 38); }
      }
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const pending = objections.filter(o => o.status === 'pending').length;
  const rectified = objections.filter(o => o.status === 'rectified').length;
  const totalAmt = objections.reduce((s, o) => s + o.amountInvolved, 0);
  doc.setFontSize(9);
  doc.setFont(font, 'normal');
  doc.text(`Total: ${objections.length} | Pending: ${pending} | Rectified: ${rectified} | Total Amount Involved: ${fmt(totalAmt)}`, 15, finalY);

  // G8 FIX: Use standardized signature block
  addSignatureBlock(doc, font, ['Secretary', 'Auditor', 'President'], finalY + 10);

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('AuditRegister', society));
}

export function generateDayBookPDF(
  entries: { id: string; date: string; voucherNo: string; type: string; debitAccountId: string; creditAccountId: string; amount: number; narration?: string }[],
  accounts: LedgerAccount[],
  society: SocietySettings,
  fromDate: string,
  toDate: string,
  language: 'hi' | 'en'
) {
  const doc = new jsPDF({ orientation: 'landscape' });
  const getAccName = (id: string) => accounts.find(a => a.id === id)?.name || id;
  const typeLabel = (t: string) => t === 'receipt' ? 'Receipt' : t === 'payment' ? 'Payment' : 'Journal';

  const subtitle = `${fmtDate(fromDate)} to ${fmtDate(toDate)} | FY: ${society.financialYear}`;
  const { startY, font } = addHeader(doc, 'Day Book', society, subtitle, { reportCode: 'DB' });

  // Group by date
  const groups: { date: string; items: typeof entries }[] = [];
  entries.forEach(v => {
    const last = groups[groups.length - 1];
    if (last && last.date === v.date) last.items.push(v);
    else groups.push({ date: v.date, items: [v] });
  });

  // Running cash only (Day Book = cash based)
  const cashAccOB = accounts.find(a => a.id === ACCOUNT_IDS.CASH)?.openingBalance || 0;
  // C-2 FIX: Use getVoucherLines() to correctly calculate pre-period cash balance
  // including multi-line Expert Mode vouchers.
  const firstDate = entries.length > 0 ? entries[0].date : null;
  let runCash = cashAccOB;
  if (firstDate) {
    entries.forEach(v => {
      if (v.date >= firstDate) return;
      getVoucherLines(v).forEach(l => {
        if (l.accountId === ACCOUNT_IDS.CASH)
          runCash += l.type === 'Dr' ? l.amount : -l.amount;
      });
    });
  }

  // Columns: Date/Voucher | Particulars | Debit (Rs.) | Credit (Rs.)
  // Each voucher = 2 rows: Dr row + Cr row
  const body: (string[])[] = [];
  const dayHeaderRows: number[] = [];
  const openingBalRows: number[] = [];
  const dayTotalRows: number[] = [];
  const closingBalRows: number[] = [];
  const drRows: number[] = [];
  const crRows: number[] = [];

  groups.forEach(group => {
    const dayDate = fmtDate(group.date);
    const dayTotal = group.items.reduce((s, v) => s + v.amount, 0);
    const dayReceipts = group.items.filter(v => v.type === 'receipt').reduce((s, v) => s + v.amount, 0);
    const dayPayments = group.items.filter(v => v.type === 'payment').reduce((s, v) => s + v.amount, 0);

    // Day header row (spans all 4 cols)
    dayHeaderRows.push(body.length);
    body.push([
      `${dayDate}`,
      `${group.items.length} transaction(s)   Rcpt: ${fmt(dayReceipts)}   Pmnt: ${fmt(dayPayments)}`,
      '',
      `Total: ${fmt(dayTotal)}`,
    ]);

    // Opening balance row
    openingBalRows.push(body.length);
    body.push(['Opening Balance', `Cash in Hand (Opening): ${fmt(runCash)}`, fmt(runCash), '']);

    // C-2 FIX: Use getVoucherLines() for correct Dr/Cr display in multi-line vouchers.
    group.items.forEach((v, i) => {
      const vLines = getVoucherLines(v);
      const narration = v.narration ? `  (${v.narration})` : '';
      const voucherMeta = `${fmtDate(v.date)}\n${typeLabel(v.type)}\n#${i + 1} ${v.voucherNo}`;

      vLines.forEach((l, li) => {
        const label = l.type === 'Dr'
          ? `${getAccName(l.accountId)}  Dr.`
          : `    To ${getAccName(l.accountId)}  Cr.${li === vLines.length - 1 ? narration : ''}`;
        if (l.type === 'Dr') {
          drRows.push(body.length);
          body.push([li === 0 ? voucherMeta : '', label, fmt(l.amount), '']);
        } else {
          crRows.push(body.length);
          body.push(['', label, '', fmt(l.amount)]);
        }
      });
    });

    // Day total row
    dayTotalRows.push(body.length);
    body.push(['Day Total', `${dayDate}`, fmt(dayTotal), fmt(dayTotal)]);

    // C-2 FIX: Update running cash using getVoucherLines() for multi-line voucher support.
    group.items.forEach(v => {
      getVoucherLines(v).forEach(l => {
        if (l.accountId === ACCOUNT_IDS.CASH)
          runCash += l.type === 'Dr' ? l.amount : -l.amount;
      });
    });

    // Closing balance row
    closingBalRows.push(body.length);
    body.push(['Closing Balance', `Cash in Hand (Closing): ${fmt(runCash)}`, fmt(runCash), '']);
  });

  const grandTotal = entries.reduce((s, v) => s + v.amount, 0);

  autoTable(doc, {
    startY,
    head: [['Date / Voucher', 'Particulars', 'Debit (Rs.)', 'Credit (Rs.)']],
    body,
    foot: [['', 'GRAND TOTAL', fmt(grandTotal), fmt(grandTotal)]],
    styles: { fontSize: 8, cellPadding: 2.5 },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold', fontSize: 9 },
    footStyles: { fillColor: [220, 230, 255], fontStyle: 'bold', textColor: 20, fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 42 },
      1: { cellWidth: 145 },
      2: { cellWidth: 40, halign: 'right' },
      3: { cellWidth: 40, halign: 'right' },
    },
    didParseCell: (data) => {
      if (data.section !== 'body') return;
      const rowIdx = data.row.index;
      if (dayHeaderRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [41, 82, 163];
        data.cell.styles.textColor = [255, 255, 255];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fontSize = 8.5;
      } else if (openingBalRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [255, 248, 220];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = [120, 80, 0];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      } else if (drRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [240, 245, 255];
        data.cell.styles.textColor = [30, 50, 150];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      } else if (crRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [245, 255, 245];
        data.cell.styles.textColor = [20, 100, 40];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      } else if (dayTotalRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [230, 236, 255];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = [30, 30, 150];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      } else if (closingBalRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [225, 245, 225];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = [20, 100, 20];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      }
    },
  });

  const sigY = (doc as any).lastAutoTable.finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], sigY, undefined,
    [sig.accountant, sig.secretary, sig.president]);

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('DayBook', society));
}

export function generateTradingAccountPDF(
  data: {
    salesItems:        { name: string; amount: number }[];
    closingStockItems: { name: string; amount: number }[];
    openingStockItems: { name: string; amount: number }[];
    purchaseItems:     { name: string; amount: number }[];
    directExpItems:    { name: string; amount: number }[];
    totalSales: number; totalClosingStock: number;
    totalOpeningStock: number; totalPurchases: number; totalDirectExp: number;
    grossProfit: number;
  },
  society: SocietySettings
) {
  const doc = new jsPDF('landscape');
  const { startY, font } = addHeader(doc, 'Trading Account', society, `Financial Year: ${society.financialYear}`, { reportCode: 'TA' });

  const isProfit  = data.grossProfit >= 0;
  const grandTotal = Math.abs(data.grossProfit) +
    (isProfit
      ? data.totalOpeningStock + data.totalPurchases + data.totalDirectExp
      : data.totalSales + data.totalClosingStock);

  // ── Dr side (left) ────────────────────────────────────────────────────────
  const drBody: (string | { content: string; styles: object })[][] = [];

  if (data.openingStockItems.length > 0) {
    drBody.push([{ content: 'Opening Stock', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.openingStockItems.forEach(i => drBody.push([`  ${i.name}`, fmt(i.amount)]));
    drBody.push([{ content: 'Total Opening Stock', styles: { fontStyle: 'bold' } }, fmt(data.totalOpeningStock)]);
  }

  if (data.purchaseItems.length > 0) {
    drBody.push([{ content: 'Purchases', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.purchaseItems.forEach(i => drBody.push([`  ${i.name}`, fmt(i.amount)]));
  }

  if (data.directExpItems.length > 0) {
    drBody.push([{ content: 'Direct Expenses', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.directExpItems.forEach(i => drBody.push([`  ${i.name}`, fmt(i.amount)]));
  }

  if (isProfit && data.grossProfit > 0) {
    drBody.push([{ content: 'Gross Profit (to I&E Account)', styles: { fontStyle: 'bold', textColor: [25, 135, 84] } }, fmt(data.grossProfit)]);
  }

  // ── Cr side (right) ───────────────────────────────────────────────────────
  const crBody: (string | { content: string; styles: object })[][] = [];

  if (data.salesItems.length > 0) {
    crBody.push([{ content: 'Sales (Trading Income)', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.salesItems.forEach(i => crBody.push([`  ${i.name}`, fmt(i.amount)]));
    crBody.push([{ content: 'Total Sales', styles: { fontStyle: 'bold' } }, fmt(data.totalSales)]);
  }

  if (data.closingStockItems.length > 0) {
    crBody.push([{ content: 'Closing Stock', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.closingStockItems.forEach(i => crBody.push([`  ${i.name}`, fmt(i.amount)]));
    crBody.push([{ content: 'Total Closing Stock', styles: { fontStyle: 'bold' } }, fmt(data.totalClosingStock)]);
  }

  if (!isProfit) {
    crBody.push([{ content: 'Gross Loss (to I&E Account)', styles: { fontStyle: 'bold', textColor: [220, 53, 69] } }, fmt(Math.abs(data.grossProfit))]);
  }

  // Render Dr table (left half)
  autoTable(doc, {
    startY,
    margin: { left: 15, right: 155 },
    head: [['Debit (Dr)', 'Amount']],
    body: drBody.length > 0 ? drBody : [['No entries', '']],
    foot: [['Grand Total', fmt(grandTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [220, 53, 69], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right', cellWidth: 30 } },
    didParseCell: rightAlignAmountColumns(1),
  });
  const taDrFinalY = (doc as any).lastAutoTable.finalY;

  // Render Cr table (right half)
  autoTable(doc, {
    startY,
    margin: { left: 151, right: 15 },
    head: [['Credit (Cr)', 'Amount']],
    body: crBody.length > 0 ? crBody : [['No entries', '']],
    foot: [['Grand Total', fmt(grandTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right', cellWidth: 30 } },
    didParseCell: rightAlignAmountColumns(1),
  });

  // G8 FIX: Use standardized signature block — use max of both tables to avoid overlap
  const finalY = Math.max(taDrFinalY, (doc as any).lastAutoTable.finalY) + 10;
  const taSig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary', 'Chairman'], finalY,
    'Certified that the above Trading Account has been prepared from the Books of Account of the Society.',
    [taSig.accountant, taSig.secretary, taSig.president]
  );

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('TradingAccount', society));
}

export function generateSalarySlipPDF(
  record: SalaryRecord,
  employee: Employee,
  society: SocietySettings
): void {
  const doc = new jsPDF({ orientation: 'portrait', format: 'a5' });
  const font = setupFont(doc);
  const pageW = doc.internal.pageSize.width;
  const cx = pageW / 2;

  // ── Header ──────────────────────────────────────────────────────────────
  doc.setFontSize(13);
  doc.setFont(font, 'bold');
  doc.text(society.name, cx, 14, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.text(`Reg. No: ${society.registrationNo}  |  ${society.address}`, cx, 20, { align: 'center' });
  doc.setFontSize(11);
  doc.setFont(font, 'bold');
  doc.text('SALARY SLIP', cx, 28, { align: 'center' });
  doc.setDrawColor(41, 82, 163);
  doc.setLineWidth(0.5);
  doc.line(10, 31, pageW - 10, 31);

  // ── Slip meta ────────────────────────────────────────────────────────────
  const [yr, mo] = record.month.split('-');
  const monthName = new Date(Number(yr), Number(mo) - 1, 1)
    .toLocaleString('en-IN', { month: 'long', year: 'numeric' });

  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.text(`Slip No: ${record.slipNo}`, 12, 37);
  doc.text(`Month: ${monthName}`, cx, 37, { align: 'center' });
  doc.text(`Date: ${record.isPaid && record.paidDate ? fmtDate(record.paidDate) : fmtDate(record.createdAt)}`, pageW - 12, 37, { align: 'right' });

  // ── Employee details box ─────────────────────────────────────────────────
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.rect(10, 40, pageW - 20, 22);

  doc.setFont(font, 'bold');
  doc.setFontSize(8);
  doc.text('Employee Details', 13, 46);
  doc.setFont(font, 'normal');
  doc.text(`Emp No : ${employee.empNo}`, 13, 52);
  doc.text(`Name   : ${employee.name}`, 13, 57);
  doc.text(`Designation: ${employee.designation}`, cx + 5, 52);
  doc.text(`Join Date  : ${fmtDate(employee.joinDate)}`, cx + 5, 57);

  // ── Earnings & Deductions table ──────────────────────────────────────────
  autoTable(doc, {
    startY: 66,
    head: [['Earnings', 'Amount (Rs.)', 'Deductions', 'Amount (Rs.)']],
    body: [
      ['Basic Salary',   fmt(record.basicSalary), 'Deductions', fmt(record.deductions)],
      ['Allowances',     fmt(record.allowances),  '',           ''],
      ['Gross Salary',   fmt(record.basicSalary + record.allowances), '', ''],
    ],
    foot: [['Net Salary Payable', '', '', fmt(record.netSalary)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    footStyles: { fillColor: [240, 248, 240], textColor: [0, 100, 0], fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' }, 3: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(1, 3),
  });

  // ── Payment info ─────────────────────────────────────────────────────────
  const afterTableY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  const payMode = { cash: 'Cash', bank: 'Bank Transfer', credit: 'Credit' }[record.paymentMode] ?? record.paymentMode;
  doc.text(`Payment Mode: ${payMode}`, 12, afterTableY);
  const statusText = record.isPaid
    ? `Status: PAID${record.paidDate ? '  on ' + fmtDate(record.paidDate) : ''}`
    : 'Status: PENDING';
  doc.setFont(font, 'bold');
  doc.text(statusText, pageW - 12, afterTableY, { align: 'right' });
  if (employee.bankAccount) {
    doc.setFont(font, 'normal');
    doc.text(`Bank A/c: ${employee.bankAccount}`, 12, afterTableY + 5);
  }

  // ── Signature block ──────────────────────────────────────────────────────
  const sigY = afterTableY + 22;
  doc.setDrawColor(150, 150, 150);
  doc.setLineWidth(0.3);
  doc.line(15, sigY, 55, sigY);
  doc.line(pageW - 55, sigY, pageW - 15, sigY);
  doc.setFont(font, 'normal');
  doc.setFontSize(7);
  doc.text('Employee Signature', 35, sigY + 4, { align: 'center' });
  doc.text('Authorized Signatory', pageW - 35, sigY + 4, { align: 'center' });

  doc.save(`SalarySlip_${employee.empNo}_${record.month}.pdf`);
}

// ── GST Summary PDF ───────────────────────────────────────────────────────────

interface GstSlabRow {
  rate: number;
  taxableAmount: number;
  cgst: number;
  sgst: number;
  igst: number;
  total: number;
  count: number;
}

interface GstTotals {
  taxable: number;
  cgst: number;
  sgst: number;
  igst: number;
  tax: number;
  grand: number;
}

interface GstSummaryPDFParams {
  society: SocietySettings;
  fromDate: string;
  toDate: string;
  outputByRate: GstSlabRow[];
  outputTotals: GstTotals;
  itcByRate: GstSlabRow[];
  itcTotals: GstTotals;
  netCgst: number;
  netSgst: number;
  netIgst: number;
  netGst: number;
  language: string;
}

export function generateGstSummaryPDF(params: GstSummaryPDFParams): void {
  const { society, fromDate, toDate, outputByRate, outputTotals, itcByRate, itcTotals, netCgst, netSgst, netIgst, netGst } = params;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const font = setupFont(doc);
  const { startY } = addHeader(doc, 'GST Summary Report', society, `Period: ${fmtDate(fromDate)} to ${fmtDate(toDate)}`);

  let y = startY + 4;

  // ── Output Tax section ───────────────────────────────────────────────────
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text('Part A — Output Tax (Sales)', 15, y);
  y += 2;

  const outRows = outputByRate.map(r => [
    `${r.rate.toFixed(1)}%`,
    String(r.count),
    fmt(r.taxableAmount),
    fmt(r.cgst),
    fmt(r.sgst),
    fmt(r.igst),
    fmt(r.total),
  ]);
  outRows.push([
    'Grand Total', String(outputByRate.reduce((s, r) => s + r.count, 0)),
    fmt(outputTotals.taxable), fmt(outputTotals.cgst), fmt(outputTotals.sgst), fmt(outputTotals.igst), fmt(outputTotals.tax),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['GST Rate', 'Bills', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Total GST']],
    body: outRows,
    styles: { fontSize: 8, font },
    headStyles: { fillColor: [34, 197, 94], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [240, 240, 240], fontStyle: 'bold' },
    columnStyles: {
      2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' },
      5: { halign: 'right' }, 6: { halign: 'right' },
    },
    didParseCell(data) {
      if (data.row.index === outRows.length - 1) {
        data.cell.styles.fillColor = [220, 252, 231];
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 8;

  // ── ITC section ──────────────────────────────────────────────────────────
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text('Part B — Input Tax Credit (Purchases)', 15, y);
  y += 2;

  const itcRows = itcByRate.map(r => [
    `${r.rate.toFixed(1)}%`,
    String(r.count),
    fmt(r.taxableAmount),
    fmt(r.cgst),
    fmt(r.sgst),
    fmt(r.igst),
    fmt(r.total),
  ]);
  itcRows.push([
    'Grand Total', String(itcByRate.reduce((s, r) => s + r.count, 0)),
    fmt(itcTotals.taxable), fmt(itcTotals.cgst), fmt(itcTotals.sgst), fmt(itcTotals.igst), fmt(itcTotals.tax),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['GST Rate', 'Bills', 'Taxable Value', 'CGST (ITC)', 'SGST (ITC)', 'IGST (ITC)', 'Total ITC']],
    body: itcRows,
    styles: { fontSize: 8, font },
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' },
      5: { halign: 'right' }, 6: { halign: 'right' },
    },
    didParseCell(data) {
      if (data.row.index === itcRows.length - 1) {
        data.cell.styles.fillColor = [219, 234, 254];
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 8;

  // ── Net GST Statement ────────────────────────────────────────────────────
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text('Part C — Net GST Liability Statement', 15, y);
  y += 2;

  const isPayable = netGst >= 0;
  const netLabel = isPayable ? 'Net GST Payable' : 'Net GST Refundable';

  autoTable(doc, {
    startY: y,
    head: [['Particulars', 'CGST (Rs.)', 'SGST (Rs.)', 'IGST (Rs.)', 'Total GST (Rs.)']],
    body: [
      ['Output Tax (GST on Sales)', fmt(outputTotals.cgst), fmt(outputTotals.sgst), fmt(outputTotals.igst), fmt(outputTotals.tax)],
      ['Less: Input Tax Credit', `(${fmt(itcTotals.cgst)})`, `(${fmt(itcTotals.sgst)})`, `(${fmt(itcTotals.igst)})`, `(${fmt(itcTotals.tax)})`],
      [netLabel, fmt(Math.abs(netCgst)), fmt(Math.abs(netSgst)), fmt(Math.abs(netIgst)), fmt(Math.abs(netGst))],
    ],
    styles: { fontSize: 8, font },
    headStyles: { fillColor: [100, 116, 139], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' },
    },
    didParseCell(data) {
      if (data.row.index === 2) {
        data.cell.styles.fillColor = isPayable ? [254, 226, 226] : [237, 233, 254];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = isPayable ? [185, 28, 28] : [109, 40, 217];
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 6;

  // Footer note
  doc.setFont(font, 'italic');
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text('Note: This report is for internal accounting purposes only. Verify with GSTN portal before filing returns.', 15, y);

  const sigY = y + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary', 'Authorized Signatory'], sigY, undefined,
    [sig.accountant, sig.secretary, sig.president]);

  addPageNumbers(doc, font, society?.name);
  const dateStr = new Date().toISOString().split('T')[0];
  doc.save(pdfFileName('GSTSummary', society, fromDate, toDate));
}


// ── Budget vs Actual PDF ─────────────────────────────────────────────────────

interface BudgetRow { name: string; budget: number; actual: number; varPct: number; status: string }

export function generateBudgetPDF(params: {
  incomeRows: BudgetRow[];
  expenseRows: BudgetRow[];
  totalBudgetIncome: number; totalActualIncome: number;
  totalBudgetExpense: number; totalActualExpense: number;
  society: SocietySettings; fy: string;
}): void {
  const { incomeRows, expenseRows, totalBudgetIncome, totalActualIncome, totalBudgetExpense, totalActualExpense, society, fy } = params;
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const { startY, font } = addHeader(doc, 'Budget vs Actual', society, `Financial Year: ${fy}`, { reportCode: 'BVA' });

  const fmtN = (n: number) => fmt(n);
  const buildBody = (rows: BudgetRow[]) =>
    rows.map(r => [r.name, fmtN(r.budget), fmtN(r.actual), `${r.varPct.toFixed(1)}%`, r.status]);

  const tableOpts = (headColor: number[], bodyData: BudgetRow[], totalBudget: number, totalActual: number, y: number) => ({
    startY: y,
    head: [['Account', 'Budget (Rs.)', 'Actual (Rs.)', 'Var %', 'Status']],
    body: buildBody(bodyData),
    foot: [['Total', fmtN(totalBudget), fmtN(totalActual), '', '']],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: headColor, textColor: 255, fontStyle: 'bold' as const },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' as const },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 1: { halign: 'right' as const }, 2: { halign: 'right' as const }, 3: { halign: 'right' as const } },
    didParseCell: rightAlignAmountColumns(1, 2, 3),
  });

  // Income section
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text('Income', 15, startY);
  autoTable(doc, tableOpts([39, 174, 96], incomeRows, totalBudgetIncome, totalActualIncome, startY + 3));

  // Expense section
  const y2 = (doc as any).lastAutoTable.finalY + 8;
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text('Expenses', 15, y2);
  autoTable(doc, tableOpts([192, 57, 43], expenseRows, totalBudgetExpense, totalActualExpense, y2 + 3));

  const sigY = (doc as any).lastAutoTable.finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary', 'Chairman'], sigY,
    'Certified that the above Budget vs Actual statement has been prepared from the Books of Account of the Society.',
    [sig.accountant, sig.secretary, sig.president]
  );

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('BudgetVsActual', society));
}


// ── Sale Register PDF ────────────────────────────────────────────────────────

export function generateSaleRegisterPDF(
  sales: { saleNo: string; date: string; customerName: string; netAmount: number; cgstAmount: number; sgstAmount: number; igstAmount: number; taxAmount: number; grandTotal: number; paymentMode: string }[],
  totals: { netAmount: number; cgst: number; sgst: number; igst: number; taxAmount: number; grandTotal: number },
  society: SocietySettings, _language: string, fromDate?: string, toDate?: string,
): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const subtitle = fromDate && toDate ? `${fmtDate(fromDate)} to ${fmtDate(toDate)}` : `FY: ${society.financialYear}`;
  const { startY, font } = addHeader(doc, 'Sale Register', society, subtitle, { reportCode: 'SR' });

  autoTable(doc, {
    startY: startY + 2,
    head: [['#', 'Invoice No', 'Date', 'Customer', 'Taxable (Rs.)', 'CGST', 'SGST', 'IGST', 'Tax Total', 'Grand Total', 'Payment']],
    body: sales.map((s, i) => [
      String(i + 1), s.saleNo, fmtDate(s.date), s.customerName,
      fmt(s.netAmount), s.cgstAmount > 0 ? fmt(s.cgstAmount) : '—', s.sgstAmount > 0 ? fmt(s.sgstAmount) : '—',
      s.igstAmount > 0 ? fmt(s.igstAmount) : '—', fmt(s.taxAmount), fmt(s.grandTotal), s.paymentMode,
    ]),
    foot: [['', '', '', 'Total', fmt(totals.netAmount), fmt(totals.cgst), fmt(totals.sgst), fmt(totals.igst), fmt(totals.taxAmount), fmt(totals.grandTotal), '']],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 4: { halign: 'right' }, 5: { halign: 'right' }, 6: { halign: 'right' }, 7: { halign: 'right' }, 8: { halign: 'right' }, 9: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(4, 5, 6, 7, 8, 9),
  });

  const sigY = (doc as any).lastAutoTable.finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], sigY, undefined, [sig.accountant, sig.secretary, sig.president]);
  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('SaleRegister', society, fromDate, toDate));
}


// ── Purchase Register PDF ────────────────────────────────────────────────────

export function generatePurchaseRegisterPDF(
  purchases: { purchaseNo: string; date: string; supplierName: string; netAmount: number; cgstAmount: number; sgstAmount: number; igstAmount: number; taxAmount: number; tdsAmount: number; grandTotal: number; paymentMode: string }[],
  totals: { netAmount: number; cgst: number; sgst: number; igst: number; taxAmount: number; tds: number; grandTotal: number },
  society: SocietySettings, _language: string, fromDate?: string, toDate?: string,
): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const subtitle = fromDate && toDate ? `${fmtDate(fromDate)} to ${fmtDate(toDate)}` : `FY: ${society.financialYear}`;
  const { startY, font } = addHeader(doc, 'Purchase Register', society, subtitle, { reportCode: 'PR' });

  autoTable(doc, {
    startY: startY + 2,
    head: [['#', 'Bill No', 'Date', 'Supplier', 'Taxable (Rs.)', 'CGST', 'SGST', 'IGST', 'Tax Total', 'TDS', 'Grand Total', 'Payment']],
    body: purchases.map((p, i) => [
      String(i + 1), p.purchaseNo, fmtDate(p.date), p.supplierName,
      fmt(p.netAmount), p.cgstAmount > 0 ? fmt(p.cgstAmount) : '—', p.sgstAmount > 0 ? fmt(p.sgstAmount) : '—',
      p.igstAmount > 0 ? fmt(p.igstAmount) : '—', fmt(p.taxAmount),
      (p.tdsAmount || 0) > 0 ? fmt(p.tdsAmount) : '—', fmt(p.grandTotal), p.paymentMode,
    ]),
    foot: [['', '', '', 'Total', fmt(totals.netAmount), fmt(totals.cgst), fmt(totals.sgst), fmt(totals.igst), fmt(totals.taxAmount), fmt(totals.tds), fmt(totals.grandTotal), '']],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [194, 65, 12], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 4: { halign: 'right' }, 5: { halign: 'right' }, 6: { halign: 'right' }, 7: { halign: 'right' }, 8: { halign: 'right' }, 9: { halign: 'right' }, 10: { halign: 'right' } },
    didParseCell: rightAlignAmountColumns(4, 5, 6, 7, 8, 9, 10),
  });

  const sigY = (doc as any).lastAutoTable.finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], sigY, undefined, [sig.accountant, sig.secretary, sig.president]);
  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('PurchaseRegister', society, fromDate, toDate));
}


// ── Closing Stock Report PDF — Category-wise grouped ────────────────────────

export interface ClosingStockItemRow {
  name: string; unit: string; stockGroup: string;
  openingQty: number; openingRate: number; openingValue: number;
  inwardQty: number; inwardRate: number; inwardValue: number;
  outwardQty: number; outwardRate: number; outwardValue: number;
  closingQty: number; closingRate: number; closingValue: number;
}

export interface ClosingStockGroupTotals {
  openingValue: number; inwardValue: number; outwardValue: number; closingValue: number;
}

export function generateClosingStockPDF(
  groups: { group: string; items: ClosingStockItemRow[]; openingValue: number; inwardValue: number; outwardValue: number; closingValue: number }[],
  grandTotals: ClosingStockGroupTotals,
  society: SocietySettings, _language: string,
): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'Closing Stock Report', society,
    `Financial Year: ${society.financialYear} | As at 31st March`,
    { reportCode: 'CSR' });

  const fQ = (n: number) => n > 0 ? n.toFixed(2) : '';
  const fV = (n: number) => n > 0 ? fmt(n) : '';

  // Build body rows: group headers (bold) + item rows (indented)
  const body: string[][] = [];
  const groupRowIndices: number[] = [];

  groups.forEach(g => {
    groupRowIndices.push(body.length);
    // Group header row — show only values, not qty/rate
    body.push([g.group, '', '', fV(g.openingValue), '', '', fV(g.inwardValue), '', '', fV(g.outwardValue), '', '', fV(g.closingValue)]);

    // Item rows
    g.items.forEach(r => {
      body.push([
        `  ${r.name}`, r.unit,
        fQ(r.openingQty), fV(r.openingValue),
        fQ(r.inwardQty), fV(r.inwardRate), fV(r.inwardValue),
        fQ(r.outwardQty), fV(r.outwardRate), fV(r.outwardValue),
        fQ(r.closingQty), fV(r.closingRate), fV(r.closingValue),
      ]);
    });
  });

  autoTable(doc, {
    startY: startY + 2,
    head: [[
      'Particulars', 'Unit',
      'Open Qty', 'Open Value',
      'Inward Qty', 'Inward Rate', 'Inward Value',
      'Outward Qty', 'Outward Rate', 'Outward Value',
      'Close Qty', 'Close Rate', 'Close Value',
    ]],
    body,
    foot: [['Grand Total', '', '', fV(grandTotals.openingValue), '', '', fV(grandTotals.inwardValue), '', '', fV(grandTotals.outwardValue), '', '', fV(grandTotals.closingValue)]],
    styles: { fontSize: 7, cellPadding: 1.5, font },
    headStyles: { fillColor: [5, 150, 105], textColor: 255, fontStyle: 'bold', fontSize: 7 },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' },
      5: { halign: 'right' }, 6: { halign: 'right' }, 7: { halign: 'right' },
      8: { halign: 'right' }, 9: { halign: 'right' }, 10: { halign: 'right' },
      11: { halign: 'right' }, 12: { halign: 'right' },
    },
    didParseCell: (data) => {
      // Right-align amount columns across head/body/foot
      if (data.column.index >= 2) data.cell.styles.halign = 'right';
      // Bold group header rows
      if (data.section === 'body' && groupRowIndices.includes(data.row.index)) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = [232, 245, 233];
      }
    },
  });

  const sigY = (doc as any).lastAutoTable.finalY + 10;
  const sig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], sigY,
    'Certified that the above Closing Stock statement is correct as per the physical verification and Books of Account.',
    [sig.accountant, sig.secretary, sig.president]);
  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('ClosingStockReport', society));
}


// ── Depreciation Schedule PDF ────────────────────────────────────────────────

interface DepCategoryRow {
  category: string;
  label: string;
  assetCount: number;
  totalCost: number;
  openingWDV: number;
  additions: number;
  depRate: string;
  method: string;
  depAmount: number;
  closingWDV: number;
}

interface DepTotals {
  totalCost: number;
  openingWDV: number;
  additions: number;
  deductions: number;
  depAmount: number;
  closingWDV: number;
}

export function generateDepreciationSchedulePDF(
  data: DepCategoryRow[],
  totals: DepTotals,
  society: SocietySettings,
  _language: string,
): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'DEPRECIATION SCHEDULE', society,
    `Financial Year: ${society.financialYear} | As per Income Tax Act / Cooperative Societies Act`,
    { reportCode: 'DEP' }
  );

  const body = data.map(r => [
    r.label,
    String(r.assetCount),
    fmt(r.openingWDV),
    r.additions > 0 ? fmt(r.additions) : '—',
    r.depRate,
    r.method,
    fmt(r.depAmount),
    fmt(r.closingWDV),
  ]);

  autoTable(doc, {
    startY: startY + 2,
    head: [['Category', 'Assets', 'Opening WDV', 'Additions', 'Dep Rate', 'Method', `Dep. (${society.financialYear})`, 'Closing WDV']],
    body,
    foot: [['Total', String(data.reduce((s, r) => s + r.assetCount, 0)),
      fmt(totals.openingWDV), fmt(totals.additions), '', '',
      fmt(totals.depAmount), fmt(totals.closingWDV),
    ]],
    styles: { fontSize: 8, cellPadding: 2.5, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: {
      1: { halign: 'center' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'center' },
      5: { halign: 'center' },
      6: { halign: 'right' },
      7: { halign: 'right' },
    },
    didParseCell: rightAlignAmountColumns(2, 3, 6, 7),
  });

  const depFinalY = (doc as any).lastAutoTable.finalY + 10;
  const depSig = getSignatoryNames(society);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary', 'Chairman'], depFinalY,
    'Certified that the above Depreciation Schedule has been prepared as per the Books of Account of the Society.',
    [depSig.accountant, depSig.secretary, depSig.president]
  );

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('DepreciationSchedule', society));
}


// ── B-2: Audit Schedules PDF ───────────────────────────────────────────────

import type { ResolvedSchedule, StateAuditFormat } from '@/lib/stateAuditFormats';

export function generateAuditSchedulesPDF(
  schedules: ResolvedSchedule[],
  society: SocietySettings,
  format: StateAuditFormat,
  _language: string,
): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const font = setupFont(doc);
  const pageW = doc.internal.pageSize.getWidth();
  let y = 16;

  const hasPY = !!(society.previousFinancialYear && society.previousYearBalances && Object.keys(society.previousYearBalances).length > 0);
  const pyYear = society.previousFinancialYear || '';

  const fmtAmt = (n: number): string => {
    if (Math.abs(n) < 0.01) return '—';
    const abs = new Intl.NumberFormat('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Math.abs(n));
    return n < 0 ? `(${abs})` : abs;
  };

  const ensureSpace = (needed = 40) => {
    if (y + needed > 270) { doc.addPage(); y = 16; }
  };

  // Cover page
  doc.setFont(font, 'bold');
  doc.setFontSize(16);
  doc.text('AUDIT SCHEDULES', pageW / 2, y, { align: 'center' }); y += 7;
  doc.setFontSize(10);
  doc.text(`[${format.actName}]`, pageW / 2, y, { align: 'center' }); y += 6;
  if (format.auditFormNumber) {
    doc.text(`Form: ${format.auditFormNumber}`, pageW / 2, y, { align: 'center' }); y += 6;
  }
  doc.setFont(font, 'normal');
  doc.setFontSize(9);
  doc.text(society.name, pageW / 2, y, { align: 'center' }); y += 5;
  doc.text(`Registration No: ${society.registrationNo || 'N/A'}`, pageW / 2, y, { align: 'center' }); y += 5;
  doc.text(`Financial Year: ${society.financialYear}`, pageW / 2, y, { align: 'center' }); y += 5;
  doc.text(`Reserve Fund: ${society.reserveFundPct ?? 25}% | Education Fund: ${format.educationFundPct}% | Coop Dev Fund: ${format.coopDevFundPct}%`, pageW / 2, y, { align: 'center' }); y += 5;
  doc.text(`Generated: ${preparedOn()}`, pageW / 2, y, { align: 'center' });
  y += 12;

  // Each schedule
  schedules.forEach(sch => {
    ensureSpace(50);

    doc.setFont(font, 'bold');
    doc.setFontSize(11);
    doc.text(sch.name, 14, y);
    y += 6;

    const head = [
      ['#', 'Particulars', ...(hasPY ? [`${pyYear} (Rs.)`] : []), `${society.financialYear} (Rs.)`],
    ];

    const body = sch.items.map((item, idx) => {
      const label = item.isTotal ? item.label : `  ${item.indent ? '    '.repeat(item.indent) : ''}${item.label}`;
      const note = item.note ? ` (${item.note})` : '';
      return [
        item.isTotal ? '' : String(idx + 1),
        `${label}${note}`,
        ...(hasPY ? [fmtAmt(item.previousYear)] : []),
        fmtAmt(item.currentYear),
      ];
    });

    autoTable(doc, {
      startY: y,
      head,
      body,
      styles: { fontSize: 8, font },
      headStyles: { fillColor: [79, 70, 229], textColor: 255 },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: hasPY ? 80 : 100 },
        ...(hasPY
          ? { 2: { halign: 'right', cellWidth: 35 }, 3: { halign: 'right', cellWidth: 35 } }
          : { 2: { halign: 'right', cellWidth: 40 } }),
      },
      didParseCell: (data) => {
        const rowIdx = data.row.index;
        const item = sch.items[rowIdx];
        if (data.section === 'body' && item) {
          if (item.isTotal) {
            data.cell.styles.fillColor = [238, 242, 255];
            data.cell.styles.fontStyle = 'bold';
          } else if (item.bold) {
            data.cell.styles.fontStyle = 'bold';
          }
        }
      },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  });

  // Signature block
  ensureSpace(40);
  y += 10;
  doc.setFont(font, 'normal');
  doc.setFontSize(9);
  const sigPositions = [14, pageW / 2 - 25, pageW - 65];
  const sigLabels = ['Accountant', 'Secretary', 'Chairman'];
  sigPositions.forEach((x, i) => {
    doc.text('_______________________', x, y);
    doc.text(sigLabels[i], x, y + 6);
  });

  addPageNumbers(doc, font, society?.name);
  doc.save(pdfFileName('AuditSchedules', society));
}
