import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { SocietySettings, AccountBalance, CashBookEntry, BankBookEntry, LedgerAccount, Member, MemberLedgerEntry, ReceiptsPaymentsData, Loan, Asset, AuditObjection, Employee, SalaryRecord } from '@/types';
import { ACCOUNT_IDS } from '@/lib/storage';
import { getVoucherLines } from '@/lib/voucherUtils';
import { fmtDate } from '@/lib/dateUtils';


const fmt = (amount: number): string =>
  'Rs. ' + new Intl.NumberFormat('en-IN', { minimumFractionDigits: 2 }).format(amount);

const preparedOn = (): string => {
  const d = new Date();
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
};

/** All PDFs use English only — helvetica font always. */
function setupFont(_doc: jsPDF): string {
  return 'helvetica';
}

/** Add page numbers + footer to every page. Call AFTER all content is added. */
function addPageNumbers(doc: jsPDF, font: string): void {
  const total = doc.getNumberOfPages();
  const pageW = doc.internal.pageSize.width;
  const pageH = doc.internal.pageSize.height;
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setFont(font, 'normal');
    doc.setTextColor(120);
    doc.text('Generated by SahakarLekha (Computer Generated Document)', 15, pageH - 6);
    doc.text(`Page ${i} of ${total}`, pageW - 15, pageH - 6, { align: 'right' });
    doc.setTextColor(0);
  }
}

/**
 * Add a 3-column signature block.
 * labels: e.g. ['Accountant', 'Secretary', 'President']
 * Returns the Y position used.
 */
function addSignatureBlock(doc: jsPDF, font: string, labels: string[], startY: number, note?: string): number {
  const pageW = doc.internal.pageSize.width;
  const pageH = doc.internal.pageSize.height;
  // If not enough space on current page, add new page
  if (startY + 30 > pageH - 20) {
    doc.addPage();
    startY = 20;
  }
  const positions = labels.map((_, i) => 15 + (i * (pageW - 30) / (labels.length - 1 || 1)));
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  if (note) {
    doc.setFontSize(7.5);
    doc.setTextColor(80);
    doc.text(note, pageW / 2, startY, { align: 'center' });
    doc.setTextColor(0);
    startY += 6;
  }
  labels.forEach((lbl, i) => {
    const x = labels.length === 1 ? pageW / 2 : positions[i];
    doc.setDrawColor(80);
    doc.setLineWidth(0.3);
    doc.line(x - 22, startY + 8, x + 22, startY + 8);
    doc.setFontSize(7.5);
    doc.text(lbl, x, startY + 13, { align: 'center' });
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text('Date: __________', x, startY + 18, { align: 'center' });
    doc.setTextColor(0);
  });
  return startY + 22;
}

/**
 * Auditor's Certificate block — per Cooperative Societies Act requirements.
 * Printed at bottom of Balance Sheet / I&E Account.
 */
function addAuditorCertificate(doc: jsPDF, font: string, society: SocietySettings, reportName: string, startY: number): void {
  const pageW = doc.internal.pageSize.width;
  const pageH = doc.internal.pageSize.height;
  if (startY + 50 > pageH - 15) {
    doc.addPage();
    startY = 15;
  }
  doc.setDrawColor(41, 82, 163);
  doc.setLineWidth(0.3);
  doc.line(15, startY, pageW - 15, startY);
  startY += 5;

  doc.setFontSize(8);
  doc.setFont(font, 'bold');
  doc.text("AUDITOR'S CERTIFICATE", pageW / 2, startY, { align: 'center' });
  startY += 5;

  doc.setFont(font, 'normal');
  doc.setFontSize(7.5);
  const certText =
    `We have examined the ${reportName} of ${society.name} (Reg. No. ${society.registrationNo}) ` +
    `for the Financial Year ${society.financialYear} and certify that the same is drawn up in accordance ` +
    `with the provisions of the Haryana Cooperative Societies Act, 1984 and the rules made thereunder ` +
    `and presents a true and fair view of the state of affairs of the Society as on 31st March.`;
  const lines = doc.splitTextToSize(certText, pageW - 30);
  doc.text(lines, 15, startY);
  startY += lines.length * 4 + 4;

  addSignatureBlock(doc, font,
    ['Statutory Auditor\n(Name & Membership No.)', 'Secretary\n(Seal)', 'President\n(Seal)'],
    startY
  );
}

/** P-1 + P-2: Updated addHeader — includes society address and Prepared on date. */
function addHeader(doc: jsPDF, title: string, society: SocietySettings, subtitle?: string): { startY: number; font: string } {
  const font = setupFont(doc);
  const pageW = doc.internal.pageSize.width;
  const cx = pageW / 2;
  const marginR = pageW - 15;

  // Society name
  doc.setFontSize(14);
  doc.setFont(font, 'bold');
  doc.text(society.name, cx, 15, { align: 'center' });

  // Reg No + FY (center) | Prepared on (right)
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.text(`Reg. No: ${society.registrationNo} | FY: ${society.financialYear}`, cx, 21, { align: 'center' });
  doc.setFontSize(7);
  doc.setTextColor(80);
  doc.text(`Prepared on: ${preparedOn()}`, marginR, 21, { align: 'right' });
  doc.setTextColor(0);

  // P-1: Address line
  const addrParts = [society.address, society.district, society.state].filter(Boolean);
  if (society.pinCode) addrParts.push(`PIN: ${society.pinCode}`);
  if (addrParts.length > 0) {
    doc.setFontSize(7.5);
    doc.setTextColor(60);
    doc.text(addrParts.join(', '), cx, 26, { align: 'center' });
    doc.setTextColor(0);
  }

  // Report title
  doc.setFontSize(13);
  doc.setFont(font, 'bold');
  doc.text(title, cx, 33, { align: 'center' });

  if (subtitle) {
    doc.setFontSize(8.5);
    doc.setFont(font, 'normal');
    doc.text(subtitle, cx, 39, { align: 'center' });
  }

  doc.setDrawColor(41, 82, 163);
  doc.setLineWidth(0.5);
  doc.line(15, 43, marginR, 43);
  return { startY: 47, font };
}

export function generateCashBookPDF(
  entries: CashBookEntry[],
  society: SocietySettings,
  openingBalance: number,
  language: 'hi' | 'en'
) {
  const doc = new jsPDF();
  const { startY, font } = addHeader(doc, 'Cash Book', society, `Financial Year: ${society.financialYear}`);

  const totalReceipts = entries.filter(e => e.type === 'receipt').reduce((s, e) => s + e.amount, 0);
  const totalPayments = entries.filter(e => e.type === 'payment').reduce((s, e) => s + e.amount, 0);
  const closingBalance = entries.length > 0 ? entries[entries.length - 1].runningBalance : openingBalance;

  const body = [
    ['', 'OB', 'Opening Balance', fmt(openingBalance), '', fmt(openingBalance)],
    ...entries.map(e => [
      fmtDate(e.date),
      e.voucherNo,
      e.particulars,
      e.type === 'receipt' ? fmt(e.amount) : '',
      e.type === 'payment' ? fmt(e.amount) : '',
      fmt(e.runningBalance),
    ]),
  ];

  autoTable(doc, {
    startY,
    head: [['Date', 'Voucher No.', 'Particulars', 'Receipt (Dr)', 'Payment (Cr)', 'Balance']],
    body,
    foot: [['', '', 'Total', fmt(totalReceipts), fmt(totalPayments), fmt(closingBalance)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
  });

  addPageNumbers(doc, font);
  doc.save(`cash-book-${society.financialYear}.pdf`);
}

export function generateBankBookPDF(
  entries: BankBookEntry[],
  society: SocietySettings,
  openingBalance: number,
  language: 'hi' | 'en'
) {
  const doc = new jsPDF();
  const { startY, font } = addHeader(doc, 'Bank Book', society, `Financial Year: ${society.financialYear}`);

  const totalDeposits = entries.filter(e => e.type === 'deposit').reduce((s, e) => s + e.amount, 0);
  const totalWithdrawals = entries.filter(e => e.type === 'withdrawal').reduce((s, e) => s + e.amount, 0);
  const closingBalance = entries.length > 0 ? entries[entries.length - 1].runningBalance : openingBalance;

  const body = [
    ['', 'OB', 'Opening Balance', fmt(openingBalance), '', fmt(openingBalance)],
    ...entries.map(e => [
      fmtDate(e.date),
      e.voucherNo,
      e.particulars,
      e.type === 'deposit' ? fmt(e.amount) : '',
      e.type === 'withdrawal' ? fmt(e.amount) : '',
      fmt(e.runningBalance),
    ]),
  ];

  autoTable(doc, {
    startY,
    head: [['Date', 'Voucher No.', 'Particulars', 'Deposit', 'Withdrawal', 'Balance']],
    body,
    foot: [['', '', 'Total', fmt(totalDeposits), fmt(totalWithdrawals), fmt(closingBalance)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
  });

  addPageNumbers(doc, font);
  doc.save(`bank-book-${society.financialYear}.pdf`);
}

export function generateTrialBalancePDF(balances: AccountBalance[], society: SocietySettings, asOnDate: string, language: 'hi' | 'en') {
  const doc = new jsPDF();
  const { startY, font } = addHeader(doc, 'Trial Balance', society, `As on: ${fmtDate(asOnDate)} | FY: ${society.financialYear}`);

  const totalDebit = balances.reduce((s, b) => s + b.totalDebit, 0);
  const totalCredit = balances.reduce((s, b) => s + b.totalCredit, 0);

  const body = balances.map((b, i) => [
    String(i + 1),
    b.account.name, // Always English in PDF
    b.account.type.charAt(0).toUpperCase() + b.account.type.slice(1),
    b.totalDebit > 0 ? fmt(b.totalDebit) : '',
    b.totalCredit > 0 ? fmt(b.totalCredit) : '',
  ]);

  autoTable(doc, {
    startY,
    head: [['#', 'Account Name', 'Type', 'Debit (Dr)', 'Credit (Cr)']],
    body,
    foot: [['', '', 'Total', fmt(totalDebit), fmt(totalCredit)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' } },
  });

  const tbFinalY = (doc as any).lastAutoTable.finalY + 10;
  const tbBalanced = Math.abs(totalDebit - totalCredit) < 1;
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.setTextColor(tbBalanced ? 22 : 220, tbBalanced ? 163 : 38, tbBalanced ? 74 : 38);
  doc.text(
    tbBalanced ? '✓ Trial Balance is Balanced — Debit total equals Credit total.' : `✗ Trial Balance is NOT balanced. Difference: ${fmt(Math.abs(totalDebit - totalCredit))}`,
    15, tbFinalY
  );
  doc.setTextColor(0);
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], tbFinalY + 6,
    'Certified that the above Trial Balance has been prepared from the Books of Account of the Society.'
  );
  addPageNumbers(doc, font);
  doc.save(`trial-balance-${society.financialYear}.pdf`);
}

export function generateIncomeExpenditurePDF(
  incomeItems: { name: string; nameHi: string; amount: number }[],
  expenseItems: { name: string; nameHi: string; amount: number }[],
  society: SocietySettings,
  language: 'hi' | 'en',
  reserveFund: number = 0
) {
  const doc = new jsPDF('landscape');
  const { startY, font } = addHeader(doc, 'Income & Expenditure Account', society, `Financial Year: ${society.financialYear}`);

  const totalIncome = incomeItems.reduce((s, i) => s + i.amount, 0);
  const totalExpenses = expenseItems.reduce((s, i) => s + i.amount, 0);
  const netProfit = totalIncome - totalExpenses;
  const isSurplus = netProfit >= 0;
  const distributableSurplus = isSurplus ? netProfit - reserveFund : 0;

  // P-4 FIX: Expenditure side total = expenses + reserve fund + surplus (must equal totalIncome for balance)
  const expSideTotal = totalExpenses + (isSurplus ? reserveFund + distributableSurplus : 0);

  const expBody: string[][] = [
    ...expenseItems.map(i => [i.name, fmt(i.amount)]),
    ...(isSurplus && reserveFund > 0 ? [[`Statutory Reserve Fund (${society.reserveFundPct ?? 25}%)`, fmt(reserveFund)]] : []),
    ...(isSurplus ? [['Surplus carried to Balance Sheet', fmt(distributableSurplus)]] : [['Deficit carried to Balance Sheet', fmt(Math.abs(netProfit))]]),
  ];
  const incBody: string[][] = incomeItems.map(i => [i.name, fmt(i.amount)]);

  // Expenditure side (left half)
  autoTable(doc, {
    startY,
    margin: { left: 15, right: 158 },
    head: [['Expenditure (Dr)', 'Amount']],
    body: expBody,
    foot: [['Total', fmt(expSideTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [220, 53, 69], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
  });

  // Income side (right half)
  autoTable(doc, {
    startY,
    margin: { left: 154, right: 15 },
    head: [['Income (Cr)', 'Amount']],
    body: incBody,
    foot: [['Total', fmt(totalIncome)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
  });

  const ieFinalY = (doc as any).lastAutoTable.finalY + 6;
  // M-2: Auditor's Certificate
  addAuditorCertificate(doc, font, society, 'Income & Expenditure Account', ieFinalY);
  addPageNumbers(doc, font);
  doc.save(`income-expenditure-${society.financialYear}.pdf`);
}

export function generateReceiptsPaymentsPDF(data: ReceiptsPaymentsData, society: SocietySettings) {
  const doc = new jsPDF('landscape');
  const { startY, font } = addHeader(doc, 'Receipts & Payments Account', society, `Financial Year: ${society.financialYear}`);

  const { openingCash, openingBank, receipts, payments, closingCash, closingBank } = data;
  const totalReceipts = receipts.reduce((s, r) => s + r.amount, 0);
  const totalPayments = payments.reduce((s, p) => s + p.amount, 0);
  const drTotal = openingCash + openingBank + totalReceipts;
  const crTotal = totalPayments + closingCash + closingBank;

  // Dr side: Opening Balance + Receipts
  const drBody: string[][] = [
    ['To Balance b/d (Opening)', ''],
    ['  Cash in Hand', fmt(openingCash)],
    ['  Cash at Bank', fmt(openingBank)],
    ...receipts.map(r => [`To ${r.accountName}`, fmt(r.amount)]),
  ];

  // Cr side: Payments + Closing Balance
  const crBody: string[][] = [
    ...payments.map(p => [`By ${p.accountName}`, fmt(p.amount)]),
    ['By Balance c/d (Closing)', ''],
    ['  Cash in Hand', fmt(closingCash)],
    ['  Cash at Bank', fmt(closingBank)],
  ];

  // Dr (Receipts) side — left half
  autoTable(doc, {
    startY,
    margin: { left: 15, right: 158 },
    head: [['Dr — Receipts', 'Amount']],
    body: drBody,
    foot: [['Total', fmt(drTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
  });

  // Cr (Payments) side — right half
  autoTable(doc, {
    startY,
    margin: { left: 154, right: 15 },
    head: [['Cr — Payments', 'Amount']],
    body: crBody,
    foot: [['Total', fmt(crTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [220, 53, 69], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
  });

  const rpFinalY = (doc as any).lastAutoTable.finalY + 8;
  addSignatureBlock(doc, font, ['Accountant', 'Secretary / Manager', 'President'], rpFinalY,
    'Certified that the above Receipts & Payments Account is correct as per the Books of Account of the Society.'
  );
  addPageNumbers(doc, font);
  doc.save(`receipts-payments-${society.financialYear}.pdf`);
}

export function generateBalanceSheetPDF(
  assetBalances: AccountBalance[],
  liabilityBalances: AccountBalance[],
  netProfit: number,
  society: SocietySettings,
  language: 'hi' | 'en',
  reserveFund: number = 0
) {
  const doc = new jsPDF('landscape');
  const { startY, font } = addHeader(doc, 'Balance Sheet', society, `As at 31st March 20${society.financialYear.split('-')[1]}`);

  const totalAssets = assetBalances.reduce((s, b) => s + b.netBalance, 0);
  // C-1 FIX: Use -netBalance (not Math.abs) so contra-equity accounts (e.g. Dividend Distribution)
  // correctly reduce the equity total instead of being added to it.
  const totalLiabilities = liabilityBalances.reduce((s, b) => s + (-b.netBalance), 0) + netProfit;
  const distributableSurplus = netProfit > 0 ? netProfit - reserveFund : 0;
  const pyBalances = society.previousYearBalances || {};
  const pyYear = society.previousFinancialYear || '';
  const hasPY = pyYear && Object.keys(pyBalances).length > 0;
  const getPY = (id: string) => pyBalances[id] ?? 0;

  const liabHead = hasPY
    ? [['Capital & Liabilities', pyYear, society.financialYear]]
    : [['Capital & Liabilities', 'Amount']];
  const assetHead = hasPY
    ? [['Assets', pyYear, society.financialYear]]
    : [['Assets', 'Amount']];

  const liabBody = [
    ...liabilityBalances
      .filter(b => b.netBalance !== 0 || getPY(b.account.id) !== 0)
      .map(b => {
        // Contra-equity (debit-nature equity, e.g. Dividend Distribution): netBalance > 0 → show in parentheses
        const isContra = b.netBalance > 0;
        const displayVal = isContra ? `(${fmt(b.netBalance)})` : fmt(Math.abs(b.netBalance));
        const label = isContra ? `${b.account.name} (Dr)` : b.account.name;
        return hasPY
          ? [label, getPY(b.account.id) ? fmt(getPY(b.account.id)) : '—', displayVal]
          : [label, displayVal];
      }),
    ...(netProfit > 0 && reserveFund > 0
      ? [hasPY ? [`Statutory Reserve Fund ${society.reserveFundPct ?? 25}%`, '—', fmt(reserveFund)] : [`Statutory Reserve Fund — ${society.reserveFundPct ?? 25}%`, fmt(reserveFund)]]
      : []),
    ...(netProfit > 0
      ? [hasPY ? ['Distributable Surplus', '—', fmt(distributableSurplus)] : ['Distributable Surplus', fmt(distributableSurplus)]]
      : []),
    ...(netProfit < 0
      ? [hasPY ? ['Deficit (Current Year)', '—', `(${fmt(Math.abs(netProfit))})`] : ['Deficit (Current Year)', `(${fmt(Math.abs(netProfit))})`]]
      : []),
  ];

  const assetBody = assetBalances
    .filter(b => b.netBalance !== 0 || getPY(b.account.id) !== 0)
    .map(b => {
      const display = b.netBalance < 0 ? `(${fmt(Math.abs(b.netBalance))})` : fmt(b.netBalance);
      return hasPY
        ? [b.netBalance < 0 ? `${b.account.name} (Cr)` : b.account.name, getPY(b.account.id) ? fmt(getPY(b.account.id)) : '—', display]
        : [b.netBalance < 0 ? `${b.account.name} (Cr)` : b.account.name, display];
    });

  const pyLiabTotal = liabilityBalances.reduce((s, b) => s + getPY(b.account.id), 0);
  const pyAssetTotal = assetBalances.reduce((s, b) => s + getPY(b.account.id), 0);

  const colStyles = hasPY
    ? { 1: { halign: 'right' as const }, 2: { halign: 'right' as const } }
    : { 1: { halign: 'right' as const } };

  // Capital & Liabilities (left half)
  autoTable(doc, {
    startY,
    margin: { left: 15, right: 158 },
    head: liabHead,
    body: liabBody,
    foot: [hasPY ? ['Total', fmt(pyLiabTotal), fmt(totalLiabilities)] : ['Total', fmt(totalLiabilities)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: colStyles,
  });

  // Assets (right half)
  autoTable(doc, {
    startY,
    margin: { left: 154, right: 15 },
    head: assetHead,
    body: assetBody,
    foot: [hasPY ? ['Total', fmt(pyAssetTotal), fmt(totalAssets)] : ['Total', fmt(totalAssets)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: colStyles,
  });

  const bsFinalY = (doc as any).lastAutoTable.finalY + 6;
  // M-1: Auditor's Certificate
  addAuditorCertificate(doc, font, society, 'Balance Sheet', bsFinalY);
  addPageNumbers(doc, font);
  doc.save(`balance-sheet-${society.financialYear}.pdf`);
}

export function generateLedgerPDF(
  entries: { date: string; voucherNo: string; particulars: string; debit: number; credit: number; balance: number; balanceType: 'Dr' | 'Cr' }[],
  account: LedgerAccount,
  society: SocietySettings,
  language: 'hi' | 'en',
  fromDate?: string,
  toDate?: string
) {
  const doc = new jsPDF();
  const subtitle = fromDate && toDate
    ? `Account: ${account.name} | ${fmtDate(fromDate)} to ${fmtDate(toDate)}`
    : `Account: ${account.name} | FY: ${society.financialYear}`;
  const { startY, font } = addHeader(doc, 'Ledger Account Statement', society, subtitle);

  const totalDebit = entries.reduce((s, e) => s + e.debit, 0);
  const totalCredit = entries.reduce((s, e) => s + e.credit, 0);
  const closing = entries[entries.length - 1];

  const body = entries.map(e => [
    fmtDate(e.date),
    e.voucherNo,
    e.particulars,
    e.debit > 0 ? fmt(e.debit) : '',
    e.credit > 0 ? fmt(e.credit) : '',
    `${fmt(e.balance)} ${e.balanceType}`,
  ]);

  autoTable(doc, {
    startY,
    head: [['Date', 'Voucher No.', 'Particulars', 'Debit (Dr)', 'Credit (Cr)', 'Balance']],
    body,
    foot: [['', '', 'Total', fmt(totalDebit), fmt(totalCredit), closing ? `${fmt(closing.balance)} ${closing.balanceType}` : '']],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
  });

  addPageNumbers(doc, font);
  doc.save(`ledger-${account.name.toLowerCase().replace(/\s+/g, '-')}-${society.financialYear}.pdf`);
}

export function generateMemberPassbookPDF(
  member: Member,
  entries: MemberLedgerEntry[],
  society: SocietySettings
) {
  const doc = new jsPDF();
  const { startY, font } = addHeader(doc, 'Member Share Ledger', society, `Member: ${member.name} | ID: ${member.memberId}`);

  // Member info box
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.text(`Father/Husband: ${member.fatherName || '-'}`, 15, startY + 2);
  doc.text(`Phone: ${member.phone}`, 15, startY + 7);
  doc.text(`Address: ${member.address || '-'}`, 15, startY + 12);
  doc.text(`Join Date: ${fmtDate(member.joinDate)}`, 120, startY + 2);
  doc.text(`Status: ${member.status.toUpperCase()}`, 120, startY + 7);

  const totalCredit = entries.reduce((s, e) => s + e.credit, 0);
  const totalDebit = entries.reduce((s, e) => s + e.debit, 0);
  const closing = entries[entries.length - 1];

  const body = entries.map(e => [
    fmtDate(e.date),
    e.voucherNo,
    e.particulars,
    e.credit > 0 ? fmt(e.credit) : '',
    e.debit > 0 ? fmt(e.debit) : '',
    fmt(e.balance),
  ]);

  autoTable(doc, {
    startY: startY + 18,
    head: [['Date', 'Voucher No.', 'Particulars', 'Credit (Cr)', 'Debit (Dr)', 'Balance']],
    body,
    foot: [['', '', 'Total', fmt(totalCredit), fmt(totalDebit), closing ? fmt(closing.balance) : '']],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 253] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
  });

  // Signature line
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(9);
  doc.text('Member Signature: ___________________', 15, finalY);
  doc.text('Secretary: ___________________', 120, finalY);

  addPageNumbers(doc, font);
  doc.save(`member-passbook-${member.memberId}-${society.financialYear}.pdf`);
}

// ─── Share Register PDF ─────────────────────────────────────────────────────
export function generateShareRegisterPDF(members: Member[], society: SocietySettings): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'SHARE REGISTER', society, `Financial Year: ${society.financialYear}`);

  const rows = members.map((m, i) => [
    String(i + 1),
    m.memberId,
    m.name,
    m.fatherName || '',
    m.joinDate,
    m.shareCertNo || '',
    m.shareCount != null ? String(m.shareCount) : '',
    m.shareFaceValue != null ? fmt(m.shareFaceValue) : '',
    fmt(m.shareCapital),
    m.nomineeName || '',
    m.nomineeRelation || '',
    m.status === 'active' ? 'Active' : 'Inactive',
  ]);

  autoTable(doc, {
    startY: startY + 2,
    head: [['S.No', 'Member ID', 'Name', 'Father/Husband', 'Join Date', 'Cert. No.', 'Shares', 'Face Val.', 'Total Capital', 'Nominee', 'Relation', 'Status']],
    body: rows,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 8: { halign: 'right' } },
  });

  const srSummaryY = (doc as any).lastAutoTable.finalY + 8;
  const totalCap = members.reduce((s, m) => s + m.shareCapital, 0);
  doc.setFontSize(9);
  doc.setFont(font, 'bold');
  doc.text(`Total Members: ${members.length}   |   Total Share Capital: ${fmt(totalCap)}`, 15, srSummaryY);

  // M-5: Secretary certification
  const srCertY = srSummaryY + 8;
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.setTextColor(60);
  const certLine = 'Certified that the above is a true and correct Register of Members and Share Capital of the Society as maintained in the books.';
  doc.text(certLine, 15, srCertY);
  doc.setTextColor(0);
  addSignatureBlock(doc, font, ['Secretary / Manager\n(with Seal)', 'President\n(with Seal)'], srCertY + 8);
  addPageNumbers(doc, font);
  doc.save(`share-register-${society.financialYear}.pdf`);
}

// ─── Loan Register PDF ────────────────────────────────────────────────────────
export function generateLoanRegisterPDF(loans: Loan[], members: Member[], society: SocietySettings): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'LOAN REGISTER', society, `Financial Year: ${society.financialYear}`);

  const getMemberName = (id: string) => members.find(m => m.id === id)?.name || id;
  const loanTypeLabel = (t: string) => t === 'short-term' ? 'S/T' : t === 'medium-term' ? 'M/T' : 'L/T';

  const rows = loans.map(l => [
    l.loanNo,
    getMemberName(l.memberId),
    loanTypeLabel(l.loanType),
    l.purpose || '',
    fmt(l.amount),
    `${l.interestRate}%`,
    fmtDate(l.disbursementDate),
    fmtDate(l.dueDate),
    fmt(l.repaidAmount),
    fmt(l.amount - l.repaidAmount),
    l.status.toUpperCase(),
  ]);

  autoTable(doc, {
    startY: startY + 2,
    head: [['Loan No.', 'Member', 'Type', 'Purpose', 'Amount', 'Rate', 'Disbursed', 'Due Date', 'Repaid', 'Outstanding', 'Status']],
    body: rows,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 4: { halign: 'right' }, 8: { halign: 'right' }, 9: { halign: 'right' } },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const totalDisbursed = loans.reduce((s, l) => s + l.amount, 0);
  const totalOutstanding = loans.filter(l => l.status !== 'cleared').reduce((s, l) => s + (l.amount - l.repaidAmount), 0);
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text(`Total Loans: ${loans.length}   |   Total Disbursed: ${fmt(totalDisbursed)}   |   Outstanding: ${fmt(totalOutstanding)}`, 15, finalY);

  addPageNumbers(doc, font);
  doc.save(`loan-register-${society.financialYear}.pdf`);
}

// ─── Asset Register PDF ────────────────────────────────────────────────────────
export function generateAssetRegisterPDF(assets: Asset[], society: SocietySettings): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'ASSET REGISTER', society, `As on: ${new Date().toLocaleDateString('en-IN')} | Depreciation Method: SLM`);

  const calcBookValue = (a: Asset): number => {
    if (!a.purchaseDate || !a.depreciationRate) return a.cost;
    const now = new Date();
    const yearEnd = now.getMonth() >= 3 ? new Date(now.getFullYear(), 2, 31) : new Date(now.getFullYear() - 1, 2, 31);
    const yearsElapsed = Math.max(0, (yearEnd.getTime() - new Date(a.purchaseDate).getTime()) / (365.25 * 24 * 3600 * 1000));
    return Math.max(0, a.cost - a.cost * (a.depreciationRate / 100) * yearsElapsed);
  };

  const rows = assets.map((a, i) => {
    const bookVal = calcBookValue(a);
    return [
      String(i + 1),
      a.assetNo,
      a.name,
      a.category,
      a.location || '',
      fmtDate(a.purchaseDate),
      fmt(a.cost),
      `${a.depreciationRate}%`,
      fmt(a.cost - bookVal),
      fmt(bookVal),
      a.status === 'active' ? 'Active' : 'Disposed',
    ];
  });

  autoTable(doc, {
    startY: startY + 2,
    head: [['S.No', 'Asset No.', 'Asset Name', 'Category', 'Location', 'Purchase Date', 'Cost', 'Dep%', 'Acc. Dep.', 'Book Value', 'Status']],
    body: rows,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 6: { halign: 'right' }, 8: { halign: 'right' }, 9: { halign: 'right' } },
    foot: [[
      '', '', '', '', '', 'Total',
      fmt(assets.reduce((s, a) => s + a.cost, 0)),
      '',
      fmt(assets.reduce((s, a) => s + (a.cost - calcBookValue(a)), 0)),
      fmt(assets.reduce((s, a) => s + calcBookValue(a), 0)),
      '',
    ]],
    footStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
  });

  addPageNumbers(doc, font);
  doc.save(`asset-register-${new Date().getFullYear()}.pdf`);
}

// ─── Audit Rectification Register PDF ─────────────────────────────────────────
export function generateAuditRegisterPDF(objections: AuditObjection[], society: SocietySettings): void {
  const doc = new jsPDF({ orientation: 'landscape' });
  const { startY, font } = addHeader(doc, 'AUDIT RECTIFICATION REGISTER', society, `Prepared on: ${new Date().toLocaleDateString('en-IN')}`);

  const statusLabel = (s: string) => s === 'rectified' ? 'Rectified' : s === 'partial' ? 'Partial' : 'Pending';

  const rows = objections.map(o => [
    o.objectionNo,
    o.auditYear,
    o.paraNo,
    o.category.toUpperCase(),
    o.objection.length > 60 ? o.objection.substring(0, 60) + '...' : o.objection,
    o.amountInvolved > 0 ? fmt(o.amountInvolved) : '—',
    o.dueDate ? fmtDate(o.dueDate) : '—',
    o.actionTaken ? (o.actionTaken.length > 40 ? o.actionTaken.substring(0, 40) + '...' : o.actionTaken) : '—',
    o.rectifiedDate ? fmtDate(o.rectifiedDate) : '—',
    statusLabel(o.status),
  ]);

  autoTable(doc, {
    startY: startY + 2,
    head: [['Objn. No.', 'Audit Year', 'Para', 'Category', 'Objection', 'Amount', 'Due Date', 'Action Taken', 'Rect. Date', 'Status']],
    body: rows,
    styles: { fontSize: 7.5 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      4: { cellWidth: 55 },
      7: { cellWidth: 45 },
      5: { halign: 'right' },
    },
    didDrawCell: (data) => {
      // Color status column
      if (data.section === 'body' && data.column.index === 9) {
        const val = data.cell.raw as string;
        if (val === 'Rectified') { doc.setTextColor(22, 163, 74); }
        else if (val === 'Partial') { doc.setTextColor(217, 119, 6); }
        else { doc.setTextColor(220, 38, 38); }
      }
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const pending = objections.filter(o => o.status === 'pending').length;
  const rectified = objections.filter(o => o.status === 'rectified').length;
  const totalAmt = objections.reduce((s, o) => s + o.amountInvolved, 0);
  doc.setFontSize(9);
  doc.setFont(font, 'normal');
  doc.text(`Total: ${objections.length} | Pending: ${pending} | Rectified: ${rectified} | Total Amount Involved: ${fmt(totalAmt)}`, 15, finalY);

  const sigY = finalY + 15;
  doc.text('Secretary: ___________________', 15, sigY);
  doc.text('Auditor: ___________________', 120, sigY);
  doc.text('President: ___________________', 225, sigY);

  addPageNumbers(doc, font);
  doc.save(`audit-register-${society.financialYear}.pdf`);
}

export function generateDayBookPDF(
  entries: { id: string; date: string; voucherNo: string; type: string; debitAccountId: string; creditAccountId: string; amount: number; narration?: string }[],
  accounts: LedgerAccount[],
  society: SocietySettings,
  fromDate: string,
  toDate: string,
  language: 'hi' | 'en'
) {
  const doc = new jsPDF({ orientation: 'landscape' });
  const getAccName = (id: string) => accounts.find(a => a.id === id)?.name || id;
  const typeLabel = (t: string) => t === 'receipt' ? 'Receipt' : t === 'payment' ? 'Payment' : 'Journal';

  const subtitle = `${fmtDate(fromDate)} to ${fmtDate(toDate)} | FY: ${society.financialYear}`;
  const { startY, font } = addHeader(doc, 'Day Book', society, subtitle);

  // Group by date
  const groups: { date: string; items: typeof entries }[] = [];
  entries.forEach(v => {
    const last = groups[groups.length - 1];
    if (last && last.date === v.date) last.items.push(v);
    else groups.push({ date: v.date, items: [v] });
  });

  // Running cash only (Day Book = cash based)
  const cashAccOB = accounts.find(a => a.id === ACCOUNT_IDS.CASH)?.openingBalance || 0;
  // C-2 FIX: Use getVoucherLines() to correctly calculate pre-period cash balance
  // including multi-line Expert Mode vouchers.
  const firstDate = entries.length > 0 ? entries[0].date : null;
  let runCash = cashAccOB;
  if (firstDate) {
    entries.forEach(v => {
      if (v.date >= firstDate) return;
      getVoucherLines(v).forEach(l => {
        if (l.accountId === ACCOUNT_IDS.CASH)
          runCash += l.type === 'Dr' ? l.amount : -l.amount;
      });
    });
  }

  // Columns: Date/Voucher | Particulars | Debit (Rs.) | Credit (Rs.)
  // Each voucher = 2 rows: Dr row + Cr row
  const body: (string[])[] = [];
  const dayHeaderRows: number[] = [];
  const openingBalRows: number[] = [];
  const dayTotalRows: number[] = [];
  const closingBalRows: number[] = [];
  const drRows: number[] = [];
  const crRows: number[] = [];

  groups.forEach(group => {
    const dayDate = fmtDate(group.date);
    const dayTotal = group.items.reduce((s, v) => s + v.amount, 0);
    const dayReceipts = group.items.filter(v => v.type === 'receipt').reduce((s, v) => s + v.amount, 0);
    const dayPayments = group.items.filter(v => v.type === 'payment').reduce((s, v) => s + v.amount, 0);

    // Day header row (spans all 4 cols)
    dayHeaderRows.push(body.length);
    body.push([
      `${dayDate}`,
      `${group.items.length} transaction(s)   Rcpt: ${fmt(dayReceipts)}   Pmnt: ${fmt(dayPayments)}`,
      '',
      `Total: ${fmt(dayTotal)}`,
    ]);

    // Opening balance row
    openingBalRows.push(body.length);
    body.push(['Opening Balance', `Cash in Hand (Opening): ${fmt(runCash)}`, fmt(runCash), '']);

    // C-2 FIX: Use getVoucherLines() for correct Dr/Cr display in multi-line vouchers.
    group.items.forEach((v, i) => {
      const vLines = getVoucherLines(v);
      const narration = v.narration ? `  (${v.narration})` : '';
      const voucherMeta = `${fmtDate(v.date)}\n${typeLabel(v.type)}\n#${i + 1} ${v.voucherNo}`;

      vLines.forEach((l, li) => {
        const label = l.type === 'Dr'
          ? `${getAccName(l.accountId)}  Dr.`
          : `    To ${getAccName(l.accountId)}  Cr.${li === vLines.length - 1 ? narration : ''}`;
        if (l.type === 'Dr') {
          drRows.push(body.length);
          body.push([li === 0 ? voucherMeta : '', label, fmt(l.amount), '']);
        } else {
          crRows.push(body.length);
          body.push(['', label, '', fmt(l.amount)]);
        }
      });
    });

    // Day total row
    dayTotalRows.push(body.length);
    body.push(['Day Total', `${dayDate}`, fmt(dayTotal), fmt(dayTotal)]);

    // C-2 FIX: Update running cash using getVoucherLines() for multi-line voucher support.
    group.items.forEach(v => {
      getVoucherLines(v).forEach(l => {
        if (l.accountId === ACCOUNT_IDS.CASH)
          runCash += l.type === 'Dr' ? l.amount : -l.amount;
      });
    });

    // Closing balance row
    closingBalRows.push(body.length);
    body.push(['Closing Balance', `Cash in Hand (Closing): ${fmt(runCash)}`, fmt(runCash), '']);
  });

  const grandTotal = entries.reduce((s, v) => s + v.amount, 0);

  autoTable(doc, {
    startY,
    head: [['Date / Voucher', 'Particulars', 'Debit (Rs.)', 'Credit (Rs.)']],
    body,
    foot: [['', 'GRAND TOTAL', fmt(grandTotal), fmt(grandTotal)]],
    styles: { fontSize: 8, cellPadding: 2.5 },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold', fontSize: 9 },
    footStyles: { fillColor: [220, 230, 255], fontStyle: 'bold', textColor: 20, fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 42 },
      1: { cellWidth: 145 },
      2: { cellWidth: 40, halign: 'right' },
      3: { cellWidth: 40, halign: 'right' },
    },
    didParseCell: (data) => {
      if (data.section !== 'body') return;
      const rowIdx = data.row.index;
      if (dayHeaderRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [41, 82, 163];
        data.cell.styles.textColor = [255, 255, 255];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fontSize = 8.5;
      } else if (openingBalRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [255, 248, 220];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = [120, 80, 0];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      } else if (drRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [240, 245, 255];
        data.cell.styles.textColor = [30, 50, 150];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      } else if (crRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [245, 255, 245];
        data.cell.styles.textColor = [20, 100, 40];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      } else if (dayTotalRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [230, 236, 255];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = [30, 30, 150];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      } else if (closingBalRows.includes(rowIdx)) {
        data.cell.styles.fillColor = [225, 245, 225];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = [20, 100, 20];
        if (data.column.index >= 2) data.cell.styles.halign = 'right';
      }
    },
  });

  addPageNumbers(doc, font);
  doc.save(`day-book-${society.financialYear}.pdf`);
}

export function generateTradingAccountPDF(
  data: {
    salesItems:        { name: string; amount: number }[];
    closingStockItems: { name: string; amount: number }[];
    openingStockItems: { name: string; amount: number }[];
    purchaseItems:     { name: string; amount: number }[];
    directExpItems:    { name: string; amount: number }[];
    totalSales: number; totalClosingStock: number;
    totalOpeningStock: number; totalPurchases: number; totalDirectExp: number;
    grossProfit: number;
  },
  society: SocietySettings
) {
  const doc = new jsPDF('landscape');
  const { startY, font } = addHeader(doc, 'Trading Account', society, `Financial Year: ${society.financialYear}`);

  const isProfit  = data.grossProfit >= 0;
  const grandTotal = Math.abs(data.grossProfit) +
    (isProfit
      ? data.totalOpeningStock + data.totalPurchases + data.totalDirectExp
      : data.totalSales + data.totalClosingStock);

  // ── Dr side (left) ────────────────────────────────────────────────────────
  const drBody: (string | { content: string; styles: object })[][] = [];

  if (data.openingStockItems.length > 0) {
    drBody.push([{ content: 'Opening Stock', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.openingStockItems.forEach(i => drBody.push([`  ${i.name}`, fmt(i.amount)]));
    drBody.push([{ content: 'Total Opening Stock', styles: { fontStyle: 'bold' } }, fmt(data.totalOpeningStock)]);
  }

  if (data.purchaseItems.length > 0) {
    drBody.push([{ content: 'Purchases', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.purchaseItems.forEach(i => drBody.push([`  ${i.name}`, fmt(i.amount)]));
  }

  if (data.directExpItems.length > 0) {
    drBody.push([{ content: 'Direct Expenses', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.directExpItems.forEach(i => drBody.push([`  ${i.name}`, fmt(i.amount)]));
  }

  if (isProfit && data.grossProfit > 0) {
    drBody.push([{ content: 'Gross Profit (to I&E Account)', styles: { fontStyle: 'bold', textColor: [25, 135, 84] } }, fmt(data.grossProfit)]);
  }

  // ── Cr side (right) ───────────────────────────────────────────────────────
  const crBody: (string | { content: string; styles: object })[][] = [];

  if (data.salesItems.length > 0) {
    crBody.push([{ content: 'Sales (Trading Income)', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.salesItems.forEach(i => crBody.push([`  ${i.name}`, fmt(i.amount)]));
    crBody.push([{ content: 'Total Sales', styles: { fontStyle: 'bold' } }, fmt(data.totalSales)]);
  }

  if (data.closingStockItems.length > 0) {
    crBody.push([{ content: 'Closing Stock', styles: { fontStyle: 'bold', fillColor: [245, 245, 245] } }, '']);
    data.closingStockItems.forEach(i => crBody.push([`  ${i.name}`, fmt(i.amount)]));
    crBody.push([{ content: 'Total Closing Stock', styles: { fontStyle: 'bold' } }, fmt(data.totalClosingStock)]);
  }

  if (!isProfit) {
    crBody.push([{ content: 'Gross Loss (to I&E Account)', styles: { fontStyle: 'bold', textColor: [220, 53, 69] } }, fmt(Math.abs(data.grossProfit))]);
  }

  // Render Dr table (left half)
  autoTable(doc, {
    startY,
    margin: { left: 15, right: 155 },
    head: [['Debit (Dr)', 'Amount']],
    body: drBody.length > 0 ? drBody : [['No entries', '']],
    foot: [['Grand Total', fmt(grandTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [220, 53, 69], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right', cellWidth: 30 } },
  });

  // Render Cr table (right half)
  autoTable(doc, {
    startY,
    margin: { left: 151, right: 15 },
    head: [['Credit (Cr)', 'Amount']],
    body: crBody.length > 0 ? crBody : [['No entries', '']],
    foot: [['Grand Total', fmt(grandTotal)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [25, 135, 84], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right', cellWidth: 30 } },
  });

  // Signature row
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  const pageW  = doc.internal.pageSize.width;
  const labels = ['Accountant', 'Secretary', 'Chairman'];
  const sigXs  = [pageW * 0.2, pageW * 0.5, pageW * 0.8];
  doc.setFontSize(9);
  doc.setFont(font, 'normal');
  labels.forEach((lbl, i) => {
    doc.line(sigXs[i] - 25, finalY, sigXs[i] + 25, finalY);
    doc.text(lbl, sigXs[i], finalY + 5, { align: 'center' });
  });

  addPageNumbers(doc, font);
  doc.save(`trading-account-${society.financialYear}.pdf`);
}

export function generateSalarySlipPDF(
  record: SalaryRecord,
  employee: Employee,
  society: SocietySettings
): void {
  const doc = new jsPDF({ orientation: 'portrait', format: 'a5' });
  const font = setupFont(doc);
  const pageW = doc.internal.pageSize.width;
  const cx = pageW / 2;

  // ── Header ──────────────────────────────────────────────────────────────
  doc.setFontSize(13);
  doc.setFont(font, 'bold');
  doc.text(society.name, cx, 14, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.text(`Reg. No: ${society.registrationNo}  |  ${society.address}`, cx, 20, { align: 'center' });
  doc.setFontSize(11);
  doc.setFont(font, 'bold');
  doc.text('SALARY SLIP', cx, 28, { align: 'center' });
  doc.setDrawColor(41, 82, 163);
  doc.setLineWidth(0.5);
  doc.line(10, 31, pageW - 10, 31);

  // ── Slip meta ────────────────────────────────────────────────────────────
  const [yr, mo] = record.month.split('-');
  const monthName = new Date(Number(yr), Number(mo) - 1, 1)
    .toLocaleString('en-IN', { month: 'long', year: 'numeric' });

  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  doc.text(`Slip No: ${record.slipNo}`, 12, 37);
  doc.text(`Month: ${monthName}`, cx, 37, { align: 'center' });
  doc.text(`Date: ${record.isPaid && record.paidDate ? fmtDate(record.paidDate) : fmtDate(record.createdAt)}`, pageW - 12, 37, { align: 'right' });

  // ── Employee details box ─────────────────────────────────────────────────
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.rect(10, 40, pageW - 20, 22);

  doc.setFont(font, 'bold');
  doc.setFontSize(8);
  doc.text('Employee Details', 13, 46);
  doc.setFont(font, 'normal');
  doc.text(`Emp No : ${employee.empNo}`, 13, 52);
  doc.text(`Name   : ${employee.name}`, 13, 57);
  doc.text(`Designation: ${employee.designation}`, cx + 5, 52);
  doc.text(`Join Date  : ${fmtDate(employee.joinDate)}`, cx + 5, 57);

  // ── Earnings & Deductions table ──────────────────────────────────────────
  autoTable(doc, {
    startY: 66,
    head: [['Earnings', 'Amount (Rs.)', 'Deductions', 'Amount (Rs.)']],
    body: [
      ['Basic Salary',   fmt(record.basicSalary), 'Deductions', fmt(record.deductions)],
      ['Allowances',     fmt(record.allowances),  '',           ''],
      ['Gross Salary',   fmt(record.basicSalary + record.allowances), '', ''],
    ],
    foot: [['Net Salary Payable', '', '', fmt(record.netSalary)]],
    styles: { fontSize: 8, cellPadding: 2, font },
    headStyles: { fillColor: [41, 82, 163], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    footStyles: { fillColor: [240, 248, 240], textColor: [0, 100, 0], fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' }, 3: { halign: 'right' } },
  });

  // ── Payment info ─────────────────────────────────────────────────────────
  const afterTableY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;
  doc.setFontSize(8);
  doc.setFont(font, 'normal');
  const payMode = { cash: 'Cash', bank: 'Bank Transfer', credit: 'Credit' }[record.paymentMode] ?? record.paymentMode;
  doc.text(`Payment Mode: ${payMode}`, 12, afterTableY);
  const statusText = record.isPaid
    ? `Status: PAID${record.paidDate ? '  on ' + fmtDate(record.paidDate) : ''}`
    : 'Status: PENDING';
  doc.setFont(font, 'bold');
  doc.text(statusText, pageW - 12, afterTableY, { align: 'right' });
  if (employee.bankAccount) {
    doc.setFont(font, 'normal');
    doc.text(`Bank A/c: ${employee.bankAccount}`, 12, afterTableY + 5);
  }

  // ── Signature block ──────────────────────────────────────────────────────
  const sigY = afterTableY + 22;
  doc.setDrawColor(150, 150, 150);
  doc.setLineWidth(0.3);
  doc.line(15, sigY, 55, sigY);
  doc.line(pageW - 55, sigY, pageW - 15, sigY);
  doc.setFont(font, 'normal');
  doc.setFontSize(7);
  doc.text('Employee Signature', 35, sigY + 4, { align: 'center' });
  doc.text('Authorized Signatory', pageW - 35, sigY + 4, { align: 'center' });

  doc.save(`salary-slip-${employee.empNo}-${record.month}.pdf`);
}

// ── GST Summary PDF ───────────────────────────────────────────────────────────

interface GstSlabRow {
  rate: number;
  taxableAmount: number;
  cgst: number;
  sgst: number;
  igst: number;
  total: number;
  count: number;
}

interface GstTotals {
  taxable: number;
  cgst: number;
  sgst: number;
  igst: number;
  tax: number;
  grand: number;
}

interface GstSummaryPDFParams {
  society: SocietySettings;
  fromDate: string;
  toDate: string;
  outputByRate: GstSlabRow[];
  outputTotals: GstTotals;
  itcByRate: GstSlabRow[];
  itcTotals: GstTotals;
  netCgst: number;
  netSgst: number;
  netIgst: number;
  netGst: number;
  language: string;
}

export function generateGstSummaryPDF(params: GstSummaryPDFParams): void {
  const { society, fromDate, toDate, outputByRate, outputTotals, itcByRate, itcTotals, netCgst, netSgst, netIgst, netGst } = params;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const font = setupFont(doc);
  const { startY } = addHeader(doc, 'GST Summary Report', society, `Period: ${fmtDate(fromDate)} to ${fmtDate(toDate)}`);

  let y = startY + 4;

  // ── Output Tax section ───────────────────────────────────────────────────
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text('Part A — Output Tax (Sales)', 15, y);
  y += 2;

  const outRows = outputByRate.map(r => [
    `${r.rate.toFixed(1)}%`,
    String(r.count),
    fmt(r.taxableAmount),
    fmt(r.cgst),
    fmt(r.sgst),
    fmt(r.igst),
    fmt(r.total),
  ]);
  outRows.push([
    'Grand Total', String(outputByRate.reduce((s, r) => s + r.count, 0)),
    fmt(outputTotals.taxable), fmt(outputTotals.cgst), fmt(outputTotals.sgst), fmt(outputTotals.igst), fmt(outputTotals.tax),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['GST Rate', 'Bills', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Total GST']],
    body: outRows,
    styles: { fontSize: 8, font },
    headStyles: { fillColor: [34, 197, 94], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [240, 240, 240], fontStyle: 'bold' },
    columnStyles: {
      2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' },
      5: { halign: 'right' }, 6: { halign: 'right' },
    },
    didParseCell(data) {
      if (data.row.index === outRows.length - 1) {
        data.cell.styles.fillColor = [220, 252, 231];
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 8;

  // ── ITC section ──────────────────────────────────────────────────────────
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text('Part B — Input Tax Credit (Purchases)', 15, y);
  y += 2;

  const itcRows = itcByRate.map(r => [
    `${r.rate.toFixed(1)}%`,
    String(r.count),
    fmt(r.taxableAmount),
    fmt(r.cgst),
    fmt(r.sgst),
    fmt(r.igst),
    fmt(r.total),
  ]);
  itcRows.push([
    'Grand Total', String(itcByRate.reduce((s, r) => s + r.count, 0)),
    fmt(itcTotals.taxable), fmt(itcTotals.cgst), fmt(itcTotals.sgst), fmt(itcTotals.igst), fmt(itcTotals.tax),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['GST Rate', 'Bills', 'Taxable Value', 'CGST (ITC)', 'SGST (ITC)', 'IGST (ITC)', 'Total ITC']],
    body: itcRows,
    styles: { fontSize: 8, font },
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' },
      5: { halign: 'right' }, 6: { halign: 'right' },
    },
    didParseCell(data) {
      if (data.row.index === itcRows.length - 1) {
        data.cell.styles.fillColor = [219, 234, 254];
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 8;

  // ── Net GST Statement ────────────────────────────────────────────────────
  doc.setFontSize(10);
  doc.setFont(font, 'bold');
  doc.text('Part C — Net GST Liability Statement', 15, y);
  y += 2;

  const isPayable = netGst >= 0;
  const netLabel = isPayable ? 'Net GST Payable' : 'Net GST Refundable';

  autoTable(doc, {
    startY: y,
    head: [['Particulars', 'CGST (Rs.)', 'SGST (Rs.)', 'IGST (Rs.)', 'Total GST (Rs.)']],
    body: [
      ['Output Tax (GST on Sales)', fmt(outputTotals.cgst), fmt(outputTotals.sgst), fmt(outputTotals.igst), fmt(outputTotals.tax)],
      ['Less: Input Tax Credit', `(${fmt(itcTotals.cgst)})`, `(${fmt(itcTotals.sgst)})`, `(${fmt(itcTotals.igst)})`, `(${fmt(itcTotals.tax)})`],
      [netLabel, fmt(Math.abs(netCgst)), fmt(Math.abs(netSgst)), fmt(Math.abs(netIgst)), fmt(Math.abs(netGst))],
    ],
    styles: { fontSize: 8, font },
    headStyles: { fillColor: [100, 116, 139], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' },
    },
    didParseCell(data) {
      if (data.row.index === 2) {
        data.cell.styles.fillColor = isPayable ? [254, 226, 226] : [237, 233, 254];
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = isPayable ? [185, 28, 28] : [109, 40, 217];
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 6;

  // Footer note
  doc.setFont(font, 'italic');
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text('Note: This report is for internal accounting purposes only. Verify with GSTN portal before filing returns.', 15, y);

  const dateStr = new Date().toISOString().split('T')[0];
  doc.save(`gst-summary-${fromDate}-to-${toDate}-${dateStr}.pdf`);
}
