/**
 * Bundle entry for the CAIOS ask-core (Slice 1).
 *
 * Re-exports the EXACT src/ modules so the Edge Function runs the same mechanism, the
 * same ranker and the same corpus the browser does. It is NOT a second implementation:
 * esbuild bundles the real modules into one Deno-friendly ESM file (ask-core.mjs).
 * A server-side copy of the scorer would drift, and the day it drifted the assistant
 * and the search box would disagree in front of a user — RULE 2's failure mode, which
 * this reuse exists to prevent.
 *
 * The corpus JSON is bundled in by esbuild, so the function carries its own knowledge
 * and needs no database read to answer a K-lane question.
 *
 * Regenerate after any change to ask/, search/, ai/ or the corpus:
 *   npm run build:search-index && npm run build:ask-core
 */
export { ask, ASK_FEATURE } from '../../../src/lib/ask/core';
export type { AskRequest, AskAnswer, Citation, Channel, Lane, Intent } from '../../../src/lib/ask/core';
export { classify } from '../../../src/lib/ask/classify';
// Tier 0 — the F-lane's rule catalog and the deterministic calculator. The LLM never
// computes money (AI-P3), so the figure has to come from here, on the server too.
export { answerFact, unverifiedHint } from '../../../src/lib/ask/fact';
export { TDS_RULES, resolveTaxRule, verifiedValue } from '../../../src/lib/rules/tax';
export { computeTds, isRefusal } from '../../../src/lib/tax/computeTds';
export { resolveAiFlags, AI_OFF } from '../../../src/lib/ai/flags';
export { isAiEnabled } from '../../../src/lib/ai/killSwitch';
export type { AiFlags } from '../../../src/lib/ai/killSwitch';
// T-01: the ONE jurisdiction normalisation ('HR' / 'Haryana' / 'हरियाणा' → 'hr'),
// never re-invented server-side.
export { resolveJurisdiction } from '../../../src/lib/jurisdiction';
export type { SearchDoc } from '../../../src/lib/search/rank';

// The frozen corpus, generated by the REAL buildIndex() (scripts/build-search-index.mjs).
import INDEX from '../../../src/generated/search-index.json';
export const CORPUS = INDEX.docs as unknown as import('../../../src/lib/search/rank').SearchDoc[];
