/**
 * Restore dependency resolver (T-30 / gap EXP-03).
 *
 * PURE. No Supabase, no DOM, no network, no clock. It takes the registry and returns the
 * order in which rows may be inserted, plus an account of everything it refused to insert
 * and why. Every later restore stage (diff, commit, replay) reads its plan from here.
 *
 * ─────────────────────────────────────────────────────────────────────────────────────
 * WHY ORDER IS A CORRECTNESS PROPERTY, NOT A PERFORMANCE ONE
 *
 * A voucher references a member; a loan repayment references a loan. Insert the child
 * first and either the foreign key rejects it, or — worse, and this is the real risk in
 * this schema — there is no foreign key, the row lands, and it points at nothing. The
 * restore reports success and the books are quietly wrong. Dependency-first insertion is
 * what makes "restored" mean the same thing as "correct".
 *
 * THE FOUR CUSTODY POLICIES, AND WHAT RESTORE DOES WITH EACH
 *
 *   full     (84)  inserted, in this order.
 *   replay   (1)   NEVER inserted. `voucher_entry` is what the posting engine PRODUCES
 *                  from a voucher. Re-inserting it would import last year's arithmetic
 *                  instead of recomputing it, and a posting-rule fix would never reach
 *                  restored data. T-33 regenerates these and asserts they match.
 *   sidecar  (2)   NEVER inserted. `audit_log` is WORM — writing to it would forge the
 *                  non-repudiable trail. `guide_certificate` is evidence someone else
 *                  signed. Both travel in the archive so they can be READ, not replanted.
 *   exclude  (6)   never left the society in the first place.
 *
 * Global-scope entities (shared reference data) are also never restored: they belong to
 * the platform, not to the society whose archive this is.
 * ─────────────────────────────────────────────────────────────────────────────────────
 */
import type { EntityDescriptor, ExportRegistry } from '../export/registry.types';
import { findCycle, topoOrder } from '../export/registry.types';

/**
 * Keys that a restore must NEVER insert, named explicitly rather than derived from
 * `backupPolicy`.
 *
 * A derived guard — "exclude everything whose policy is replay or sidecar" — is worthless
 * precisely when it matters. Flip `voucher_entry` to `'full'` by accident and the derived
 * set becomes empty, the guard finds nothing to exclude, and it passes. The check would
 * disappear at the exact moment it was needed.
 *
 * So the list is independent, and `assertNeverInserted` checks BOTH directions: nothing
 * here may be inserted, and nothing here may have quietly become insertable.
 */
export const NEVER_INSERT_KEYS: readonly string[] = Object.freeze([
  'voucher_entry',      // replay  — regenerated by the posting engine (T-33)
  'audit_log',          // sidecar — WORM; insertion would forge the audit trail
  'guide_certificate',  // sidecar — third-party evidence, not our row to write
]);

/** Why a given entity is not in the insert plan. */
export type SkipReason = 'replay' | 'sidecar' | 'exclude' | 'global-scope';

export interface SkippedEntity {
  key: string;
  reason: SkipReason;
  /** One line, for the operator. Not for the log. */
  explanation: string;
}

export interface RestorePlan {
  /** Entities to insert, dependencies strictly before dependents. */
  insert: EntityDescriptor[];
  /** Reverse of `insert`. Replace-mode teardown must delete children before parents. */
  teardown: EntityDescriptor[];
  /** Everything not inserted, and why. `insert.length + skipped.length === entities.length`. */
  skipped: SkippedEntity[];
}

export class RestorePlanError extends Error {
  readonly detail: string;
  constructor(message: string, detail = '') {
    super(detail ? `${message}: ${detail}` : message);
    this.name = 'RestorePlanError';
    this.detail = detail;
  }
}

/** PURE — an entity is insertable when it is the society's own data, held verbatim. */
export function isRestorable(e: EntityDescriptor): boolean {
  return e.backupPolicy === 'full' && e.scope === 'society';
}

const EXPLANATION: Record<SkipReason, string> = {
  replay: 'regenerated by the posting engine, then asserted against the archive',
  sidecar: 'carried as evidence and never written back',
  exclude: 'never left the society',
  'global-scope': 'shared platform data, not this society\'s to restore',
};

function skipReasonFor(e: EntityDescriptor): SkipReason | null {
  if (e.backupPolicy === 'replay') return 'replay';
  if (e.backupPolicy === 'sidecar') return 'sidecar';
  if (e.backupPolicy === 'exclude') return 'exclude';
  if (e.scope !== 'society') return 'global-scope';
  return null;
}

/**
 * PURE — dependency-first insert order for the restorable entities.
 *
 * The topological sort runs over the WHOLE graph and the result is filtered afterwards,
 * rather than sorting a pre-filtered subgraph. If a restorable entity ever depends on a
 * non-restorable one, sorting the subgraph would silently drop the edge and could emit a
 * wrong order; sorting the whole graph keeps the transitive ordering intact. Whether such
 * an edge is *legal* is a separate question, answered by `assertDependencyClosure`.
 *
 * Ties break on registry declaration order, so the plan is deterministic across runs.
 * Throws on a cycle — a plausible-but-wrong order is worse than no order.
 */
export function restoreOrder(entities: ExportRegistry): EntityDescriptor[] {
  const cycle = findCycle(entities);
  if (cycle) throw new RestorePlanError('restore graph has a dependency cycle', cycle.join(' → '));

  const byKey = new Map(entities.map(e => [e.key, e]));
  return topoOrder(entities)
    .map(key => byKey.get(key))
    .filter((e): e is EntityDescriptor => !!e && isRestorable(e));
}

/**
 * PURE — every dependency of an insertable entity must itself be insertable.
 *
 * If `voucher` were to depend on `audit_log`, the plan would insert vouchers whose parent
 * row is never written — a dangling reference the restore would call a success. Today the
 * registry satisfies this; the check exists so that the day it stops, a build fails rather
 * than a society's books.
 */
export function assertDependencyClosure(entities: ExportRegistry): void {
  const insertable = new Set(entities.filter(isRestorable).map(e => e.key));
  const known = new Set(entities.map(e => e.key));
  const broken: string[] = [];

  for (const e of entities) {
    if (!isRestorable(e)) continue;
    for (const dep of e.dependsOn) {
      if (!known.has(dep)) continue;             // unresolved dep — validateRegistry's job
      if (!insertable.has(dep)) broken.push(`${e.key} → ${dep}`);
    }
  }
  if (broken.length) {
    throw new RestorePlanError(
      'a restorable entity depends on one that is never restored',
      broken.join(', '),
    );
  }
}

/**
 * PURE — the guard that gives acceptance criterion 2 its teeth.
 *
 * Checked in both directions, because either failure is a data-integrity bug:
 *   forward  — a forbidden key reached the insert plan (the restore would write it).
 *   backward — a forbidden key is no longer excluded by policy, so any OTHER caller
 *              building a plan from `isRestorable` would happily include it.
 *
 * Reached from `planRestore`, the forward check always fires first: its plan is exactly
 * `filter(isRestorable)`, so a flipped policy puts the key straight into `insert`. The
 * backward check earns its place for callers that build a plan some other way — and it
 * is tested directly, not through `planRestore`, for that reason.
 */
export function assertNeverInserted(plan: RestorePlan, entities: ExportRegistry): void {
  const inserting = new Set(plan.insert.map(e => e.key));
  const forward = NEVER_INSERT_KEYS.filter(k => inserting.has(k));
  if (forward.length) {
    throw new RestorePlanError('the insert plan contains entities that must never be inserted', forward.join(', '));
  }

  const byKey = new Map(entities.map(e => [e.key, e]));
  const backward = NEVER_INSERT_KEYS.filter(k => {
    const e = byKey.get(k);
    return e && isRestorable(e);   // present, and its policy now says "insert me"
  });
  if (backward.length) {
    throw new RestorePlanError(
      'an entity on the never-insert list has become restorable — its backupPolicy was changed',
      backward.join(', '),
    );
  }
}

/**
 * PURE — the full plan, with every entity in the registry accounted for exactly once.
 *
 * Like `planArchive`, this refuses to answer with a subset. An entity that is neither
 * inserted nor explained is the failure mode this whole workstream exists to prevent:
 * something quietly missing from a restore, discovered a year later by an auditor.
 */
export function planRestore(entities: ExportRegistry): RestorePlan {
  assertDependencyClosure(entities);

  const insert = restoreOrder(entities);

  const skipped: SkippedEntity[] = [];
  for (const e of entities) {
    const reason = skipReasonFor(e);
    if (reason) skipped.push({ key: e.key, reason, explanation: EXPLANATION[reason] });
  }

  const plan: RestorePlan = { insert, teardown: [...insert].reverse(), skipped };

  // Every entity, exactly once. `isRestorable` and `skipReasonFor` are complements by
  // construction, so this can only fire if one of them is edited without the other.
  if (insert.length + skipped.length !== entities.length) {
    throw new RestorePlanError(
      'the restore plan does not account for every entity',
      `${insert.length} inserted + ${skipped.length} skipped ≠ ${entities.length} declared`,
    );
  }

  assertNeverInserted(plan, entities);
  return plan;
}

/** PURE — a one-line summary for the Restore Center's plan step. */
export function describePlan(plan: RestorePlan, hi = true): string {
  const replayed = plan.skipped.filter(s => s.reason === 'replay').length;
  const evidence = plan.skipped.filter(s => s.reason === 'sidecar').length;
  return hi
    ? `${plan.insert.length} सूचियाँ लिखी जाएँगी, ${replayed} दोबारा बनाई जाएँगी, ${evidence} केवल पढ़ी जाएँगी।`
    : `${plan.insert.length} collections will be written, ${replayed} regenerated, ${evidence} read-only.`;
}
