/**
 * Procurement Phase-0 — Immutable engine-voucher boundary.
 *
 * INVARIANT: from voucher #1 onward, a system-owned (engine-generated) voucher can NEVER be
 * manually mutated — no edit, no cancel, no restore, no RULE-3 cascade. The ONLY permitted
 * correction is an engine-generated reversal voucher. This file holds the pure helpers that
 * the existing accounting flows (guards) and the future Financial Event Engine both reuse.
 */
import type { Voucher, VoucherLine, VoucherOrigin } from '@/types';

/** True iff this voucher is system-owned (generated by the Financial Event Engine). */
export const isEngineVoucher = (v?: { origin?: VoucherOrigin } | null): boolean =>
  v?.origin === 'engine';

/** Toast payload shown when a manual flow attempts to mutate an engine voucher (RULE 7: Hindi-first). */
export const ENGINE_VOUCHER_BLOCK = {
  title: 'सिस्टम वाउचर — बदला नहीं जा सकता',
  description:
    'यह वाउचर सिस्टम द्वारा बनाया गया है (engine-generated)। इसे edit / cancel / restore नहीं किया जा सकता — सुधार केवल reversal voucher से होता है।',
} as const;

export interface ReversalParams {
  id: string;
  voucherNo: string;
  date: string;
  createdAt: string;
  by: string;
}

/**
 * PURE — builds the equal-and-opposite reversal of an engine voucher. It does NOT save, post,
 * toast, publish events, or mutate any state; the Financial Event Engine (Phase 1+) owns those
 * side effects and reuses this builder. The reversal is itself an engine voucher (immutable).
 * The caller supplies id / voucherNo / date (engine controls numbering) → deterministic & testable.
 */
export function buildReversalVoucher(original: Voucher, p: ReversalParams): Voucher {
  const flip = (t: VoucherLine['type']): VoucherLine['type'] => (t === 'Dr' ? 'Cr' : 'Dr');
  return {
    ...original,
    id: p.id,
    voucherNo: p.voucherNo,
    date: p.date,
    createdAt: p.createdAt,
    createdBy: p.by,
    // equal-and-opposite
    debitAccountId: original.creditAccountId,
    creditAccountId: original.debitAccountId,
    lines: original.lines?.map((l) => ({ ...l, type: flip(l.type) })),
    origin: 'engine',
    reversalOf: original.id,
    narration: `Reversal of ${original.voucherNo}${original.narration ? ` — ${original.narration}` : ''}`,
    // a reversal starts clean — never carry over the original's status / audit fields
    isDeleted: false,
    deletedAt: undefined,
    deletedBy: undefined,
    deletedReason: undefined,
    editHistory: undefined,
    isCleared: undefined,
    clearedDate: undefined,
    approvalStatus: undefined,
    approvalRemarks: undefined,
    approvedBy: undefined,
    approvedAt: undefined,
    reversedBy: undefined,
    groupId: undefined,
    billAllocations: undefined,
  };
}
