/**
 * SahakarLekha Blog — hand-authored articles (separate from the auto-generated
 * /guide course). Each post's prose lives in ./<slug>.md and is loaded raw;
 * the metadata below drives the /blog index, per-post SEO and the prerenderer.
 *
 * NOTE for scripts/prerender-guide.mjs: it parses THIS file with a regex that
 * expects, per post and IN THIS ORDER, `slug:`, `metaTitle:`, `metaDescription:`,
 * `date:` as single-quoted strings. Keep those four fields first, in that order,
 * and avoid raw apostrophes inside them.
 */
export interface BlogPost {
  slug: string;
  /** <title> + og:title (≤ ~60 chars ideal) */
  metaTitle: string;
  /** meta description + og:description */
  metaDescription: string;
  /** ISO publish date YYYY-MM-DD */
  date: string;
  /** ISO last-updated date (optional) */
  updated?: string;
  /** category label (Hindi) shown as a chip */
  category: string;
  /** on-page hero heading (Devanagari, can differ from metaTitle) */
  title: string;
  /** short heading used on cards */
  shortTitle: string;
  /** one/two-line summary for cards + article intro */
  excerpt: string;
  /** colour accent key → mapped to a gradient cover in the pages */
  accent: 'emerald' | 'sky' | 'violet' | 'amber' | 'rose' | 'indigo';
  /** topic tags */
  tags: string[];
}

// Reverse-chronological is enforced by sorting on `date` below.
export const BLOG_POSTS: BlogPost[] = [
  // ── Authority articles, Wave 1 (generated from active Knowledge Items / glossary) ──
  {
    slug: 'cooperative-principles-and-values',
    metaTitle: 'सहकारिता के सिद्धांत और मूल्य: हर समिति की बुनियाद | SahakarLekha',
    metaDescription: 'सहकारिता के 7 सिद्धांत और मूल्य आसान भाषा में — एक सदस्य एक वोट, सदस्य-हित, खुलापन। ये समिति के शासन व लेखांकन को कैसे आकार देते हैं।',
    date: '2026-06-10',
    category: 'बैठक व प्रशासन',
    title: 'सहकारिता के सिद्धांत और मूल्य: हर समिति की बुनियाद',
    shortTitle: 'सहकारिता के सिद्धांत व मूल्य',
    excerpt: 'सात सिद्धांत व साझा मूल्य — जो हर सहकारी समिति को कंपनी से अलग बनाते हैं।',
    accent: 'rose',
    tags: ['सहकारिता', 'सिद्धांत', 'शासन'],
  },
  {
    slug: 'cooperative-vs-company-difference',
    metaTitle: 'सहकारी समिति बनाम कंपनी: मुख्य अंतर आसान भाषा में | SahakarLekha',
    metaDescription: 'सहकारी समिति और कंपनी में फर्क — नियंत्रण लोगों के पास बनाम पैसे के पास, सदस्य-हित बनाम निवेशक-लाभ — और इसका लेखांकन पर असर।',
    date: '2026-06-09',
    category: 'लेखांकन मूल बातें',
    title: 'सहकारी समिति बनाम कंपनी: मुख्य अंतर',
    shortTitle: 'सहकारी समिति बनाम कंपनी',
    excerpt: 'नियंत्रण व मकसद का फर्क — और इसी से तय होता है समिति का हिसाब कैसे रखा जाए।',
    accent: 'sky',
    tags: ['सहकारी बनाम कंपनी', 'बुनियाद'],
  },
  {
    slug: 'debit-credit-and-double-entry',
    metaTitle: 'डेबिट, क्रेडिट और डबल एंट्री: हर एंट्री के दो पहलू | SahakarLekha',
    metaDescription: 'डेबिट (नाम) और क्रेडिट (जमा) का असली मतलब, डबल एंट्री सिस्टम और गोल्डन रूल्स — उदाहरण सहित आसान हिन्दी में।',
    date: '2026-06-08',
    category: 'लेखांकन मूल बातें',
    title: 'डेबिट, क्रेडिट और डबल एंट्री: हर एंट्री के दो पहलू',
    shortTitle: 'डेबिट, क्रेडिट व डबल एंट्री',
    excerpt: 'हर लेन-देन के दो पक्ष — Dr और Cr। बुनियाद समझिए, हर रिपोर्ट सही बनेगी।',
    accent: 'violet',
    tags: ['डेबिट-क्रेडिट', 'डबल एंट्री'],
  },
  {
    slug: 'accounting-equation-explained',
    metaTitle: 'अकाउंटिंग इक्वेशन: एसेट = लायबिलिटी + कैपिटल | SahakarLekha',
    metaDescription: 'बैलेंस शीट हमेशा क्यों मिलती है — एसेट = लायबिलिटी + कैपिटल। तीनों हिस्से उदाहरण सहित आसान भाषा में।',
    date: '2026-06-07',
    category: 'लेखांकन मूल बातें',
    title: 'अकाउंटिंग इक्वेशन: एसेट = लायबिलिटी + कैपिटल',
    shortTitle: 'अकाउंटिंग इक्वेशन',
    excerpt: 'एक समीकरण जो बैलेंस शीट का पूरा रहस्य खोल देता है — उदाहरण के साथ।',
    accent: 'amber',
    tags: ['अकाउंटिंग इक्वेशन', 'बैलेंस शीट'],
  },
  {
    slug: 'cash-book-vs-bank-book',
    metaTitle: 'कैश बुक और बैंक बुक: फर्क और सही इस्तेमाल | SahakarLekha',
    metaDescription: 'कैश बुक (भौतिक नकद) और बैंक बुक (बैंक का पैसा) में फर्क, contra एंट्री और सबसे आम चूक से बचाव — आसान भाषा में।',
    date: '2026-06-06',
    category: 'बैंक व रिपोर्ट',
    title: 'कैश बुक और बैंक बुक: फर्क और सही इस्तेमाल',
    shortTitle: 'कैश बुक vs बैंक बुक',
    excerpt: 'कैश और बैंक को अलग रखना सही हिसाब की पहली शर्त है — जानिए कैसे।',
    accent: 'indigo',
    tags: ['कैश बुक', 'बैंक बुक'],
  },
  {
    slug: 'ledger-and-posting-explained',
    metaTitle: 'लेजर और पोस्टिंग: एंट्री से शेष तक | SahakarLekha',
    metaDescription: 'लेजर, लेजर अकाउंट और पोस्टिंग कैसे काम करते हैं — वाउचर से खाते तक, और डे बुक बनाम लेजर का फर्क।',
    date: '2026-06-05',
    category: 'लेखांकन मूल बातें',
    title: 'लेजर और पोस्टिंग: एंट्री से शेष तक',
    shortTitle: 'लेजर व पोस्टिंग',
    excerpt: 'वाउचर लेजर में कैसे पहुँचता है और हर खाते का शेष कैसे बनता है।',
    accent: 'emerald',
    tags: ['लेजर', 'पोस्टिंग'],
  },
  {
    slug: 'trial-balance-explained',
    metaTitle: 'ट्रायल बैलेंस: Dr = Cr क्यों मिलना ज़रूरी है | SahakarLekha',
    metaDescription: 'ट्रायल बैलेंस क्या है, इसके दो कॉलम बराबर क्यों होते हैं, और न मिलने पर क्या करें — किताबों की पहली हेल्थ-चेक।',
    date: '2026-06-04',
    category: 'बैंक व रिपोर्ट',
    title: 'ट्रायल बैलेंस: Dr = Cr क्यों मिलना ज़रूरी है',
    shortTitle: 'ट्रायल बैलेंस कैसे मिलता है',
    excerpt: 'अंतिम खाते से पहले की पहली जाँच — दोनों कॉलम बराबर क्यों, और न मिले तो क्या।',
    accent: 'sky',
    tags: ['ट्रायल बैलेंस', 'Dr Cr'],
  },
  {
    slug: 'chart-of-accounts-groups-heads',
    metaTitle: 'खातों का चार्ट: समूह और शीर्ष सही कैसे बनाएं | SahakarLekha',
    metaDescription: 'अकाउंट ग्रुप और लेजर हेड क्या हैं, सही चार्ट ऑफ़ अकाउंट्स कैसे बनाएं, और मानक नामों से रिपोर्ट साफ़ कैसे रखें।',
    date: '2026-06-03',
    category: 'लेखांकन मूल बातें',
    title: 'खातों का चार्ट: समूह और शीर्ष सही कैसे बनाएं',
    shortTitle: 'खातों का चार्ट (समूह व शीर्ष)',
    excerpt: 'सही समूह व शीर्ष = साफ़, सही रिपोर्ट। चार्ट ऑफ़ अकाउंट्स की बुनियाद।',
    accent: 'violet',
    tags: ['चार्ट ऑफ अकाउंट्स', 'लेजर हेड'],
  },
  {
    slug: 'voucher-narration-and-documents',
    metaTitle: 'वाउचर विवरण और दस्तावेज़: ऑडिट-तैयार बही की कुंजी | SahakarLekha',
    metaDescription: 'अच्छा narration कैसे लिखें और कौन-से समर्थक दस्तावेज़ रखें — ताकि हर एंट्री समझने-योग्य व ऑडिट-तैयार रहे।',
    date: '2026-06-02',
    category: 'वाउचर एंट्री',
    title: 'वाउचर विवरण और दस्तावेज़: ऑडिट-तैयार बही की कुंजी',
    shortTitle: 'वाउचर विवरण व दस्तावेज़',
    excerpt: 'दो छोटी आदतें — साफ़ विवरण और सबूत — जो ऑडिट को सहज बना देती हैं।',
    accent: 'amber',
    tags: ['narration', 'दस्तावेज़', 'ऑडिट'],
  },
  {
    slug: 'membership-rights-and-duties',
    metaTitle: 'सदस्यता: कौन है सदस्य, अधिकार व कर्तव्य | SahakarLekha',
    metaDescription: 'सदस्य कौन होता है, सदस्यता के प्रकार (नाममात्र, सहयोगी), अधिकार-कर्तव्य का संतुलन और नॉमिनी का महत्व — आसान भाषा में।',
    date: '2026-06-01',
    category: 'सदस्य व ऋण',
    title: 'सदस्यता: कौन है सदस्य, और उसके अधिकार व कर्तव्य',
    shortTitle: 'सदस्यता: अधिकार व कर्तव्य',
    excerpt: 'सदस्य मालिक भी, उपयोगकर्ता भी — अधिकार के साथ कर्तव्य भी। पूरी समझ।',
    accent: 'rose',
    tags: ['सदस्यता', 'अधिकार', 'कर्तव्य'],
  },
  {
    slug: 'share-capital-authorised-issued-paidup',
    metaTitle: 'शेयर कैपिटल: अधिकृत, निर्गमित और चुकता का फर्क | SahakarLekha',
    metaDescription: 'अधिकृत, निर्गमित और पेड-अप कैपिटल में फर्क, फेस वैल्यू और शेयर सर्टिफिकेट — उदाहरण सहित आसान भाषा में।',
    date: '2026-05-31',
    category: 'सदस्य व ऋण',
    title: 'शेयर कैपिटल: अधिकृत, निर्गमित और चुकता का फर्क',
    shortTitle: 'शेयर कैपिटल के प्रकार',
    excerpt: 'अधिकृत ≥ निर्गमित ≥ चुकता — और बैलेंस शीट पर असली आँकड़ा कौन-सा।',
    accent: 'indigo',
    tags: ['शेयर कैपिटल', 'शेयर'],
  },
  {
    slug: 'bank-payment-methods-cheque-dd-upi',
    metaTitle: 'बैंक भुगतान के तरीके: चेक, DD, NEFT/RTGS और UPI | SahakarLekha',
    metaDescription: 'चेक, डिमांड ड्राफ्ट, NEFT/RTGS और UPI में फर्क और सही इस्तेमाल — और हर तरीका बैंक बुक में कैसे दर्ज करें।',
    date: '2026-05-30',
    category: 'बैंक व रिपोर्ट',
    title: 'बैंक भुगतान के तरीके: चेक, DD, NEFT/RTGS और UPI',
    shortTitle: 'बैंक भुगतान के तरीके',
    excerpt: 'कौन-सा तरीका कब, और हर एक को बैंक बुक में सही दर्ज कैसे करें।',
    accent: 'emerald',
    tags: ['चेक', 'UPI', 'NEFT'],
  },
  {
    slug: 'financial-year-and-accounting-period',
    metaTitle: 'वित्तीय वर्ष और लेखांकन अवधि: खाते किस समय के लिए | SahakarLekha',
    metaDescription: 'वित्तीय वर्ष (अप्रैल–मार्च) और लेखांकन अवधि क्या हैं, इनका फर्क, और हर रिपोर्ट इनसे क्यों बँधी होती है।',
    date: '2026-05-29',
    category: 'लेखांकन मूल बातें',
    title: 'वित्तीय वर्ष और लेखांकन अवधि: खाते किस समय के लिए',
    shortTitle: 'वित्तीय वर्ष व अवधि',
    excerpt: 'सही वित्तीय वर्ष व अवधि से सालभर की रिपोर्ट व तुलनाएँ भरोसेमंद रहती हैं।',
    accent: 'sky',
    tags: ['वित्तीय वर्ष', 'अवधि'],
  },
  {
    slug: 'accounting-assumptions-going-concern-prudence',
    metaTitle: 'लेखांकन की बुनियादी मान्यताएँ: गोइंग कंसर्न व प्रूडेंस | SahakarLekha',
    metaDescription: 'गोइंग कंसर्न (going concern) और प्रूडेंस (prudence) — दो बुनियादी लेखांकन मान्यताएँ जो खाते को यथार्थवादी व भरोसेमंद बनाती हैं।',
    date: '2026-05-28',
    category: 'लेखांकन मूल बातें',
    title: 'लेखांकन की बुनियादी मान्यताएँ: गोइंग कंसर्न और प्रूडेंस',
    shortTitle: 'लेखांकन की बुनियादी मान्यताएँ',
    excerpt: 'खातों के पीछे की सोच — गोइंग कंसर्न व प्रूडेंस, आसान भाषा में।',
    accent: 'violet',
    tags: ['going concern', 'prudence'],
  },
  {
    slug: 'choosing-cooperative-accounting-software',
    metaTitle: 'समिति के लिए लेखा सॉफ्टवेयर कैसे चुनें: चेकलिस्ट | SahakarLekha',
    metaDescription: 'सहकारी समिति के लिए सही लेखा सॉफ्टवेयर कैसे चुनें — सहकारी-केंद्रित, हिन्दी-अनुकूल, किफ़ायती, सुरक्षित, क्लाउड व माइग्रेशन-सहित।',
    date: '2026-05-27',
    category: 'डिजिटल लेखांकन',
    title: 'समिति के लिए लेखा सॉफ्टवेयर कैसे चुनें',
    shortTitle: 'सॉफ्टवेयर कैसे चुनें',
    excerpt: 'गलत टूल पैसा-मेहनत बर्बाद करता है — समिति को क्या-क्या देखना चाहिए।',
    accent: 'amber',
    tags: ['सॉफ्टवेयर चयन', 'क्लाउड'],
  },
  {
    slug: 'getting-started-sahakarlekha',
    metaTitle: 'SahakarLekha में शुरुआत: सेटअप से पहली रिपोर्ट तक | SahakarLekha',
    metaDescription: 'नई समिति के लिए साफ़ रास्ता — रजिस्टर, समिति सेटअप, खाते व सदस्य, ओपनिंग बैलेंस, पहला वाउचर और पहली रिपोर्ट।',
    date: '2026-05-26',
    category: 'डिजिटल लेखांकन',
    title: 'SahakarLekha में शुरुआत: सेटअप से पहली रिपोर्ट तक',
    shortTitle: 'शुरुआत कैसे करें',
    excerpt: 'कहाँ से और किस क्रम में शुरू करें — पहले ही दिन समिति लाइव।',
    accent: 'emerald',
    tags: ['शुरुआत', 'सेटअप', 'onboarding'],
  },
  {
    slug: 'user-roles-and-permissions',
    metaTitle: 'उपयोगकर्ता भूमिका और अनुमति: सुरक्षित पहुँच कैसे दें | SahakarLekha',
    metaDescription: 'भूमिका (role) और अनुमति (permission) में फर्क, least-privilege पहुँच और maker-checker — समिति के डेटा को सुरक्षित कैसे रखें।',
    date: '2026-05-25',
    category: 'डिजिटल लेखांकन',
    title: 'उपयोगकर्ता भूमिका और अनुमति: सुरक्षित पहुँच कैसे दें',
    shortTitle: 'भूमिका व अनुमति',
    excerpt: 'किसे कितनी पहुँच — least-privilege व maker-checker से सुरक्षित नियंत्रण।',
    accent: 'sky',
    tags: ['भूमिका', 'अनुमति', 'सुरक्षा'],
  },
  {
    slug: 'migrate-from-tally-or-excel',
    metaTitle: 'Tally या Excel से SahakarLekha में आएं: बिना डेटा खोए | SahakarLekha',
    metaDescription: 'Tally/Excel से माइग्रेशन कैसे करें — यूनिवर्सल इम्पोर्टर से मास्टर, ओपनिंग बैलेंस व इतिहास साथ लाएं, बिना दोबारा टाइप किए।',
    date: '2026-05-24',
    category: 'डिजिटल लेखांकन',
    title: 'Tally या Excel से SahakarLekha में आएं: बिना डेटा खोए',
    shortTitle: 'Tally/Excel से माइग्रेशन',
    excerpt: 'पुराना डेटा खोने का डर खत्म — साफ़ माइग्रेशन के साथ बिना रुके डिजिटल।',
    accent: 'indigo',
    tags: ['माइग्रेशन', 'Tally', 'import'],
  },
  {
    slug: 'dairy-cooperative-accounting-basics',
    metaTitle: 'दुग्ध सहकारी समिति: हिसाब की बुनियाद समझें | SahakarLekha',
    metaDescription: 'दुग्ध सहकारी समिति कैसे काम करती है — दूध संग्रह, गुणवत्ता व सदस्य-भुगतान — और हिसाब की बुनियाद। फैट/SNF उपचार विशेषज्ञ-सत्यापन योग्य।',
    date: '2026-05-23',
    category: 'लेखांकन मूल बातें',
    title: 'दुग्ध सहकारी समिति: हिसाब की बुनियाद समझें',
    shortTitle: 'दुग्ध समिति: हिसाब की बुनियाद',
    excerpt: 'दूध संग्रह, गुणवत्ता व सदस्य-भुगतान — दुग्ध समिति की बुनियादी समझ।',
    accent: 'rose',
    tags: ['दुग्ध समिति', 'डेयरी'],
  },
  {
    slug: 'cash-handling-and-verification',
    metaTitle: 'कैश संभाल और सत्यापन: नकद का सही हिसाब | SahakarLekha',
    metaDescription: 'कैश बुक का शेष असल नकद से कैसे मिलाएं, कैश सत्यापन की आदतें और आम चूकों से बचाव — समिति की नकद हमेशा सही रखें।',
    date: '2026-05-22',
    category: 'बैंक व रिपोर्ट',
    title: 'कैश संभाल और सत्यापन: नकद का सही हिसाब',
    shortTitle: 'कैश संभाल व सत्यापन',
    excerpt: 'नकद में सबसे ज़्यादा गलतियाँ — अनुशासित संभाल व सत्यापन से बचाव।',
    accent: 'amber',
    tags: ['कैश', 'सत्यापन', 'नकद'],
  },
  {
    slug: 'agm-preparation-checklist',
    metaTitle: 'AGM (वार्षिक आम सभा) की तैयारी: संपूर्ण चेकलिस्ट | SahakarLekha',
    metaDescription: 'सहकारी समिति की वार्षिक आम सभा से पहले क्या तैयार रखें — अंतिम खाते, ऑडिट रिपोर्ट, बँटवारा व कार्यवृत्त — आसान चेकलिस्ट।',
    date: '2026-09-15',
    category: 'बैठक व प्रशासन',
    title: 'AGM (वार्षिक आम सभा) की तैयारी: संपूर्ण चेकलिस्ट',
    shortTitle: 'AGM की तैयारी: चेकलिस्ट',
    excerpt: 'वार्षिक आम सभा से पहले दस्तावेज़, बँटवारा-प्रस्ताव व कार्यवृत्त — सब तैयार कैसे रखें।',
    accent: 'rose',
    tags: ['AGM', 'बैठक', 'प्रशासन'],
  },
  {
    slug: 'quarterly-compliance-calendar',
    metaTitle: 'तिमाही अनुपालन कैलेंडर: GST, TDS व रिटर्न की due-dates | SahakarLekha',
    metaDescription: 'GST, TDS, 26Q व रिटर्न की due-dates का सरल ढाँचा + मासिक 5-मिनट जाँच — जुर्माने से बचें।',
    date: '2026-10-13',
    category: 'कर अनुपालन',
    title: 'तिमाही अनुपालन कैलेंडर: GST, TDS व रिटर्न की due-dates',
    shortTitle: 'तिमाही अनुपालन कैलेंडर',
    excerpt: 'कब क्या फ़ाइल/जमा करना है — एक कैलेंडर व मासिक आदत से समिति जुर्माना-मुक्त रहती है।',
    accent: 'amber',
    tags: ['अनुपालन', 'GST', 'TDS'],
  },
  {
    slug: 'cooperative-week-going-digital',
    metaTitle: 'सहकारिता सप्ताह: डिजिटल सहकारिता की ओर एक कदम | SahakarLekha',
    metaDescription: 'सहकारिता सप्ताह पर समिति के लिए 3 संकल्प — डिजिटल हिसाब, पारदर्शिता व समय पर अनुपालन।',
    date: '2026-11-17',
    category: 'डिजिटल लेखांकन',
    title: 'सहकारिता सप्ताह: डिजिटल सहकारिता की ओर एक कदम',
    shortTitle: 'सहकारिता सप्ताह: डिजिटल की ओर',
    excerpt: 'सहकारिता सप्ताह पर अपनी समिति के लिए 3 संकल्प — डिजिटल, पारदर्शी, अनुपालन-तैयार।',
    accent: 'emerald',
    tags: ['सहकारिता सप्ताह', 'डिजिटल'],
  },
  {
    slug: 'loan-recovery-before-year-end',
    metaTitle: 'ऋण वसूली: वर्ष-अंत से पहले का सबसे ज़रूरी काम | SahakarLekha',
    metaDescription: 'बकाया-उम्र (aging) से वसूली सूची, वसूली% व NPA पर नज़र — वर्षांत से पहले व्यवस्थित ऋण वसूली।',
    date: '2026-12-15',
    category: 'सदस्य व ऋण',
    title: 'ऋण वसूली: वर्ष-अंत से पहले का सबसे ज़रूरी काम',
    shortTitle: 'ऋण वसूली: वर्ष-अंत से पहले',
    excerpt: 'aging-सूची, वसूली% व NPA — बकाया वसूली को व्यवस्थित कैसे करें, वर्ष-अंत से पहले।',
    accent: 'indigo',
    tags: ['वसूली', 'NPA', 'ऋण'],
  },
  {
    slug: 'half-year-financial-review',
    metaTitle: 'साल के बीच की वित्तीय समीक्षा: अभी क्यों ज़रूरी | SahakarLekha',
    metaDescription: '6-महीने का हेल्थ-चेक — ट्रायल बैलेंस, वसूली%, खर्च बनाम बजट — वर्षांत की भागदौड़ से बचें।',
    date: '2027-01-13',
    category: 'बैंक व रिपोर्ट',
    title: 'साल के बीच की वित्तीय समीक्षा: अभी क्यों ज़रूरी',
    shortTitle: 'साल के बीच की समीक्षा',
    excerpt: 'छमाही समीक्षा से गलतियाँ जल्दी पकड़ में आती हैं और वर्षांत आसान हो जाता है।',
    accent: 'sky',
    tags: ['समीक्षा', 'रिपोर्ट'],
  },
  {
    slug: 'year-end-readiness-checklist',
    metaTitle: 'वर्षांत से पहले: 10 ज़रूरी काम (FY क्लोज़िंग की तैयारी) | SahakarLekha',
    metaDescription: 'मार्च से पहले निपटाने वाले 10 काम — मिलान, स्टॉक, डेप्रिसिएशन, समायोजन — ताकि साल का अंत सहज हो।',
    date: '2027-02-17',
    category: 'मुनाफ़ा व बँटवारा',
    title: 'वर्षांत से पहले: 10 ज़रूरी काम (FY क्लोज़िंग की तैयारी)',
    shortTitle: 'वर्षांत से पहले: 10 काम',
    excerpt: 'मार्च की भागदौड़ से बचने के लिए समय रहते निपटाने वाली 10-काम की तैयारी-चेकलिस्ट।',
    accent: 'violet',
    tags: ['वर्षांत', 'चेकलिस्ट'],
  },
  {
    slug: 'new-financial-year-and-budget',
    metaTitle: 'नया वित्तीय वर्ष: सही शुरुआत और वार्षिक बजट | SahakarLekha',
    metaDescription: 'अप्रैल में नए साल की सही शुरुआत — सही ओपनिंग बैलेंस व एक साफ़ बजट से पूरा साल व्यवस्थित।',
    date: '2027-04-07',
    category: 'लेखांकन मूल बातें',
    title: 'नया वित्तीय वर्ष: सही शुरुआत और वार्षिक बजट',
    shortTitle: 'नया वित्तीय वर्ष व बजट',
    excerpt: 'सही opening और साफ़ बजट — नए वित्तीय वर्ष को व्यवस्थित व तनाव-मुक्त कैसे बनाएँ।',
    accent: 'emerald',
    tags: ['नया FY', 'बजट'],
  },
  {
    slug: 'annual-statutory-returns',
    metaTitle: 'वार्षिक व कानूनी रिटर्न: साल बंद होने के बाद के काम | SahakarLekha',
    metaDescription: 'विभाग/संघ को वार्षिक रिटर्न, due-dates व रिकॉर्ड — साफ़ खातों से कानूनी रिटर्न आसान।',
    date: '2027-05-12',
    category: 'ऑडिट व अनुपालन',
    title: 'वार्षिक व कानूनी रिटर्न: साल बंद होने के बाद के ज़रूरी काम',
    shortTitle: 'वार्षिक व कानूनी रिटर्न',
    excerpt: 'विभाग/संघ को वार्षिक रिटर्न समय पर — साफ़ खातों से यह रिपोर्ट निकालने जितना आसान।',
    accent: 'amber',
    tags: ['रिटर्न', 'अनुपालन'],
  },
  {
    slug: 'gst-for-cooperatives',
    metaTitle: 'GST सहकारी समिति के लिए: आसान गाइड | SahakarLekha',
    metaDescription: 'आउटपुट/इनपुट GST, ITC, GSTR-1/2B/3B और रियायती बिल पर सही कर — सहकारी समिति के लिए आसान GST गाइड।',
    date: '2026-06-30',
    category: 'कर अनुपालन',
    title: 'GST सहकारी समिति के लिए: आसान गाइड',
    shortTitle: 'GST सहकारी समिति के लिए',
    excerpt: 'आउटपुट-इनपुट GST, ITC मिलान और मासिक फ़ाइलिंग — GST को सहकारी समिति के नज़रिये से आसान बनाइए।',
    accent: 'sky',
    tags: ['GST', 'ITC', 'कर'],
  },
  {
    slug: 'tds-and-26q-for-societies',
    metaTitle: 'TDS और 26Q: सहकारी समिति के लिए सरल गाइड | SahakarLekha',
    metaDescription: 'TDS कब-कितना काटें, समय पर जमा, और तिमाही 26Q — सहकारी समिति के लिए आसान TDS गाइड।',
    date: '2026-07-07',
    category: 'कर अनुपालन',
    title: 'TDS और 26Q: सहकारी समिति के लिए सरल गाइड',
    shortTitle: 'TDS और 26Q गाइड',
    excerpt: 'किन भुगतानों पर TDS, सही कटौती-जमा, और तिमाही 26Q — उदाहरण सहित आसान भाषा में।',
    accent: 'amber',
    tags: ['TDS', '26Q', 'कर'],
  },
  {
    slug: 'depreciation-explained',
    metaTitle: 'डेप्रिसिएशन (घिसाई) कैसे करें: आसान समझ | SahakarLekha',
    metaDescription: 'SLM बनाम WDV, डेप्रिसिएशन की एंट्री और शेड्यूल — सही लाभ व बैलेंस शीट के लिए आसान गाइड।',
    date: '2026-08-25',
    category: 'लेखांकन मूल बातें',
    title: 'डेप्रिसिएशन (घिसाई) कैसे करें: आसान समझ',
    shortTitle: 'डेप्रिसिएशन कैसे करें',
    excerpt: 'संपत्तियों की घटती कीमत हर साल कैसे दर्ज करें — SLM/WDV, एंट्री और शेड्यूल सरल भाषा में।',
    accent: 'violet',
    tags: ['डेप्रिसिएशन', 'संपत्ति'],
  },
  {
    slug: 'year-end-closing-and-fy-lock',
    metaTitle: 'वर्षांत प्रक्रिया व FY-लॉक: साल कैसे बंद करें | SahakarLekha',
    metaDescription: 'साल बंद करने की चेकलिस्ट — समायोजन, अंतिम खाते, FY-लॉक — और closing से opening की सही कड़ी।',
    date: '2026-09-01',
    category: 'मुनाफ़ा व बँटवारा',
    title: 'वर्षांत प्रक्रिया व FY-लॉक: साल कैसे बंद करें',
    shortTitle: 'वर्षांत व FY-लॉक',
    excerpt: 'वर्षांत की चेकलिस्ट, अंतिम खाते और FY-लॉक — साल को साफ़, स्थिर व ऑडिट-रेडी बंद कीजिए।',
    accent: 'emerald',
    tags: ['वर्षांत', 'FY-लॉक'],
  },
  {
    slug: 'opening-balances-new-society',
    metaTitle: 'ओपनिंग बैलेंस: नई समिति या नए साल की सही शुरुआत | SahakarLekha',
    metaDescription: 'हर खाते का सही शुरुआती शेष व Dr=Cr — तुलन-पत्र पहले दिन से मिले, इसका आसान तरीका।',
    date: '2026-08-11',
    category: 'लेखांकन मूल बातें',
    title: 'ओपनिंग बैलेंस: नई समिति या नए साल की सही शुरुआत',
    shortTitle: 'ओपनिंग बैलेंस कैसे डालें',
    excerpt: 'सही ओपनिंग बैलेंस = साल भर सही खाते। Dr=Cr कैसे मिलाएँ, उदाहरण सहित।',
    accent: 'rose',
    tags: ['ओपनिंग बैलेंस', 'शुरुआत'],
  },
  {
    slug: 'kcc-crop-loan-accounting',
    metaTitle: 'KCC व फसल ऋण लेखांकन: PACS के लिए गाइड | SahakarLekha',
    metaDescription: 'KCC ऋण को संपत्ति, ब्याज को आय, अनुदान अलग, और वसूली/NPA की निगरानी — PACS के लिए आसान गाइड।',
    date: '2026-07-14',
    category: 'सदस्य व ऋण',
    title: 'KCC व फसल ऋण लेखांकन: PACS के लिए गाइड',
    shortTitle: 'KCC व फसल ऋण लेखांकन',
    excerpt: 'KCC ऋण, ब्याज, ब्याज-सहायता और वसूली/NPA — किसान-ऋण का सही हिसाब आसान भाषा में।',
    accent: 'indigo',
    tags: ['KCC', 'फसल ऋण', 'PACS'],
  },
  {
    slug: 'salary-and-payroll-accounting',
    metaTitle: 'वेतन व पेरोल लेखांकन: EPF, ESI व TDS सहित | SahakarLekha',
    metaDescription: 'सकल-शुद्ध वेतन, EPF/ESI/TDS कटौतियाँ और उनकी समय पर जमा — सहकारी समिति के लिए आसान पेरोल गाइड।',
    date: '2026-08-04',
    category: 'लेखांकन मूल बातें',
    title: 'वेतन व पेरोल लेखांकन: EPF, ESI व TDS सहित',
    shortTitle: 'वेतन व पेरोल लेखांकन',
    excerpt: 'सकल बनाम शुद्ध वेतन, हर कटौती की अलग देनदारी, और समय पर जमा — उदाहरण सहित।',
    accent: 'amber',
    tags: ['वेतन', 'EPF', 'ESI'],
  },
  {
    slug: 'data-security-and-backup',
    metaTitle: 'डेटा सुरक्षा व बैकअप: समिति का हिसाब कभी न खोएँ | SahakarLekha',
    metaDescription: 'लोकल बनाम क्लाउड, भूमिका-नियंत्रण, नियमित बैकअप व निर्यात — समिति के डेटा को सुरक्षित रखने की गाइड।',
    date: '2026-08-18',
    category: 'डिजिटल लेखांकन',
    title: 'डेटा सुरक्षा व बैकअप: समिति का हिसाब कभी न खोएँ',
    shortTitle: 'डेटा सुरक्षा व बैकअप',
    excerpt: 'क्लाउड बैकअप, भूमिका-आधारित पहुँच और निर्यात — ताकि समिति का हिसाब कभी न खोए।',
    accent: 'sky',
    tags: ['सुरक्षा', 'बैकअप', 'क्लाउड'],
  },
  {
    slug: 'nabard-and-federation-returns',
    metaTitle: 'NABARD व फेडरेशन रिटर्न: सहकारी समिति की रिपोर्टिंग | SahakarLekha',
    metaDescription: 'सदस्य-वृद्धि, कैपिटल, ऋण-वसूली, NPA व संघ प्रपत्र — साफ़ खातों से NABARD/फेडरेशन रिपोर्ट आसान।',
    date: '2026-07-28',
    category: 'ऑडिट व अनुपालन',
    title: 'NABARD व फेडरेशन रिटर्न: सहकारी समिति की रिपोर्टिंग',
    shortTitle: 'NABARD व फेडरेशन रिटर्न',
    excerpt: 'ये रिपोर्ट साफ़ खातों का स्वाभाविक नतीजा हैं — कौन-सा डेटा, और कैसे आसान बनाएँ।',
    accent: 'violet',
    tags: ['NABARD', 'फेडरेशन', 'रिटर्न'],
  },
  {
    slug: 'cooperative-society-types-guide',
    metaTitle: 'सहकारी समिति के प्रकार: किसके लिए कौन-सा सेटअप | SahakarLekha',
    metaDescription: 'PACS, दुग्ध, उपभोक्ता, मार्केटिंग, बहुउद्देशीय — हर प्रकार की समिति की खास लेखांकन-ज़रूरत व सही सेटअप।',
    date: '2026-07-21',
    category: 'डिजिटल लेखांकन',
    title: 'सहकारी समिति के प्रकार: किसके लिए कौन-सा सेटअप',
    shortTitle: 'सहकारी समिति के प्रकार',
    excerpt: 'हर प्रकार की समिति की अलग ज़रूरत — और जो बुनियाद सबमें समान रहती है।',
    accent: 'emerald',
    tags: ['समिति प्रकार', 'PACS', 'सेटअप'],
  },
  {
    slug: 'profit-distribution-and-reserves',
    metaTitle: 'सहकारी समिति में लाभ का बँटवारा: रिज़र्व, डिविडेंड और बोनस | SahakarLekha',
    metaDescription: 'सहकारी समिति में नेट प्रॉफ़िट किस क्रम में बाँटें — पहले रिज़र्व फंड, फिर डिविडेंड और बोनस, और ज़रूरत से ज़्यादा बाँटने से बचाव।',
    date: '2026-06-25',
    category: 'लाभ व बँटवारा',
    title: 'लाभ का बँटवारा: रिज़र्व फंड, डिविडेंड और बोनस',
    shortTitle: 'लाभ का बँटवारा (प्रॉफ़िट)',
    excerpt: 'नेट प्रॉफ़िट किस क्रम में बाँटें — पहले रिज़र्व फंड, फिर डिविडेंड और बोनस, और ज़रूरत से ज़्यादा बाँटने से बचाव।',
    accent: 'amber',
    tags: ['लाभ', 'डिविडेंड', 'रिज़र्व फंड'],
  },
  {
    slug: 'member-and-share-accounting',
    metaTitle: 'सदस्य व शेयर रजिस्टर: सहकारी समिति में सही लेखांकन | SahakarLekha',
    metaDescription: 'शेयर कैपिटल, प्रवेश शुल्क और डिविडेंड का पारदर्शी हिसाब कैसे रखें — सदस्य-भरोसा बढ़ाने वाली गाइड।',
    date: '2026-06-18',
    category: 'सदस्य व ऋण',
    title: 'सदस्य व शेयर रजिस्टर: सहकारी समिति में सही लेखांकन',
    shortTitle: 'सदस्य व शेयर रजिस्टर लेखांकन',
    excerpt: 'प्रवेश शुल्क बनाम शेयर कैपिटल, सदस्य-बही, डिविडेंड और निकासी पर शेयर-वापसी — सब सही तरीके से।',
    accent: 'rose',
    tags: ['सदस्य', 'शेयर कैपिटल', 'डिविडेंड'],
  },
  {
    slug: 'loan-and-interest-accounting',
    metaTitle: 'ऋण व ब्याज लेखांकन: PACS व समितियों के लिए गाइड | SahakarLekha',
    metaDescription: 'सदस्य ऋण, KCC और ब्याज की सही गणना व रिकॉर्डिंग — वसूली व NPA निगरानी सहित।',
    date: '2026-06-17',
    category: 'सदस्य व ऋण',
    title: 'ऋण व ब्याज लेखांकन: PACS व समितियों के लिए गाइड',
    shortTitle: 'ऋण व ब्याज लेखांकन',
    excerpt: 'ऋण को संपत्ति, ब्याज को आय मानना; KCC की बारीकियाँ; और वसूली% व NPA की निगरानी।',
    accent: 'amber',
    tags: ['ऋण', 'ब्याज', 'KCC', 'NPA'],
  },
  {
    slug: 'inventory-and-stock-management',
    metaTitle: 'इन्वेंटरी व स्टॉक प्रबंधन: मार्केटिंग व उपभोक्ता समितियों के लिए | SahakarLekha',
    metaDescription: 'खरीद-बिक्री, स्टॉक वैल्यूएशन और क्लोज़िंग स्टॉक का सटीक हिसाब — फैंटम बैलेंस से बचें।',
    date: '2026-06-16',
    category: 'इन्वेंटरी',
    title: 'इन्वेंटरी व स्टॉक प्रबंधन: मार्केटिंग व उपभोक्ता समितियों के लिए',
    shortTitle: 'इन्वेंटरी व स्टॉक प्रबंधन',
    excerpt: 'एक-सूत्र स्टॉक नियम, वेटेड एवरेज मूल्य, और क्लोज़िंग स्टॉक की एकल गणना से सही लाभ।',
    accent: 'indigo',
    tags: ['इन्वेंटरी', 'स्टॉक', 'closing stock'],
  },
  {
    slug: 'bank-reconciliation-guide',
    metaTitle: 'बैंक समाधान (BRS) कैसे करें: सहकारी समिति गाइड | SahakarLekha',
    metaDescription: 'बैंक स्टेटमेंट और बही का मिलान आसानी से — अंतर कैसे ढूँढें और ठीक करें।',
    date: '2026-06-15',
    category: 'बैंक व रिपोर्ट',
    title: 'बैंक समाधान (BRS) कैसे करें: सहकारी समिति गाइड',
    shortTitle: 'बैंक समाधान (BRS) कैसे करें',
    excerpt: 'अनभुनाए चेक, बैंक प्रभार और छूटी एंट्रियाँ — हर अंतर पहचानकर बैंक बैलेंस मिनटों में मिलाएँ।',
    accent: 'sky',
    tags: ['बैंक समाधान', 'BRS', 'मिलान'],
  },
  {
    slug: 'how-to-read-financial-reports',
    metaTitle: 'वित्तीय रिपोर्ट्स कैसे पढ़ें: Trial Balance से Balance Sheet तक | SahakarLekha',
    metaDescription: 'ट्रायल बैलेंस, लाभ-हानि, रसीद-भुगतान और बैलेंस शीट को आसान हिन्दी में पढ़ना सीखें।',
    date: '2026-06-14',
    category: 'बैंक व रिपोर्ट',
    title: 'वित्तीय रिपोर्ट्स कैसे पढ़ें: Trial Balance से Balance Sheet तक',
    shortTitle: 'वित्तीय रिपोर्ट्स कैसे पढ़ें',
    excerpt: 'हर रिपोर्ट एक सवाल का जवाब है — पाँच मुख्य रिपोर्ट्स और उनका आपसी जुड़ाव सरल भाषा में।',
    accent: 'emerald',
    tags: ['रिपोर्ट', 'ट्रायल बैलेंस', 'बैलेंस शीट'],
  },
  {
    slug: 'audit-preparation-checklist',
    metaTitle: 'सहकारी समिति ऑडिट की तैयारी: संपूर्ण चेकलिस्ट | SahakarLekha',
    metaDescription: 'ऑडिट से पहले क्या तैयार रखें, कौन-सी रिपोर्ट चाहिए और audit paras कैसे घटाएँ — व्यावहारिक चेकलिस्ट।',
    date: '2026-06-13',
    category: 'ऑडिट व अनुपालन',
    title: 'सहकारी समिति ऑडिट की तैयारी: संपूर्ण चेकलिस्ट',
    shortTitle: 'ऑडिट की तैयारी: चेकलिस्ट',
    excerpt: 'तैयार दस्तावेज़, सबसे आम आपत्तियाँ और उनका बचाव — ऑडिट को कुछ दिनों का सहज काम बनाइए।',
    accent: 'violet',
    tags: ['ऑडिट', 'चेकलिस्ट', 'अनुपालन'],
  },
  {
    slug: 'common-accounting-mistakes',
    metaTitle: 'सहकारी समितियों की 10 आम लेखांकन गलतियाँ और बचाव | SahakarLekha',
    metaDescription: 'जो गलतियाँ हर साल ऑडिट में पकड़ी जाती हैं — और उन्हें रोकने के आसान तरीके।',
    date: '2026-06-12',
    category: 'ऑडिट व अनुपालन',
    title: 'सहकारी समितियों की 10 आम लेखांकन गलतियाँ (और उनसे बचाव)',
    shortTitle: '10 आम लेखांकन गलतियाँ',
    excerpt: 'खाते मिलाना, suspense, डबल-काउंट स्टॉक, वाउचर मिटाना — 10 आम चूकें और उनका सरल बचाव।',
    accent: 'rose',
    tags: ['गलतियाँ', 'ऑडिट', 'बचाव'],
  },
  {
    slug: 'future-of-cooperative-erp',
    metaTitle: 'सहकारी ERP का भविष्य: डिजिटल सहकारिता की ओर | SahakarLekha',
    metaDescription: 'क्लाउड, AI और एकीकृत रिपोर्टिंग सहकारी क्षेत्र को कैसे बदलेंगे — और समितियाँ अभी क्या करें।',
    date: '2026-06-11',
    category: 'डिजिटल लेखांकन',
    title: 'सहकारी ERP का भविष्य: डिजिटल सहकारिता की ओर',
    shortTitle: 'सहकारी ERP का भविष्य',
    excerpt: 'क्लाउड-फ़र्स्ट, एकीकृत अनुपालन, रीयल-टाइम डैशबोर्ड और सहायक AI — और तीन सिद्धांत जो नहीं बदलते।',
    accent: 'indigo',
    tags: ['ERP', 'भविष्य', 'क्लाउड'],
  },
  {
    slug: 'voucher-entry-guide',
    metaTitle: 'वाउचर एंट्री कैसे करें: स्टेप-बाय-स्टेप गाइड | SahakarLekha',
    metaDescription: 'Receipt, Payment, Journal व Contra वाउचर सही तरीके से कैसे भरें — उदाहरण सहित संपूर्ण मार्गदर्शिका सहकारी समिति के लिए।',
    date: '2026-06-19',
    category: 'वाउचर एंट्री',
    title: 'वाउचर एंट्री कैसे करें: स्टेप-बाय-स्टेप गाइड',
    shortTitle: 'वाउचर एंट्री कैसे करें',
    excerpt: 'चार प्रकार के वाउचर, "पैसा आया या गया" से Dr/Cr तय करना, और हर रिपोर्ट को सही बनाने का सरल तरीका।',
    accent: 'violet',
    tags: ['वाउचर', 'रसीद-भुगतान', 'डबल-एंट्री'],
  },
  {
    slug: 'cooperative-accounting-basics',
    metaTitle: 'सहकारी लेखांकन की मूल बातें: शुरुआत से समझें | SahakarLekha',
    metaDescription: 'डबल-एंट्री, खातों के पाँच प्रकार, डेबिट-क्रेडिट और अकाउंटिंग इक्वेशन — नए सचिव व लेखाकार के लिए आसान हिन्दी गाइड।',
    date: '2026-06-21',
    category: 'लेखांकन मूल बातें',
    title: 'सहकारी लेखांकन की मूल बातें: नए सचिव व लेखाकार के लिए',
    shortTitle: 'सहकारी लेखांकन की मूल बातें',
    excerpt: 'खातों के पाँच प्रकार, डेबिट-क्रेडिट का सुनहरा नियम और अकाउंटिंग इक्वेशन — पूरी बुनियाद एक जगह।',
    accent: 'sky',
    tags: ['बुनियाद', 'डेबिट-क्रेडिट', 'लेखांकन चक्र'],
  },
  {
    slug: 'digital-accounting-for-cooperatives',
    metaTitle: 'सहकारी समितियों को डिजिटल लेखांकन की ज़रूरत क्यों है? | SahakarLekha',
    metaDescription: 'मैनुअल बहीखाते की कमियाँ, ऑडिट की दिक्कतें और डिजिटल लेखांकन के लाभ — जानिए सहकारी समितियाँ अब भी डिजिटल अकाउंटिंग क्यों अपनाएँ।',
    date: '2026-06-23',
    category: 'डिजिटल लेखांकन',
    title: 'सहकारी समितियों को अभी भी डिजिटल लेखांकन की आवश्यकता क्यों है?',
    shortTitle: 'डिजिटल लेखांकन की आवश्यकता क्यों है?',
    excerpt: 'भरोसा, पारदर्शिता और अनुपालन अब कागज़ की पहुँच से बाहर हैं — जानिए मैनुअल से डिजिटल की ओर बढ़ना अभी क्यों ज़रूरी है।',
    accent: 'emerald',
    tags: ['डिजिटल लेखांकन', 'ऑडिट', 'पारदर्शिता'],
  },
];

// raw markdown for every post, keyed by "./<slug>.md"
const RAW = import.meta.glob('./*.md', { query: '?raw', import: 'default', eager: true }) as Record<string, string>;

export function loadBlogRaw(slug: string): string | null {
  return RAW['./' + slug + '.md'] ?? null;
}

/** Posts sorted newest-first (ALL posts, incl. future-scheduled). */
export const BLOG_ORDER: BlogPost[] = [...BLOG_POSTS].sort((a, b) => (a.date < b.date ? 1 : -1));

/** Today as YYYY-MM-DD (local). Recomputed at call time so scheduled posts
 *  auto-reveal in the browser once their date arrives — no rebuild needed. */
export function todayISO(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

/** A post is "live" once its publish date is today or earlier. */
export function isPublished(p: BlogPost): boolean {
  return p.date <= todayISO();
}

/** Published posts only, newest-first — the public reading order (index, prev/next). */
export function publishedOrder(): BlogPost[] {
  return BLOG_ORDER.filter(isPublished);
}

export function findPost(slug: string): BlogPost | null {
  return BLOG_POSTS.find((p) => p.slug === slug) ?? null;
}

/** Estimated reading time in minutes from the post's markdown (Hindi ~130 wpm). */
export function readingMinutes(slug: string): number {
  const raw = loadBlogRaw(slug);
  if (!raw) return 1;
  const body = raw.replace(/^#\s+.*(\r?\n)+/, '');
  const words = body.split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 130));
}

/** Up to `n` related posts (published only; same category first, then newest). */
export function relatedPosts(slug: string, n = 2): BlogPost[] {
  const self = findPost(slug);
  if (!self) return [];
  const others = publishedOrder().filter((p) => p.slug !== slug);
  const sameCat = others.filter((p) => p.category === self.category);
  const rest = others.filter((p) => p.category !== self.category);
  return [...sameCat, ...rest].slice(0, n);
}
