/**
 * Entry Cookbook — the REFERENCE layer: a searchable library of "to record X,
 * Dr/Cr this" cooperative accounting entries. Distinct from /guide (LEARN),
 * /blog (narrative) and /help (DO/task). Each entry is a typed Knowledge Object:
 * a real scenario + the journal posting (Dr/Cr lines) + narration + notes, with
 * an optional deep-link into the app and a "पूरा समझें" guide cross-link (L7).
 *
 * Account names mirror SahakarLekha's standard chart (Cash, 4101 Sales, 5101
 * Purchases, 3304 Loans & Advances, 5201 Salary, 3403 Closing Stock, etc.).
 * Slugs English; titles/body everyday Hinglish. IMPORTANT: this is reference
 * education, not a ruling — entries note when to verify with the auditor.
 */
export interface CookbookLine { account: string; type: 'Dr' | 'Cr'; note?: string }

export interface CookbookEntry {
  slug: string;
  metaTitle: string;
  metaDescription: string;
  category: string;
  title: string;
  intent: string;
  /** when this entry applies (1–2 lines) */
  scenario: string;
  /** the journal posting */
  lines: CookbookLine[];
  /** example narration to type in the voucher */
  narration: string;
  /** society types this is typical for (optional) */
  societyTypes?: string[];
  /** gotchas / variants */
  notes?: string[];
  /** optional: do it in the app */
  deepLink?: { route: string; label: string };
  /** related in-depth guide chapter (L7) */
  guideSlug?: string;
  related?: string[];
}

export const COOKBOOK_ENTRIES: CookbookEntry[] = [
  {
    slug: 'cash-sale',
    metaTitle: 'नकद बिक्री की एंट्री — Dr/Cr कैसे करें | SahakarLekha',
    metaDescription: 'नकद बिक्री का journal — Dr Cash, Cr Sales। GST लगने पर Output GST अलग। सहकारी समिति के लिए उदाहरण सहित।',
    category: 'खरीद-बिक्री',
    title: 'नकद बिक्री (Cash Sale)',
    intent: 'cash sale ki entry',
    scenario: 'समिति ने माल नकद में बेचा (पैसा तुरंत मिला)।',
    lines: [
      { account: 'Cash (नकद)', type: 'Dr' },
      { account: 'Sales / बिक्री (4101)', type: 'Cr' },
      { account: 'Output GST (अगर लागू)', type: 'Cr', note: 'सिर्फ़ तब जब बिल पर GST लिया हो' },
    ],
    narration: 'नकद बिक्री — बिल सं. ___',
    notes: [
      'App में Sale Management से करें तो यह voucher अपने-आप बनता है और स्टॉक भी घटता है।',
      'अलग-अलग category के माल पर अलग Sales खाता (per-item routing) रखें ताकि रिपोर्ट साफ़ रहे।',
    ],
    deepLink: { route: '/sales', label: 'App में बिक्री दर्ज करें' },
    guideSlug: 'sales-entries',
    related: ['credit-sale', 'cash-purchase'],
  },
  {
    slug: 'credit-sale',
    metaTitle: 'उधार बिक्री की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'उधार बिक्री का journal — Dr ग्राहक (Sundry Debtor), Cr Sales। बाद में वसूली पर Dr Cash, Cr ग्राहक।',
    category: 'खरीद-बिक्री',
    title: 'उधार बिक्री (Credit Sale)',
    intent: 'credit sale udhaar bikri entry',
    scenario: 'माल उधार बेचा — पैसा बाद में आना है।',
    lines: [
      { account: 'ग्राहक — Sundry Debtor (3303)', type: 'Dr' },
      { account: 'Sales / बिक्री (4101)', type: 'Cr' },
    ],
    narration: 'उधार बिक्री — ___ को, बिल सं. ___',
    notes: [
      'जब पैसा आए तब अलग receipt: Dr Cash/Bank, Cr वही ग्राहक खाता।',
      'हर ग्राहक का अलग sub-ledger रखें ताकि बकाया साफ़ दिखे।',
    ],
    deepLink: { route: '/sales', label: 'App में बिक्री दर्ज करें' },
    guideSlug: 'sales-entries',
    related: ['cash-sale', 'receive-payment'],
  },
  {
    slug: 'cash-purchase',
    metaTitle: 'नकद खरीद की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'नकद खरीद का journal — Dr Purchases, Cr Cash। GST input अलग खाते में।',
    category: 'खरीद-बिक्री',
    title: 'नकद खरीद (Cash Purchase)',
    intent: 'cash purchase kharid entry',
    scenario: 'समिति ने माल नकद में खरीदा।',
    lines: [
      { account: 'Purchases / खरीद (5101)', type: 'Dr' },
      { account: 'Input GST (अगर लागू)', type: 'Dr', note: 'GST बिल पर ही' },
      { account: 'Cash (नकद)', type: 'Cr' },
    ],
    narration: 'नकद खरीद — ___ से, बिल सं. ___',
    notes: ['App में Purchase Management से करें तो स्टॉक अपने-आप बढ़ता है।'],
    deepLink: { route: '/purchases', label: 'App में खरीद दर्ज करें' },
    guideSlug: 'purchase-entries',
    related: ['credit-purchase', 'cash-sale'],
  },
  {
    slug: 'credit-purchase',
    metaTitle: 'उधार खरीद की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'उधार खरीद का journal — Dr Purchases, Cr आपूर्तिकर्ता (Sundry Creditor)। भुगतान बाद में।',
    category: 'खरीद-बिक्री',
    title: 'उधार खरीद (Credit Purchase)',
    intent: 'credit purchase udhaar kharid entry',
    scenario: 'माल उधार खरीदा — भुगतान बाद में करना है।',
    lines: [
      { account: 'Purchases / खरीद (5101)', type: 'Dr' },
      { account: 'आपूर्तिकर्ता — Sundry Creditor (2101)', type: 'Cr' },
    ],
    narration: 'उधार खरीद — ___ से, बिल सं. ___',
    notes: ['भुगतान करते समय: Dr वही आपूर्तिकर्ता खाता, Cr Cash/Bank।'],
    deepLink: { route: '/purchases', label: 'App में खरीद दर्ज करें' },
    guideSlug: 'purchase-entries',
    related: ['cash-purchase', 'make-payment'],
  },
  {
    slug: 'member-share-capital',
    metaTitle: 'सदस्य शेयर पूँजी की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'सदस्य से शेयर पूँजी मिलने का journal — Dr Cash, Cr Share Capital। प्रवेश शुल्क अलग खाते में।',
    category: 'सदस्य व शेयर',
    title: 'शेयर पूँजी प्राप्त (Share Capital)',
    intent: 'share capital ki entry',
    scenario: 'नए/मौजूदा सदस्य ने शेयर पूँजी जमा की।',
    lines: [
      { account: 'Cash (नकद)', type: 'Dr' },
      { account: 'Share Capital / शेयर पूँजी', type: 'Cr' },
      { account: 'Admission Fee / प्रवेश शुल्क (अगर साथ लिया)', type: 'Cr', note: 'शेयर पूँजी से अलग आय है' },
    ],
    narration: 'शेयर पूँजी प्राप्त — सदस्य ___',
    notes: [
      'App में Members से सदस्य जोड़ें तो यह voucher अपने-आप बनता है — अलग से न बनाएँ (डबल एंट्री से बचें)।',
      'प्रवेश शुल्क आय है, शेयर पूँजी देनदारी/पूँजी — दोनों को कभी एक न मिलाएँ।',
    ],
    deepLink: { route: '/members', label: 'App में सदस्य जोड़ें' },
    guideSlug: 'member-management',
    related: ['dividend-declared', 'loan-disbursed'],
  },
  {
    slug: 'loan-disbursed',
    metaTitle: 'सदस्य ऋण वितरण की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'ऋण देने का journal — Dr Loans & Advances (संपत्ति), Cr Cash। ऋण खर्च नहीं, संपत्ति है।',
    category: 'लोन व ब्याज',
    title: 'ऋण वितरण (Loan Disbursed)',
    intent: 'loan disbursement entry',
    scenario: 'समिति ने सदस्य को ऋण दिया।',
    lines: [
      { account: 'Loans & Advances / ऋण (3304)', type: 'Dr', note: 'संपत्ति — वापस आना है' },
      { account: 'Cash / Bank', type: 'Cr' },
    ],
    narration: 'ऋण वितरण — सदस्य ___, ऋण सं. ___',
    notes: ['App में Loan Register से करें तो यह voucher अपने-आप बनता है।', 'ऋण को कभी खर्च न मानें — यह संपत्ति है।'],
    deepLink: { route: '/loan-register', label: 'App में ऋण दर्ज करें' },
    guideSlug: 'member-management',
    related: ['loan-interest-received', 'member-share-capital'],
  },
  {
    slug: 'loan-interest-received',
    metaTitle: 'ऋण ब्याज प्राप्ति की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'ऋण पर ब्याज मिलने का journal — Dr Cash, Cr Interest Income (आय)।',
    category: 'लोन व ब्याज',
    title: 'ऋण ब्याज प्राप्त (Loan Interest)',
    intent: 'loan interest received entry',
    scenario: 'सदस्य ने ऋण पर ब्याज चुकाया।',
    lines: [
      { account: 'Cash / Bank', type: 'Dr' },
      { account: 'Interest Income / ब्याज आय', type: 'Cr' },
    ],
    narration: 'ऋण ब्याज प्राप्त — सदस्य ___, ऋण सं. ___',
    notes: ['मूल वसूली (principal) अलग होती है: Dr Cash, Cr Loans & Advances। ब्याज को principal से न मिलाएँ।'],
    guideSlug: 'member-management',
    related: ['loan-disbursed'],
  },
  {
    slug: 'salary-paid',
    metaTitle: 'वेतन भुगतान की एंट्री — कटौती सहित Dr/Cr | SahakarLekha',
    metaDescription: 'वेतन का journal — Dr Salary (सकल), Cr Cash/Bank (शुद्ध) और Cr EPF/ESI/TDS payable (कटौती)।',
    category: 'वेतन',
    title: 'वेतन भुगतान (Salary, कटौती सहित)',
    intent: 'salary payment entry with deductions',
    scenario: 'कर्मचारी को वेतन दिया, जिसमें EPF/TDS आदि कटौती है।',
    lines: [
      { account: 'Salary / वेतन (5201)', type: 'Dr', note: 'सकल (gross) वेतन' },
      { account: 'Cash / Bank', type: 'Cr', note: 'शुद्ध (net) — जो हाथ में दिया' },
      { account: 'EPF/ESI/TDS Payable / देय कटौती', type: 'Cr', note: 'जो काटा, बाद में जमा होगा' },
    ],
    narration: 'वेतन भुगतान — ___ माह, कर्मचारी ___',
    notes: [
      'कटौती (EPF/TDS) देनदारी है — जब विभाग में जमा करें तब: Dr वही Payable, Cr Cash/Bank।',
      'App में Salary Management से slip बनाएँ तो यह सब अपने-आप होता है।',
    ],
    deepLink: { route: '/salary', label: 'App में वेतन दर्ज करें' },
    guideSlug: 'salary-management',
    related: ['bank-charges'],
  },
  {
    slug: 'bank-charges',
    metaTitle: 'बैंक प्रभार व ब्याज की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'बैंक प्रभार: Dr Bank Charges, Cr Bank। बैंक ब्याज: Dr Bank, Cr Interest Income। BRS में अक्सर छूटते हैं।',
    category: 'बैंक',
    title: 'बैंक प्रभार / बैंक ब्याज',
    intent: 'bank charges interest entry',
    scenario: 'बैंक ने प्रभार काटा या ब्याज जमा किया (स्टेटमेंट में दिखा)।',
    lines: [
      { account: 'Bank Charges / बैंक प्रभार (व्यय)', type: 'Dr', note: 'प्रभार की स्थिति में' },
      { account: 'Bank', type: 'Cr', note: 'प्रभार की स्थिति में' },
    ],
    narration: 'बैंक प्रभार — स्टेटमेंट तारीख ___',
    notes: [
      'बैंक ब्याज जमा हो तो उल्टा: Dr Bank, Cr Interest Income (आय)।',
      'ये entries Bank Reconciliation में सबसे आम छूट हैं — स्टेटमेंट से ज़रूर मिलाएँ।',
    ],
    deepLink: { route: '/bank-reconciliation', label: 'App में BRS करें' },
    guideSlug: 'daybook-and-ledger',
    related: ['salary-paid'],
  },
  {
    slug: 'depreciation',
    metaTitle: 'डेप्रिसिएशन की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'घिसाई का journal — Dr Depreciation (व्यय), Cr Accumulated Depreciation। साल के अंत में।',
    category: 'साल-अंत',
    title: 'डेप्रिसिएशन (Depreciation)',
    intent: 'depreciation ki entry',
    scenario: 'साल के अंत में संपत्ति पर घिसाई लगानी है।',
    lines: [
      { account: 'Depreciation / डेप्रिसिएशन (व्यय)', type: 'Dr' },
      { account: 'Accumulated Depreciation / संचित घिसाई', type: 'Cr' },
    ],
    narration: 'डेप्रिसिएशन — वर्ष ___',
    notes: ['App में Depreciation Schedule से "Post" करें तो यह सबके लिए अपने-आप बनता है (SLM/WDV)।'],
    deepLink: { route: '/depreciation-schedule', label: 'App में डेप्रिसिएशन पोस्ट करें' },
    guideSlug: 'depreciation',
    related: ['closing-stock'],
  },
  {
    slug: 'closing-stock',
    metaTitle: 'क्लोज़िंग स्टॉक की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'साल के अंत क्लोज़िंग स्टॉक: Dr Closing Stock (संपत्ति 3403), Cr Trading/Purchases। डबल-काउंट से बचें।',
    category: 'साल-अंत',
    title: 'क्लोज़िंग स्टॉक (Closing Stock)',
    intent: 'closing stock entry',
    scenario: 'साल के अंत बचा हुआ माल books में लाना है।',
    lines: [
      { account: 'Closing Stock / समापन स्टॉक (3403)', type: 'Dr', note: 'संपत्ति' },
      { account: 'Closing Stock A/c — Trading (5150)', type: 'Cr' },
    ],
    narration: 'क्लोज़िंग स्टॉक — वर्ष ___',
    notes: [
      'App में Year-End / Closing Stock Report से "Post" करें तो यह सही मूल्य (वेटेड एवरेज) पर अपने-आप बनता है।',
      'क्लोज़िंग स्टॉक की गणना एक ही जगह से रखें — Trading और Balance Sheet दोनों में डबल-काउंट न हो।',
    ],
    deepLink: { route: '/closing-stock-report', label: 'App में क्लोज़िंग स्टॉक पोस्ट करें' },
    guideSlug: 'trading-account',
    related: ['depreciation', 'profit-distribution-reserve'],
  },
  {
    slug: 'hafed-procurement-commission',
    metaTitle: 'HAFED/MSP खरीद कमीशन की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'विपणन समिति का MSP खरीद कमीशन: Dr HAFED/एजेंसी प्राप्य, Cr Commission Income। बारदाना व सूखत अलग।',
    category: 'HAFED / MSP',
    title: 'HAFED/MSP खरीद कमीशन',
    intent: 'hafed msp commission entry',
    scenario: 'विपणन समिति ने HAFED/एजेंसी के लिए MSP पर खरीद की और कमीशन कमाया।',
    lines: [
      { account: 'HAFED / एजेंसी प्राप्य (Receivable)', type: 'Dr' },
      { account: 'Commission Income / कमीशन आय', type: 'Cr' },
    ],
    narration: 'MSP खरीद कमीशन — सीज़न ___',
    societyTypes: ['विपणन / Marketing', 'PACS'],
    notes: [
      'बारदाना (gunny) व सूखत (driage) का हिसाब अलग खातों में रखें — कमीशन में न मिलाएँ।',
      'किसान भुगतान व ऋण-कटौती अलग entries हैं। राज्य/एजेंसी के नियम बदल सकते हैं — अपने RCS/ऑडिटर से पुष्टि करें।',
    ],
    guideSlug: 'msp-procurement-entries',
    related: ['cash-purchase', 'credit-sale'],
  },
  {
    slug: 'profit-distribution-reserve',
    metaTitle: 'लाभ बँटवारा व रिज़र्व फंड की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'नेट प्रॉफ़िट से रिज़र्व फंड व डिविडेंड: Dr Profit Appropriation, Cr Reserve Fund / Dividend Payable।',
    category: 'साल-अंत',
    title: 'लाभ बँटवारा — रिज़र्व व डिविडेंड',
    intent: 'profit distribution reserve fund dividend entry',
    scenario: 'साल का नेट प्रॉफ़िट बाँटना है — पहले रिज़र्व फंड, फिर डिविडेंड/बोनस।',
    lines: [
      { account: 'Profit & Loss Appropriation / लाभ-बँटवारा', type: 'Dr' },
      { account: 'Reserve Fund / रिज़र्व फंड (25%)', type: 'Cr', note: 'पहले यही' },
      { account: 'Dividend Payable / देय डिविडेंड', type: 'Cr', note: 'मंज़ूरी के बाद' },
    ],
    narration: 'लाभ बँटवारा — वर्ष ___',
    notes: [
      'क्रम मायने रखता है: पहले कानूनी रिज़र्व फंड (आमतौर पर 25%), फिर बाँटने लायक मुनाफ़ा।',
      'डिविडेंड दर व बँटवारा आम सभा/बायलॉज़ व राज्य नियमों से तय होता है — अपने RCS/ऑडिटर से पुष्टि करें।',
    ],
    deepLink: { route: '/profit-distribution', label: 'App में लाभ बँटवारा करें' },
    guideSlug: 'profit-distribution',
    related: ['member-share-capital', 'closing-stock'],
  },
  {
    slug: 'receive-payment',
    metaTitle: 'ग्राहक से वसूली की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'उधार बिक्री का पैसा ग्राहक से मिलने का journal — Dr Cash/Bank, Cr ग्राहक (Sundry Debtor)। बिल-वार निपटान सहित।',
    category: 'भुगतान व वसूली',
    title: 'ग्राहक से वसूली (Receive Payment)',
    intent: 'customer se vasooli receive payment entry',
    scenario: 'पहले उधार बेचे माल का पैसा ग्राहक से अब मिला।',
    lines: [
      { account: 'Cash / Bank', type: 'Dr' },
      { account: 'ग्राहक — Sundry Debtor (3303)', type: 'Cr' },
    ],
    narration: 'वसूली — ग्राहक ___, बिल सं. ___ के विरुद्ध',
    notes: ['App में Receive Payment से करें तो किस बिल के विरुद्ध है यह bill-wise सेट कर सकते हैं।'],
    deepLink: { route: '/receive-payment', label: 'App में वसूली दर्ज करें' },
    guideSlug: 'bill-wise-settlement',
    related: ['credit-sale', 'make-payment'],
  },
  {
    slug: 'make-payment',
    metaTitle: 'आपूर्तिकर्ता को भुगतान की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'उधार खरीद का भुगतान आपूर्तिकर्ता को करने का journal — Dr आपूर्तिकर्ता (Sundry Creditor), Cr Cash/Bank।',
    category: 'भुगतान व वसूली',
    title: 'आपूर्तिकर्ता को भुगतान (Make Payment)',
    intent: 'supplier ko bhugtan make payment entry',
    scenario: 'पहले उधार खरीदे माल का भुगतान आपूर्तिकर्ता को अब किया।',
    lines: [
      { account: 'आपूर्तिकर्ता — Sundry Creditor (2101)', type: 'Dr' },
      { account: 'Cash / Bank', type: 'Cr' },
    ],
    narration: 'भुगतान — आपूर्तिकर्ता ___, बिल सं. ___ के विरुद्ध',
    notes: ['App में Make Payment से bill-wise निपटान करें ताकि बकाया सही घटे।'],
    deepLink: { route: '/make-payment', label: 'App में भुगतान दर्ज करें' },
    guideSlug: 'bill-wise-settlement',
    related: ['credit-purchase', 'receive-payment'],
  },
  {
    slug: 'cash-deposit-to-bank',
    metaTitle: 'नकद बैंक में जमा (Contra) की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'नकद बैंक में जमा करने का contra journal — Dr Bank, Cr Cash। यह आय-व्यय नहीं, सिर्फ़ जगह बदली।',
    category: 'बैंक',
    title: 'नकद बैंक में जमा (Contra)',
    intent: 'cash bank me jama contra entry',
    scenario: 'हाथ का नकद बैंक खाते में जमा किया।',
    lines: [
      { account: 'Bank', type: 'Dr' },
      { account: 'Cash (नकद)', type: 'Cr' },
    ],
    narration: 'नकद बैंक में जमा — तारीख ___',
    notes: ['यह Contra voucher है — न आय है न व्यय, सिर्फ़ नकद से बैंक में पैसा गया। Receipts & Payments में यह नहीं गिना जाता।'],
    deepLink: { route: '/vouchers', label: 'App में Contra voucher करें' },
    guideSlug: 'voucher-types',
    related: ['bank-withdrawal-to-cash', 'cash-sale'],
  },
  {
    slug: 'bank-withdrawal-to-cash',
    metaTitle: 'बैंक से नकद निकासी (Contra) की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'बैंक से नकद निकालने का contra journal — Dr Cash, Cr Bank।',
    category: 'बैंक',
    title: 'बैंक से नकद निकासी (Contra)',
    intent: 'bank se nakad nikasi contra entry',
    scenario: 'बैंक खाते से नकद निकाला (हाथ में लिया)।',
    lines: [
      { account: 'Cash (नकद)', type: 'Dr' },
      { account: 'Bank', type: 'Cr' },
    ],
    narration: 'बैंक से नकद निकासी — तारीख ___',
    notes: ['Contra voucher — सिर्फ़ बैंक से नकद में जगह बदली, कोई आय/व्यय नहीं।'],
    deepLink: { route: '/vouchers', label: 'App में Contra voucher करें' },
    guideSlug: 'voucher-types',
    related: ['cash-deposit-to-bank'],
  },
  {
    slug: 'loan-recovery',
    metaTitle: 'ऋण मूल वसूली की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'ऋण की मूल राशि (principal) वापस आने का journal — Dr Cash/Bank, Cr Loans & Advances। ब्याज अलग।',
    category: 'लोन व ब्याज',
    title: 'ऋण मूल वसूली (Loan Recovery)',
    intent: 'loan recovery principal vasooli entry',
    scenario: 'सदस्य ने ऋण की मूल राशि लौटाई।',
    lines: [
      { account: 'Cash / Bank', type: 'Dr' },
      { account: 'Loans & Advances / ऋण (3304)', type: 'Cr', note: 'संपत्ति घटी' },
    ],
    narration: 'ऋण मूल वसूली — सदस्य ___, ऋण सं. ___',
    notes: ['ब्याज की वसूली अलग entry है (Dr Cash, Cr Interest Income) — मूल व ब्याज को कभी एक न मिलाएँ।'],
    deepLink: { route: '/loan-register', label: 'App में ऋण देखें' },
    guideSlug: 'member-management',
    related: ['loan-disbursed', 'loan-interest-received'],
  },
  {
    slug: 'asset-purchase',
    metaTitle: 'संपत्ति खरीद की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'फर्नीचर/कंप्यूटर आदि संपत्ति खरीदने का journal — Dr Asset (संपत्ति), Cr Cash/Bank। यह खर्च नहीं।',
    category: 'संपत्ति',
    title: 'संपत्ति खरीद (Asset Purchase)',
    intent: 'asset purchase sampatti kharid entry',
    scenario: 'समिति ने स्थायी संपत्ति (फर्नीचर/कंप्यूटर/वाहन) खरीदी।',
    lines: [
      { account: 'सम्बंधित संपत्ति — Fixed Asset', type: 'Dr', note: 'संपत्ति, खर्च नहीं' },
      { account: 'Cash / Bank', type: 'Cr' },
    ],
    narration: 'संपत्ति खरीद — ___, बिल सं. ___',
    notes: [
      'संपत्ति को खर्च न मानें — यह बैलेंस शीट में रहती है, और हर साल इस पर डेप्रिसिएशन लगता है।',
      'App में Asset Register में जोड़ें ताकि डेप्रिसिएशन अपने-आप गणना हो।',
    ],
    deepLink: { route: '/asset-register', label: 'App में संपत्ति जोड़ें' },
    guideSlug: 'depreciation',
    related: ['depreciation', 'cash-purchase'],
  },
  {
    slug: 'rent-paid',
    metaTitle: 'किराया भुगतान की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'किराया देने का journal — Dr Rent (व्यय), Cr Cash/Bank। किराये पर TDS लागू हो तो अलग कटौती।',
    category: 'खर्च',
    title: 'किराया भुगतान (Rent Paid)',
    intent: 'rent paid kiraya entry',
    scenario: 'समिति ने दफ़्तर/गोदाम का किराया दिया।',
    lines: [
      { account: 'Rent / किराया (व्यय)', type: 'Dr' },
      { account: 'Cash / Bank', type: 'Cr' },
    ],
    narration: 'किराया भुगतान — ___ माह',
    notes: ['सीमा से ऊपर किराये पर TDS लागू हो सकता है — तब Cr में TDS Payable अलग। नियम के लिए ऑडिटर से पुष्टि करें।'],
    deepLink: { route: '/vouchers', label: 'App में payment voucher करें' },
    guideSlug: 'expense-dictionary',
    related: ['expense-paid', 'salary-paid'],
  },
  {
    slug: 'expense-paid',
    metaTitle: 'सामान्य खर्च की एंट्री — बिजली/स्टेशनरी/मरम्मत | SahakarLekha',
    metaDescription: 'रोज़मर्रा के खर्च का journal — Dr सम्बंधित व्यय खाता, Cr Cash/Bank। सही व्यय खाते में डालें।',
    category: 'खर्च',
    title: 'सामान्य खर्च (Expense Paid)',
    intent: 'expense paid kharch bijli stationery entry',
    scenario: 'बिजली, स्टेशनरी, मरम्मत, यात्रा आदि कोई खर्च नकद/बैंक से किया।',
    lines: [
      { account: 'सम्बंधित व्यय (जैसे बिजली/स्टेशनरी)', type: 'Dr' },
      { account: 'Cash / Bank', type: 'Cr' },
    ],
    narration: 'खर्च — ___ (विवरण)',
    notes: ['हर खर्च को उसके सही व्यय खाते में डालें — सब "विविध खर्च" में न डालें, वरना रिपोर्ट बेकार हो जाती है।'],
    deepLink: { route: '/vouchers', label: 'App में payment voucher करें' },
    guideSlug: 'expense-dictionary',
    related: ['rent-paid'],
  },
  {
    slug: 'share-refund-on-exit',
    metaTitle: 'सदस्य निकासी पर शेयर वापसी की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'सदस्य के समिति छोड़ने पर शेयर पूँजी लौटाने का journal — Dr Share Capital, Cr Cash/Bank।',
    category: 'सदस्य व शेयर',
    title: 'शेयर वापसी — सदस्य निकासी',
    intent: 'share refund member exit nikasi entry',
    scenario: 'सदस्य ने समिति छोड़ी और उसकी शेयर पूँजी लौटानी है।',
    lines: [
      { account: 'Share Capital / शेयर पूँजी', type: 'Dr', note: 'पूँजी घटी' },
      { account: 'Cash / Bank', type: 'Cr' },
    ],
    narration: 'शेयर वापसी — सदस्य ___ की निकासी',
    notes: ['शेयर वापसी बायलॉज़ व राज्य नियमों के अधीन है (कई जगह सीमा/शर्तें होती हैं) — अपने RCS/ऑडिटर से पुष्टि करें।'],
    deepLink: { route: '/members', label: 'App में सदस्य देखें' },
    guideSlug: 'member-management',
    related: ['member-share-capital', 'profit-distribution-reserve'],
  },
  {
    slug: 'fixed-deposit',
    metaTitle: 'फिक्स्ड डिपॉज़िट (FD) की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'बैंक में FD करने का journal — Dr Fixed Deposit (निवेश/संपत्ति), Cr Bank। ब्याज मिलने पर आय।',
    category: 'बैंक',
    title: 'फिक्स्ड डिपॉज़िट (FD)',
    intent: 'fixed deposit fd investment entry',
    scenario: 'समिति ने बचत राशि बैंक में FD के रूप में रखी।',
    lines: [
      { account: 'Fixed Deposit / सावधि जमा (निवेश)', type: 'Dr', note: 'संपत्ति' },
      { account: 'Bank', type: 'Cr' },
    ],
    narration: 'FD — बैंक ___, FD सं. ___',
    notes: ['FD पर ब्याज मिलने पर अलग entry: Dr Bank/FD, Cr Interest Income। FD पर भी TDS कट सकता है।'],
    deepLink: { route: '/vouchers', label: 'App में voucher करें' },
    related: ['cash-deposit-to-bank'],
  },
  {
    slug: 'tds-deposit',
    metaTitle: 'TDS सरकार को जमा की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'काटा हुआ TDS सरकार को जमा करने का journal — Dr TDS Payable, Cr Bank। तिमाही में 26Q भी फाइल करें।',
    category: 'अनुपालन (Compliance)',
    title: 'TDS जमा (Deposit)',
    intent: 'tds deposit jama entry',
    scenario: 'पहले काटा गया TDS अब सरकार को जमा किया।',
    lines: [
      { account: 'TDS Payable / देय TDS', type: 'Dr', note: 'देनदारी घटी' },
      { account: 'Bank', type: 'Cr' },
    ],
    narration: 'TDS जमा — तिमाही ___, चालान सं. ___',
    notes: ['जमा के बाद तिमाही में 26Q रिटर्न भी फाइल करें। App में TDS Register से 26Q export मिलता है।'],
    deepLink: { route: '/tds-register', label: 'App में TDS Register खोलें' },
    guideSlug: 'tds-and-26q',
    related: ['salary-paid', 'epf-esi-deposit'],
  },
  {
    slug: 'epf-esi-deposit',
    metaTitle: 'EPF/ESI जमा की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'वेतन से काटे EPF/ESI को विभाग में जमा करने का journal — Dr EPF/ESI Payable, Cr Bank।',
    category: 'अनुपालन (Compliance)',
    title: 'EPF/ESI जमा',
    intent: 'epf esi pf deposit jama entry',
    scenario: 'वेतन से काटी EPF/ESI कटौती अब विभाग में जमा की।',
    lines: [
      { account: 'EPF/ESI Payable / देय कटौती', type: 'Dr' },
      { account: 'Bank', type: 'Cr' },
    ],
    narration: 'EPF/ESI जमा — ___ माह',
    notes: ['नियोक्ता का अंशदान भी जोड़ें तो उतना अतिरिक्त Dr व्यय/Payable के रूप में लगेगा।'],
    deepLink: { route: '/vouchers', label: 'App में payment voucher करें' },
    guideSlug: 'salary-management',
    related: ['salary-paid', 'tds-deposit'],
  },
  {
    slug: 'gst-payment',
    metaTitle: 'GST सरकार को जमा की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'महीने का net GST जमा — Dr Output GST, Cr Input GST और Cr Bank (बाकी देय राशि)।',
    category: 'अनुपालन (Compliance)',
    title: 'GST जमा (Payment)',
    intent: 'gst payment jama entry',
    scenario: 'महीने का देय GST (Output घटा Input) सरकार को जमा किया।',
    lines: [
      { account: 'Output GST / देय GST', type: 'Dr', note: 'देनदारी घटी' },
      { account: 'Input GST / जमा GST', type: 'Cr', note: 'इनपुट क्रेडिट घटी' },
      { account: 'Bank', type: 'Cr', note: 'बाकी net राशि' },
    ],
    narration: 'GST जमा — ___ माह',
    notes: ['देय = Output GST घटा Input GST। App का GST Summary यह net अपने-आप दिखाता है।'],
    deepLink: { route: '/gst-summary', label: 'App में GST Summary देखें' },
    guideSlug: 'gst-management',
    related: ['cash-sale', 'tds-deposit'],
  },
  {
    slug: 'sales-return',
    metaTitle: 'बिक्री वापसी की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'ग्राहक द्वारा माल लौटाने का journal — Dr Sales Return, Cr ग्राहक/Cash। स्टॉक वापस बढ़ता है।',
    category: 'खरीद-बिक्री',
    title: 'बिक्री वापसी (Sales Return)',
    intent: 'sales return bikri wapsi entry',
    scenario: 'ग्राहक ने बेचा हुआ माल लौटा दिया।',
    lines: [
      { account: 'Sales Return / बिक्री वापसी', type: 'Dr', note: 'बिक्री घटी' },
      { account: 'ग्राहक — Sundry Debtor / Cash', type: 'Cr' },
    ],
    narration: 'बिक्री वापसी — ग्राहक ___, मूल बिल सं. ___',
    notes: ['लौटा माल वापस स्टॉक में बढ़ता है। GST बिल था तो उतना Output GST भी उलटेगा।'],
    deepLink: { route: '/sales', label: 'App में बिक्री देखें' },
    guideSlug: 'sales-entries',
    related: ['cash-sale', 'purchase-return'],
  },
  {
    slug: 'purchase-return',
    metaTitle: 'खरीद वापसी की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'आपूर्तिकर्ता को माल लौटाने का journal — Dr आपूर्तिकर्ता/Cash, Cr Purchase Return।',
    category: 'खरीद-बिक्री',
    title: 'खरीद वापसी (Purchase Return)',
    intent: 'purchase return kharid wapsi entry',
    scenario: 'खरीदा हुआ माल आपूर्तिकर्ता को लौटा दिया।',
    lines: [
      { account: 'आपूर्तिकर्ता — Sundry Creditor / Cash', type: 'Dr' },
      { account: 'Purchase Return / खरीद वापसी', type: 'Cr', note: 'खरीद घटी' },
    ],
    narration: 'खरीद वापसी — आपूर्तिकर्ता ___, मूल बिल सं. ___',
    notes: ['लौटाया माल स्टॉक से घटता है। Input GST लिया था तो उतना उलटेगा।'],
    deepLink: { route: '/purchases', label: 'App में खरीद देखें' },
    guideSlug: 'purchase-entries',
    related: ['cash-purchase', 'sales-return'],
  },
  {
    slug: 'discount-allowed',
    metaTitle: 'छूट दी (Discount Allowed) की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'ग्राहक को नकद छूट देने का journal — Dr Discount Allowed (व्यय), Cr ग्राहक।',
    category: 'खरीद-बिक्री',
    title: 'छूट दी (Discount Allowed)',
    intent: 'discount allowed chhoot entry',
    scenario: 'जल्दी भुगतान पर ग्राहक को नकद छूट दी।',
    lines: [
      { account: 'Discount Allowed / दी गई छूट (व्यय)', type: 'Dr' },
      { account: 'ग्राहक — Sundry Debtor', type: 'Cr' },
    ],
    narration: 'नकद छूट — ग्राहक ___',
    notes: ['व्यापारिक (trade) छूट बिल पर ही घटा देते हैं, अलग एंट्री नहीं — सिर्फ़ नकद (cash) छूट की यह एंट्री होती है।'],
    guideSlug: 'sales-entries',
    related: ['receive-payment'],
  },
  {
    slug: 'member-deposit',
    metaTitle: 'सदस्य जमा/बचत की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'सदस्य से बचत/सावधि जमा लेने का journal — Dr Cash, Cr Member Deposit (देनदारी)। यह शेयर पूँजी नहीं।',
    category: 'सदस्य व शेयर',
    title: 'सदस्य जमा/बचत (Member Deposit)',
    intent: 'member deposit bachat jama entry',
    scenario: 'सदस्य ने बचत या सावधि जमा (RD/FD) समिति में रखी।',
    lines: [
      { account: 'Cash / Bank', type: 'Dr' },
      { account: 'Member Deposit / सदस्य जमा (देनदारी)', type: 'Cr', note: 'वापस होने वाली जमा' },
    ],
    narration: 'सदस्य जमा — सदस्य ___, जमा प्रकार ___',
    notes: ['यह शेयर पूँजी से अलग है — जमा वापस होती है, उस पर समिति ब्याज देती है (व्यय)।'],
    guideSlug: 'member-management',
    related: ['member-share-capital', 'fixed-deposit'],
  },
  {
    slug: 'dividend-paid',
    metaTitle: 'डिविडेंड भुगतान की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'घोषित डिविडेंड सदस्यों को देने का journal — Dr Dividend Payable, Cr Cash/Bank।',
    category: 'सदस्य व शेयर',
    title: 'डिविडेंड भुगतान (Dividend Paid)',
    intent: 'dividend payment bhugtan entry',
    scenario: 'आम सभा में घोषित डिविडेंड अब सदस्यों को दिया।',
    lines: [
      { account: 'Dividend Payable / देय डिविडेंड', type: 'Dr', note: 'पहले बँटवारे में बनी देनदारी' },
      { account: 'Cash / Bank', type: 'Cr' },
    ],
    narration: 'डिविडेंड भुगतान — वर्ष ___',
    notes: ['डिविडेंड पहले लाभ-बँटवारे में घोषित (Cr Dividend Payable) होता है, फिर यहाँ भुगतान।'],
    guideSlug: 'profit-distribution',
    related: ['profit-distribution-reserve', 'patronage-bonus'],
  },
  {
    slug: 'patronage-bonus',
    metaTitle: 'व्यवहार बोनस (Patronage) की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'सदस्य के व्यवहार के अनुपात में बोनस का journal — Dr लाभ-बँटवारा, Cr Bonus Payable।',
    category: 'सदस्य व शेयर',
    title: 'व्यवहार बोनस (Patronage Bonus)',
    intent: 'patronage bonus vyavhar bonus entry',
    scenario: 'मुनाफ़े में से सदस्यों को उनके व्यवहार (खरीद/बिक्री) के अनुपात में बोनस।',
    lines: [
      { account: 'Profit & Loss Appropriation / लाभ-बँटवारा', type: 'Dr' },
      { account: 'Patronage Bonus Payable / देय बोनस', type: 'Cr' },
    ],
    narration: 'व्यवहार बोनस — वर्ष ___',
    notes: ['डिविडेंड शेयर पूँजी पर मिलता है; व्यवहार बोनस सदस्य के लेन-देन के अनुपात में — दोनों अलग हैं।'],
    guideSlug: 'profit-distribution',
    related: ['dividend-paid', 'profit-distribution-reserve'],
  },
  {
    slug: 'outstanding-expense',
    metaTitle: 'बकाया खर्च (Outstanding Expense) की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'साल के अंत बिना चुकाए खर्च का journal — Dr Expense, Cr Outstanding Expense (देनदारी)।',
    category: 'साल-अंत',
    title: 'बकाया खर्च (Outstanding Expense)',
    intent: 'outstanding expense bakaya kharch entry',
    scenario: 'खर्च इसी साल का है पर साल के अंत तक चुकाया नहीं (जैसे आख़िरी महीने का बिजली बिल)।',
    lines: [
      { account: 'सम्बंधित व्यय (जैसे बिजली)', type: 'Dr', note: 'इसी साल का खर्च' },
      { account: 'Outstanding Expense / बकाया खर्च (देनदारी)', type: 'Cr' },
    ],
    narration: 'बकाया खर्च — ___, वर्ष ___',
    notes: ['यह accrual है — खर्च उसी साल में आना चाहिए जिस साल हुआ, चाहे भुगतान अगले साल हो। अगले साल भुगतान पर: Dr Outstanding Expense, Cr Cash/Bank।'],
    guideSlug: 'year-end-and-fy-lock',
    related: ['prepaid-expense', 'accrued-income'],
  },
  {
    slug: 'prepaid-expense',
    metaTitle: 'अग्रिम खर्च (Prepaid Expense) की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'अगले साल का खर्च अभी चुका दिया — Dr Prepaid Expense (संपत्ति), Cr Cash/Bank।',
    category: 'साल-अंत',
    title: 'अग्रिम खर्च (Prepaid Expense)',
    intent: 'prepaid expense agrim kharch entry',
    scenario: 'भुगतान अभी किया पर खर्च अगले साल का है (जैसे साल भर का बीमा अग्रिम)।',
    lines: [
      { account: 'Prepaid Expense / अग्रिम खर्च (संपत्ति)', type: 'Dr' },
      { account: 'Cash / Bank', type: 'Cr' },
    ],
    narration: 'अग्रिम खर्च — ___, अवधि ___',
    notes: ['इस साल का जितना हिस्सा है उतना ही खर्च माना जाता है; बाकी संपत्ति (prepaid) रहती है।'],
    guideSlug: 'year-end-and-fy-lock',
    related: ['outstanding-expense'],
  },
  {
    slug: 'accrued-income',
    metaTitle: 'उपार्जित आय (Accrued Income) की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'कमाई पर अभी मिली नहीं आय का journal — Dr Accrued Income (संपत्ति), Cr Income।',
    category: 'साल-अंत',
    title: 'उपार्जित आय (Accrued Income)',
    intent: 'accrued income uparjit aay entry',
    scenario: 'आय इसी साल बनी पर साल के अंत तक मिली नहीं (जैसे FD का देय ब्याज)।',
    lines: [
      { account: 'Accrued Income / उपार्जित आय (संपत्ति)', type: 'Dr' },
      { account: 'सम्बंधित आय (जैसे ब्याज आय)', type: 'Cr', note: 'इसी साल की आय' },
    ],
    narration: 'उपार्जित आय — ___, वर्ष ___',
    notes: ['accrual — आय उसी साल में जिसमें कमाई हुई। मिलने पर: Dr Cash/Bank, Cr Accrued Income।'],
    guideSlug: 'year-end-and-fy-lock',
    related: ['outstanding-expense', 'loan-interest-received'],
  },
  {
    slug: 'audit-fee',
    metaTitle: 'ऑडिट शुल्क की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'ऑडिट शुल्क का प्रावधान/भुगतान — Dr Audit Fee (व्यय), Cr Audit Fee Payable / Cash।',
    category: 'साल-अंत',
    title: 'ऑडिट शुल्क (Audit Fee)',
    intent: 'audit fee shulk entry',
    scenario: 'साल के अंत ऑडिट शुल्क का प्रावधान करना/चुकाना है।',
    lines: [
      { account: 'Audit Fee / ऑडिट शुल्क (व्यय)', type: 'Dr' },
      { account: 'Audit Fee Payable / Cash / Bank', type: 'Cr' },
    ],
    narration: 'ऑडिट शुल्क — वर्ष ___',
    notes: ['ऑडिट शुल्क पर भी TDS लागू हो सकता है (professional fee) — तब Cr में TDS Payable अलग।'],
    guideSlug: 'expense-dictionary',
    related: ['expense-paid', 'audit-report'],
  },
  {
    slug: 'reserve-fund-investment',
    metaTitle: 'रिज़र्व फंड निवेश की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'कानूनी रिज़र्व फंड का निवेश — Dr Reserve Fund Investment (संपत्ति), Cr Bank।',
    category: 'साल-अंत',
    title: 'रिज़र्व फंड निवेश',
    intent: 'reserve fund investment nivesh entry',
    scenario: 'रिज़र्व फंड का एक हिस्सा कानूनन निवेश करना है।',
    lines: [
      { account: 'Reserve Fund Investment / रिज़र्व फंड निवेश (संपत्ति)', type: 'Dr' },
      { account: 'Bank', type: 'Cr' },
    ],
    narration: 'रिज़र्व फंड निवेश — वर्ष ___',
    notes: ['कई राज्यों में रिज़र्व फंड का तय हिस्सा निवेश करना अनिवार्य है — दर व माध्यम अपने राज्य Act/RCS से पुष्टि करें।'],
    guideSlug: 'statutory-returns',
    related: ['profit-distribution-reserve', 'fixed-deposit'],
  },
  {
    slug: 'loan-write-off',
    metaTitle: 'NPA/डूबत ऋण बट्टे खाते की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'वसूली-अयोग्य ऋण का प्रावधान/बट्टा — Dr Bad Debt/Provision (व्यय), Cr Loans & Advances।',
    category: 'लोन व ब्याज',
    title: 'डूबत ऋण / NPA प्रावधान',
    intent: 'loan write off npa bad debt provision entry',
    scenario: 'कोई ऋण वसूली-अयोग्य (NPA) है, उस पर प्रावधान/बट्टा करना है।',
    lines: [
      { account: 'Bad Debt / Provision (व्यय)', type: 'Dr' },
      { account: 'Loans & Advances / Provision (3304)', type: 'Cr' },
    ],
    narration: 'डूबत ऋण प्रावधान — ऋण सं. ___',
    notes: ['बट्टे खाते डालने से पहले बोर्ड व ऑडिटर की मंज़ूरी ज़रूरी है — मनमाने ढंग से न करें। राज्य नियमों से पुष्टि करें।'],
    guideSlug: 'financial-ratios-and-lifecycle',
    related: ['loan-disbursed', 'loan-recovery'],
  },
  {
    slug: 'asset-sale',
    metaTitle: 'संपत्ति बिक्री की एंट्री — लाभ/हानि सहित Dr/Cr | SahakarLekha',
    metaDescription: 'पुरानी संपत्ति बेचने का journal — Dr Bank, Cr Asset (बही मूल्य), अंतर = लाभ (Cr) या हानि (Dr)।',
    category: 'संपत्ति',
    title: 'संपत्ति बिक्री (Asset Sale)',
    intent: 'asset sale sampatti bikri disposal entry',
    scenario: 'समिति ने पुरानी संपत्ति (वाहन/फर्नीचर) बेची।',
    lines: [
      { account: 'Bank / Cash', type: 'Dr', note: 'मिली राशि' },
      { account: 'सम्बंधित संपत्ति — Asset', type: 'Cr', note: 'बही मूल्य = लागत घटा संचित डेप्रिसिएशन' },
      { account: 'Profit on Sale (आय) — या हानि हो तो Dr', type: 'Cr', note: 'मिली राशि घटा बही मूल्य' },
    ],
    narration: 'संपत्ति बिक्री — ___',
    notes: ['बही मूल्य = मूल लागत घटा अब तक की संचित डेप्रिसिएशन। मिली राशि > बही मूल्य तो लाभ (Cr), कम तो हानि (Dr)।'],
    guideSlug: 'depreciation',
    related: ['asset-purchase', 'depreciation'],
  },
  {
    slug: 'farmer-payment-msp',
    metaTitle: 'किसान को MSP भुगतान (ऋण कटौती सहित) — Dr/Cr | SahakarLekha',
    metaDescription: 'MSP खरीद में किसान को भुगतान, पुराने ऋण की कटौती सहित — Dr खरीद, Cr Cash व Cr ऋण वसूली।',
    category: 'HAFED / MSP',
    title: 'किसान को MSP भुगतान (ऋण कटौती सहित)',
    intent: 'farmer payment msp loan deduction entry',
    scenario: 'MSP खरीद में किसान से अनाज लिया; भुगतान में से उसका पुराना ऋण काटा।',
    lines: [
      { account: 'Purchases / खरीद (अनाज)', type: 'Dr' },
      { account: 'Cash / Bank', type: 'Cr', note: 'किसान को हाथ में दिया (net)' },
      { account: 'Loans & Advances / ऋण वसूली', type: 'Cr', note: 'किसान का पुराना ऋण काटा' },
    ],
    narration: 'MSP भुगतान — किसान ___, ऋण कटौती सहित',
    societyTypes: ['विपणन / Marketing', 'PACS'],
    notes: ['एजेंसी (HAFED) के लिए खरीद हो तो खरीद/भुगतान एजेंसी खाते से जुड़ता है। बारदाना व सूखत अलग। राज्य/एजेंसी नियम बदल सकते हैं — RCS/ऑडिटर से पुष्टि करें।'],
    guideSlug: 'msp-procurement-entries',
    related: ['hafed-procurement-commission', 'loan-recovery'],
  },
  {
    slug: 'mandi-fee-hrdf',
    metaTitle: 'मंडी शुल्क व HRDF की एंट्री — Dr/Cr | SahakarLekha',
    metaDescription: 'MSP खरीद पर मंडी शुल्क व HRDF — Dr मंडी शुल्क/HRDF (वसूली-योग्य या व्यय), Cr Cash/Payable।',
    category: 'HAFED / MSP',
    title: 'मंडी शुल्क व HRDF',
    intent: 'mandi fee hrdf entry',
    scenario: 'MSP खरीद पर मंडी शुल्क व HRDF चुकाना/वसूली-योग्य रखना है।',
    lines: [
      { account: 'मंडी शुल्क / HRDF (वसूली-योग्य या व्यय)', type: 'Dr' },
      { account: 'Cash / Bank / Payable', type: 'Cr' },
    ],
    narration: 'मंडी शुल्क व HRDF — सीज़न ___',
    societyTypes: ['विपणन / Marketing', 'PACS'],
    notes: ['एजेंसी के लिए खरीद में ये अक्सर एजेंसी से वसूली-योग्य होते हैं (व्यय नहीं)। अपने राज्य/एजेंसी के नियम देखें।'],
    guideSlug: 'msp-procurement-entries',
    related: ['hafed-procurement-commission', 'farmer-payment-msp'],
  },
  {
    slug: 'milk-procurement',
    metaTitle: 'दुग्ध समिति — सदस्य से दूध खरीद की एंट्री | SahakarLekha',
    metaDescription: 'दुग्ध सहकारी समिति में सदस्य से दूध खरीदने का journal — Dr Milk Purchase, Cr सदस्य/Cash।',
    category: 'समिति-प्रकार',
    title: 'दूध खरीद (दुग्ध समिति)',
    intent: 'milk procurement dudh kharid dairy entry',
    scenario: 'दुग्ध सहकारी समिति ने सदस्य से दूध लिया (fat/SNF आधार पर दर)।',
    lines: [
      { account: 'Milk Purchase / दूध खरीद', type: 'Dr' },
      { account: 'सदस्य देय / Cash', type: 'Cr' },
    ],
    narration: 'दूध खरीद — सदस्य ___, ___ लीटर',
    societyTypes: ['दुग्ध / Dairy'],
    notes: ['दर fat व SNF पर तय होती है; भुगतान आमतौर पर 10-दिनी चक्र में। संघ (federation) को दूध बिक्री अलग आय एंट्री है।'],
    guideSlug: 'society-type-entries',
    related: ['cash-purchase', 'cash-sale'],
  },
];

export function findCookbookEntry(slug: string): CookbookEntry | null {
  return COOKBOOK_ENTRIES.find((e) => e.slug === slug) ?? null;
}

export const COOKBOOK_CATEGORIES: string[] = COOKBOOK_ENTRIES.reduce<string[]>((acc, e) => {
  if (!acc.includes(e.category)) acc.push(e.category);
  return acc;
}, []);

export function relatedCookbookEntries(slug: string): CookbookEntry[] {
  const self = findCookbookEntry(slug);
  if (!self?.related) return [];
  return self.related.map(findCookbookEntry).filter((e): e is CookbookEntry => !!e);
}
