/**
 * Dairy Cooperative Society — Chart of Accounts Template
 * Focus: Milk procurement, chilling/processing, cattle feed, ghee/paneer production
 * ~120 accounts
 */
import type { LedgerAccount } from '@/types';

export const DAIRY_SOCIETY_ACCOUNTS: LedgerAccount[] = [
  // ── Capital & Funds (Equity) ────────────────────────────────────────────
  { id: '1000', name: 'Capital & Funds',            nameHi: 'पूंजी एवं निधियाँ',        type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true  },
  { id: '1100', name: 'Share Capital',              nameHi: 'शेयर पूंजी',               type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true,  parentId: '1000' },
  { id: '1101', name: 'Govt Share Capital',         nameHi: 'सरकारी शेयर पूंजी',        type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1100', subtype: 'share_capital' },
  { id: '1102', name: 'Individual Share Capital',   nameHi: 'व्यक्तिगत शेयर पूंजी',     type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: false, parentId: '1100', subtype: 'share_capital' },
  { id: '1200', name: 'Reserves & Surplus',         nameHi: 'संचय एवं अधिशेष',          type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true,  parentId: '1000' },
  { id: '1201', name: 'Statutory Reserve Fund',     nameHi: 'वैधानिक संचय निधि',        type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1202', name: 'Building Fund',              nameHi: 'भवन निधि',                 type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1203', name: 'Education Fund',             nameHi: 'शिक्षा निधि',               type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1204', name: 'Risk Fund',                  nameHi: 'जोखिम निधि',               type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1205', name: 'Bad Debt Fund',              nameHi: 'अशोध्य ऋण निधि',           type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1206', name: 'Depreciation Fund',          nameHi: 'ह्रास निधि',               type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1207', name: 'Cattle Development Fund',    nameHi: 'पशु विकास निधि',           type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1208', name: 'Net Surplus / (Deficit)',     nameHi: 'शुद्ध अधिशेष / (घाटा)',    type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'surplus' },
  { id: '1211', name: 'Dividend Distribution',      nameHi: 'लाभांश वितरण',             type: 'equity',    openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '4407', name: 'Admission Fee',              nameHi: 'प्रवेश शुल्क (पूंजी)',     type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: false, parentId: '1200', subtype: 'reserve' },

  // ── Liabilities ──────────────────────────────────────────────────────────
  { id: '2000', name: 'Liabilities',                nameHi: 'दायित्व',                  type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true  },
  { id: '2100', name: 'Current Liabilities',        nameHi: 'चालू दायित्व',             type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '2000' },
  { id: '2101', name: 'Sundry Creditors',           nameHi: 'विविध लेनदार',             type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100' },
  { id: '2102', name: 'Milk Payment Payable',       nameHi: 'देय दुग्ध भुगतान',         type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100' },
  { id: '2103', name: 'Salary Payable',             nameHi: 'देय वेतन',                 type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100' },
  { id: '2104', name: 'Dividend Payable',           nameHi: 'देय लाभांश',               type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100' },
  { id: '2107', name: 'Member Deposits',            nameHi: 'सदस्य जमाराशि',            type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100', subtype: 'deposit' },
  { id: '2200', name: 'Statutory Liabilities',      nameHi: 'वैधानिक दायित्व',          type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '2000' },
  { id: '2201', name: 'GST Payable',                nameHi: 'देय GST',                  type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2200' },
  { id: '2202', name: 'TDS Payable',                nameHi: 'देय TDS',                  type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2200' },
  { id: '2203', name: 'EPF Payable',                nameHi: 'देय EPF',                  type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2200' },
  { id: '2204', name: 'ESI Payable',                nameHi: 'देय ESI',                  type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2200' },
  { id: '2206', name: 'Income Tax Payable',         nameHi: 'देय आयकर',                 type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2200' },
  { id: '2300', name: 'Loans',                      nameHi: 'ऋण',                       type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '2000' },
  { id: '2301', name: 'Bank OD',                    nameHi: 'बैंक अधिविकर्ष',           type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2300' },
  { id: '2302', name: 'Secured Loan',               nameHi: 'सुरक्षित ऋण',              type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2300' },
  { id: '2304', name: 'Loan from DCCB/NABARD',      nameHi: 'DCCB/नाबार्ड से ऋण',       type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2300' },

  // ── Assets ───────────────────────────────────────────────────────────────
  { id: '3000', name: 'Assets',                     nameHi: 'संपत्तियाँ',               type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: true  },
  { id: '3100', name: 'Fixed Assets',               nameHi: 'स्थायी संपत्तियाँ',         type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '3000' },
  { id: '3101', name: 'Land',                       nameHi: 'भूमि',                     type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3102', name: 'Building',                   nameHi: 'भवन',                      type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3103', name: 'Furniture',                  nameHi: 'फर्नीचर',                   type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3104', name: 'Vehicle',                    nameHi: 'वाहन',                     type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3105', name: 'Chilling Plant & BMC',       nameHi: 'चिलिंग प्लांट एवं BMC',    type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3106', name: 'Milk Testing Equipment',     nameHi: 'दुग्ध परीक्षण उपकरण',      type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3107', name: 'Computer / IT Equipment',    nameHi: 'कंप्यूटर / IT उपकरण',      type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3108', name: 'Accum. Dep. - Building',     nameHi: 'संचित ह्रास - भवन',         type: 'asset',     openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3109', name: 'Accum. Dep. - Chilling Plant',nameHi: 'संचित ह्रास - चिलिंग',     type: 'asset',     openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3110', name: 'Accum. Dep. - Vehicle',      nameHi: 'संचित ह्रास - वाहन',        type: 'asset',     openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3200', name: 'Investments',                nameHi: 'निवेश',                    type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '3000' },
  { id: '3201', name: 'FDR',                        nameHi: 'सावधि जमा (FDR)',           type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3200' },
  { id: '3202', name: 'Cooperative Society Shares', nameHi: 'सहकारी समिति शेयर',        type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3200' },
  { id: '3300', name: 'Current Assets',             nameHi: 'चालू संपत्तियाँ',           type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: true,  parentId: '3000' },
  { id: '3301', name: 'Cash in Hand',               nameHi: 'हाथ में नकद',              type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: false, parentId: '3300', subtype: 'cash_bank' },
  { id: '3302', name: 'Bank Accounts',              nameHi: 'बैंक खाते',                type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: false, parentId: '3300', subtype: 'cash_bank' },
  { id: '3303', name: 'Sundry Debtors',             nameHi: 'विविध देनदार',             type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },
  { id: '3304', name: 'Milk Procurement Advance',   nameHi: 'दुग्ध खरीदी अग्रिम',       type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },
  { id: '3307', name: 'TDS Receivable',             nameHi: 'प्राप्य TDS',               type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },
  { id: '3310', name: 'GST Input Credit (ITC)',     nameHi: 'GST इनपुट क्रेडिट',        type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },
  { id: '3312', name: 'Interest Receivable',        nameHi: 'प्राप्य ब्याज',             type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },
  { id: '3400', name: 'Inventory',                  nameHi: 'माल-सूची',                 type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '3000' },
  { id: '3401', name: 'Milk Stock (Raw)',            nameHi: 'कच्चा दूध भंडार',          type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3400' },
  { id: '3402', name: 'Ghee Stock',                 nameHi: 'घी भंडार',                 type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3400' },
  { id: '3403', name: 'Cattle Feed Stock',          nameHi: 'पशु आहार भंडार',           type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3400' },
  { id: '3404', name: 'Packaging Material',         nameHi: 'पैकिंग सामग्री',            type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3400' },

  // ── Income ───────────────────────────────────────────────────────────────
  { id: '4000', name: 'Income',                     nameHi: 'आय',                       type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true  },
  { id: '4100', name: 'Trading Income',             nameHi: 'व्यापारिक आय',             type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '4000' },
  { id: '4101', name: 'Milk Sales',                 nameHi: 'दुग्ध बिक्री',             type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4100' },
  { id: '4102', name: 'Ghee / Paneer Sales',        nameHi: 'घी / पनीर बिक्री',         type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4100' },
  { id: '4103', name: 'Cattle Feed Sales',          nameHi: 'पशु आहार बिक्री',          type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4100' },
  { id: '4104', name: 'Curd / Buttermilk Sales',    nameHi: 'दही / छाछ बिक्री',         type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4100' },
  { id: '4200', name: 'Commission Income',          nameHi: 'कमीशन आय',                type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '4000' },
  { id: '4201', name: 'Milk Procurement Commission',nameHi: 'दुग्ध संकलन कमीशन',        type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4200' },
  { id: '4300', name: 'Scheme Income',              nameHi: 'योजना आय',                 type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '4000' },
  { id: '4301', name: 'NABARD Dairy Subsidy',       nameHi: 'नाबार्ड डेयरी अनुदान',     type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4300' },
  { id: '4302', name: 'Govt Dairy Scheme',          nameHi: 'सरकारी डेयरी योजना',       type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4300' },
  { id: '4400', name: 'Other Income',               nameHi: 'अन्य आय',                  type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '4000' },
  { id: '4401', name: 'Rent',                       nameHi: 'किराया आय',                type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4400' },
  { id: '4403', name: 'Interest Income',            nameHi: 'ब्याज आय',                 type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4400' },
  { id: '4404', name: 'Dividend',                   nameHi: 'लाभांश आय',                type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4400' },
  { id: '4405', name: 'Miscellaneous Income',       nameHi: 'विविध आय',                 type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4400' },

  // ── Expenses ─────────────────────────────────────────────────────────────
  { id: '5000', name: 'Expenses',                   nameHi: 'व्यय',                     type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: true  },
  { id: '5100', name: 'Direct Expenses',            nameHi: 'प्रत्यक्ष व्यय',           type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5101', name: 'Milk Procurement Cost',      nameHi: 'दुग्ध खरीदी लागत',         type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5102', name: 'Cattle Feed Purchase',       nameHi: 'पशु आहार खरीदी',           type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5103', name: 'Chilling / Processing Cost', nameHi: 'शीतलन / प्रसंस्करण लागत',  type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5104', name: 'Milk Testing Expense',       nameHi: 'दुग्ध परीक्षण व्यय',       type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5105', name: 'Milk Transport',             nameHi: 'दुग्ध परिवहन व्यय',        type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5106', name: 'Packaging Expense',          nameHi: 'पैकिंग व्यय',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5107', name: 'Wastage / Spillage',         nameHi: 'बर्बादी / छलकाव',          type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5200', name: 'Employee Expenses',          nameHi: 'कर्मचारी व्यय',            type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5201', name: 'Salary',                     nameHi: 'वेतन',                     type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5200' },
  { id: '5202', name: 'Wages',                      nameHi: 'मजदूरी',                   type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5200' },
  { id: '5203', name: 'PF',                         nameHi: 'भविष्य निधि',               type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5200' },
  { id: '5204', name: 'ESI',                        nameHi: 'कर्मचारी बीमा',             type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5200' },
  { id: '5300', name: 'Admin Expenses',             nameHi: 'प्रशासनिक व्यय',           type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5301', name: 'Office Expenses',            nameHi: 'कार्यालय व्यय',            type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5302', name: 'Electricity',                nameHi: 'बिजली व्यय',               type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5303', name: 'Printing & Stationery',      nameHi: 'मुद्रण एवं लेखन',           type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5304', name: 'Telephone',                  nameHi: 'दूरभाष व्यय',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5305', name: 'Legal Fee',                  nameHi: 'कानूनी व्यय',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5306', name: 'Audit Fee',                  nameHi: 'लेखा परीक्षण व्यय',         type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5314', name: 'Bank Charges',               nameHi: 'बैंक प्रभार',               type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5400', name: 'Operational Expenses',       nameHi: 'परिचालन व्यय',             type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5401', name: 'Veterinary Expenses',        nameHi: 'पशु चिकित्सा व्यय',        type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5400' },
  { id: '5402', name: 'Repair & Maintenance',       nameHi: 'मरम्मत व्यय',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5400' },
  { id: '5403', name: 'Insurance',                  nameHi: 'बीमा व्यय',                type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5400' },
  { id: '5404', name: 'Vehicle Expense',            nameHi: 'वाहन व्यय',                type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5400' },
  { id: '5500', name: 'Depreciation',               nameHi: 'ह्रास',                    type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5501', name: 'Dep. - Building',            nameHi: 'भवन ह्रास',                type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5500' },
  { id: '5502', name: 'Dep. - Chilling Plant',      nameHi: 'चिलिंग प्लांट ह्रास',      type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5500' },
  { id: '5503', name: 'Dep. - Vehicle',             nameHi: 'वाहन ह्रास',               type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5500' },
  { id: '5600', name: 'Statutory Expenses',         nameHi: 'वैधानिक व्यय',             type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5601', name: 'GST Expense',                nameHi: 'GST व्यय',                 type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5600' },
  { id: '5603', name: 'Income Tax',                 nameHi: 'आयकर व्यय',                type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5600' },
  { id: '5604', name: 'Interest on Borrowings',     nameHi: 'उधार पर ब्याज',             type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5600' },
  { id: '9999', name: 'Suspense Account',           nameHi: 'संदिग्ध खाता',             type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false },
];
