/**
 * Housing Cooperative Society — Chart of Accounts Template
 * Focus: Maintenance collection, sinking fund, common area management, property tax
 * ~100 accounts
 */
import type { LedgerAccount } from '@/types';

export const HOUSING_SOCIETY_ACCOUNTS: LedgerAccount[] = [
  // ── Capital & Funds (Equity) ────────────────────────────────────────────
  { id: '1000', name: 'Capital & Funds',            nameHi: 'पूंजी एवं निधियाँ',        type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true  },
  { id: '1100', name: 'Share Capital',              nameHi: 'शेयर पूंजी',               type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true,  parentId: '1000' },
  { id: '1101', name: 'Govt Share Capital',         nameHi: 'सरकारी शेयर पूंजी',        type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1100', subtype: 'share_capital' },
  { id: '1102', name: 'Individual Share Capital',   nameHi: 'व्यक्तिगत शेयर पूंजी',     type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: false, parentId: '1100', subtype: 'share_capital' },
  { id: '1200', name: 'Reserves & Surplus',         nameHi: 'संचय एवं अधिशेष',          type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true,  parentId: '1000' },
  { id: '1201', name: 'Statutory Reserve Fund',     nameHi: 'वैधानिक संचय निधि',        type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1202', name: 'Sinking Fund',               nameHi: 'मरम्मत संचय निधि',         type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1203', name: 'Education Fund',             nameHi: 'शिक्षा निधि',               type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1204', name: 'Repair & Maintenance Fund',  nameHi: 'मरम्मत एवं रखरखाव निधि',   type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1206', name: 'Depreciation Fund',          nameHi: 'ह्रास निधि',               type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'reserve' },
  { id: '1208', name: 'Net Surplus / (Deficit)',     nameHi: 'शुद्ध अधिशेष / (घाटा)',    type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '1200', subtype: 'surplus' },
  { id: '4407', name: 'Admission Fee',              nameHi: 'प्रवेश शुल्क (पूंजी)',     type: 'equity',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: false, parentId: '1200', subtype: 'reserve' },

  // ── Liabilities ──────────────────────────────────────────────────────────
  { id: '2000', name: 'Liabilities',                nameHi: 'दायित्व',                  type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true  },
  { id: '2100', name: 'Current Liabilities',        nameHi: 'चालू दायित्व',             type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '2000' },
  { id: '2101', name: 'Sundry Creditors',           nameHi: 'विविध लेनदार',             type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100' },
  { id: '2102', name: 'Expenses Payable',           nameHi: 'देय व्यय',                 type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100' },
  { id: '2103', name: 'Salary Payable',             nameHi: 'देय वेतन',                 type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100' },
  { id: '2107', name: 'Member Security Deposits',   nameHi: 'सदस्य सुरक्षा जमा',        type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100', subtype: 'deposit' },
  { id: '2108', name: 'Advance Maintenance Collected',nameHi: 'अग्रिम रखरखाव शुल्क',    type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2100' },
  { id: '2200', name: 'Statutory Liabilities',      nameHi: 'वैधानिक दायित्व',          type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '2000' },
  { id: '2201', name: 'GST Payable',                nameHi: 'देय GST',                  type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2200' },
  { id: '2202', name: 'TDS Payable',                nameHi: 'देय TDS',                  type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2200' },
  { id: '2206', name: 'Income Tax Payable',         nameHi: 'देय आयकर',                 type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2200' },
  { id: '2207', name: 'Property Tax Payable',       nameHi: 'देय संपत्ति कर',            type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2200' },
  { id: '2300', name: 'Loans',                      nameHi: 'ऋण',                       type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '2000' },
  { id: '2301', name: 'Bank Loan',                  nameHi: 'बैंक ऋण',                  type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '2300' },

  // ── Assets ───────────────────────────────────────────────────────────────
  { id: '3000', name: 'Assets',                     nameHi: 'संपत्तियाँ',               type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: true  },
  { id: '3100', name: 'Fixed Assets',               nameHi: 'स्थायी संपत्तियाँ',         type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '3000' },
  { id: '3101', name: 'Land',                       nameHi: 'भूमि',                     type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3102', name: 'Building',                   nameHi: 'भवन',                      type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3103', name: 'Furniture',                  nameHi: 'फर्नीचर',                   type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3104', name: 'Lift / Elevator',            nameHi: 'लिफ्ट',                    type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3105', name: 'Water Pump / Generator',     nameHi: 'जल पंप / जनरेटर',          type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3106', name: 'CCTV & Security Equipment',  nameHi: 'CCTV एवं सुरक्षा उपकरण',   type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3107', name: 'Computer / IT Equipment',    nameHi: 'कंप्यूटर / IT उपकरण',      type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3108', name: 'Accum. Dep. - Building',     nameHi: 'संचित ह्रास - भवन',         type: 'asset',     openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3109', name: 'Accum. Dep. - Lift',         nameHi: 'संचित ह्रास - लिफ्ट',       type: 'asset',     openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3110', name: 'Accum. Dep. - Equipment',    nameHi: 'संचित ह्रास - उपकरण',       type: 'asset',     openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '3100' },
  { id: '3200', name: 'Investments',                nameHi: 'निवेश',                    type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '3000' },
  { id: '3201', name: 'FDR',                        nameHi: 'सावधि जमा (FDR)',           type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3200' },
  { id: '3300', name: 'Current Assets',             nameHi: 'चालू संपत्तियाँ',           type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: true,  parentId: '3000' },
  { id: '3301', name: 'Cash in Hand',               nameHi: 'हाथ में नकद',              type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: false, parentId: '3300', subtype: 'cash_bank' },
  { id: '3302', name: 'Bank Accounts',              nameHi: 'बैंक खाते',                type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: false, parentId: '3300', subtype: 'cash_bank' },
  { id: '3303', name: 'Maintenance Receivable',     nameHi: 'प्राप्य रखरखाव शुल्क',      type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },
  { id: '3304', name: 'Water Charges Receivable',   nameHi: 'प्राप्य जल शुल्क',          type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },
  { id: '3307', name: 'TDS Receivable',             nameHi: 'प्राप्य TDS',               type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },
  { id: '3310', name: 'GST Input Credit (ITC)',     nameHi: 'GST इनपुट क्रेडिट',        type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },
  { id: '3312', name: 'Interest Receivable',        nameHi: 'प्राप्य ब्याज',             type: 'asset',     openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '3300' },

  // ── Income ───────────────────────────────────────────────────────────────
  { id: '4000', name: 'Income',                     nameHi: 'आय',                       type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: true,  isGroup: true  },
  { id: '4100', name: 'Member Charges',             nameHi: 'सदस्य शुल्क',              type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '4000' },
  { id: '4101', name: 'Maintenance Charges',        nameHi: 'रखरखाव शुल्क',             type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4100' },
  { id: '4102', name: 'Water Charges',              nameHi: 'जल शुल्क',                 type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4100' },
  { id: '4103', name: 'Parking Charges',            nameHi: 'पार्किंग शुल्क',            type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4100' },
  { id: '4104', name: 'Non-Occupancy Charges',      nameHi: 'अनिवासी प्रभार',            type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4100' },
  { id: '4105', name: 'Sinking Fund Contribution',  nameHi: 'मरम्मत निधि अंशदान',       type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4100' },
  { id: '4200', name: 'Other Charges',              nameHi: 'अन्य प्रभार',              type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '4000' },
  { id: '4201', name: 'Transfer Fee',               nameHi: 'हस्तांतरण शुल्क',           type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4200' },
  { id: '4202', name: 'NOC Charges',                nameHi: 'एनओसी शुल्क',              type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4200' },
  { id: '4400', name: 'Other Income',               nameHi: 'अन्य आय',                  type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: true,  parentId: '4000' },
  { id: '4401', name: 'Rent from Common Area',      nameHi: 'सामान्य क्षेत्र किराया',    type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4400' },
  { id: '4402', name: 'Interest on Defaulters',     nameHi: 'चूककर्ताओं पर ब्याज',       type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4400' },
  { id: '4403', name: 'Interest on FDR',            nameHi: 'एफडीआर ब्याज',             type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4400' },
  { id: '4405', name: 'Miscellaneous Income',       nameHi: 'विविध आय',                 type: 'income',    openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false, parentId: '4400' },

  // ── Expenses ─────────────────────────────────────────────────────────────
  { id: '5000', name: 'Expenses',                   nameHi: 'व्यय',                     type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: true,  isGroup: true  },
  { id: '5100', name: 'Direct Expenses',            nameHi: 'प्रत्यक्ष व्यय',           type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5101', name: 'Water Supply Charges',       nameHi: 'जल आपूर्ति व्यय',          type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5102', name: 'Common Electricity',         nameHi: 'सामान्य बिजली व्यय',       type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5103', name: 'Lift Maintenance',           nameHi: 'लिफ्ट रखरखाव',             type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5104', name: 'Security / Watchman',        nameHi: 'सुरक्षा / चौकीदार व्यय',   type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5105', name: 'Garden & Housekeeping',      nameHi: 'उद्यान एवं स्वच्छता',      type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5106', name: 'Pest Control',               nameHi: 'कीट नियंत्रण',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5100' },
  { id: '5200', name: 'Employee Expenses',          nameHi: 'कर्मचारी व्यय',            type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5201', name: 'Salary',                     nameHi: 'वेतन',                     type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5200' },
  { id: '5202', name: 'Wages',                      nameHi: 'मजदूरी',                   type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5200' },
  { id: '5203', name: 'PF',                         nameHi: 'भविष्य निधि',               type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5200' },
  { id: '5300', name: 'Admin Expenses',             nameHi: 'प्रशासनिक व्यय',           type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5301', name: 'Office Expenses',            nameHi: 'कार्यालय व्यय',            type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5302', name: 'Printing & Stationery',      nameHi: 'मुद्रण एवं लेखन',           type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5303', name: 'Telephone',                  nameHi: 'दूरभाष व्यय',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5305', name: 'Legal Fee',                  nameHi: 'कानूनी व्यय',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5306', name: 'Audit Fee',                  nameHi: 'लेखा परीक्षण व्यय',         type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5310', name: 'Meeting / AGM Expenses',     nameHi: 'बैठक / AGM व्यय',           type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5314', name: 'Bank Charges',               nameHi: 'बैंक प्रभार',               type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5300' },
  { id: '5400', name: 'Operational Expenses',       nameHi: 'परिचालन व्यय',             type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5401', name: 'Fire Safety Compliance',     nameHi: 'अग्निशमन सुरक्षा',         type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5400' },
  { id: '5402', name: 'Repair & Maintenance',       nameHi: 'मरम्मत व्यय',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5400' },
  { id: '5403', name: 'Insurance',                  nameHi: 'बीमा व्यय',                type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5400' },
  { id: '5404', name: 'Municipal / BMC Charges',    nameHi: 'नगरपालिका शुल्क',           type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5400' },
  { id: '5500', name: 'Depreciation',               nameHi: 'ह्रास',                    type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5501', name: 'Dep. - Building',            nameHi: 'भवन ह्रास',                type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5500' },
  { id: '5502', name: 'Dep. - Lift',                nameHi: 'लिफ्ट ह्रास',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5500' },
  { id: '5503', name: 'Dep. - Equipment',           nameHi: 'उपकरण ह्रास',              type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5500' },
  { id: '5600', name: 'Statutory Expenses',         nameHi: 'वैधानिक व्यय',             type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: true,  parentId: '5000' },
  { id: '5601', name: 'Property Tax',               nameHi: 'संपत्ति कर',                type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5600' },
  { id: '5602', name: 'GST Expense',                nameHi: 'GST व्यय',                 type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5600' },
  { id: '5603', name: 'Income Tax',                 nameHi: 'आयकर व्यय',                type: 'expense',   openingBalance: 0, openingBalanceType: 'debit',  isSystem: false, isGroup: false, parentId: '5600' },
  { id: '9999', name: 'Suspense Account',           nameHi: 'संदिग्ध खाता',             type: 'liability', openingBalance: 0, openingBalanceType: 'credit', isSystem: false, isGroup: false },
];
