-- preview for 115 · READ-ONLY. GENERATED by scripts/gen-migration-115.mjs. Run BEFORE migration 115.
-- One row per account migration 115 will add, per society. Nothing is written. (Expected on 2026-10-08: 62 rows = 31 × 2.)
select s.society_id, v.id as account_id, v.name
  from (select distinct society_id from public.accounts) s
 cross join (values
    ('4499', 'Discount Received', 'प्राप्त छूट', 'income', 'credit', false, false, '4400', 'discount_received', 0),
    ('5499', 'Round Off', 'राउंड ऑफ', 'expense', 'debit', false, false, '5400', 'round_off', 1)
  ) as v(id, name, "nameHi", type, "openingBalanceType", "isSystem", "isGroup", "parentId", subtype, ord)
 where not exists (select 1 from public.accounts a where a.society_id = s.society_id and a.id = v.id)
   and not exists (select 1 from public.accounts a where a.society_id = s.society_id and a.code = v.id)
   and not exists (select 1 from public.accounts a where a.society_id = s.society_id and lower(trim(a.name)) = lower(trim(v.name)) and a.type = v.type)
   and exists (select 1 from public.accounts p where p.society_id = s.society_id and p.id = v."parentId")
 order by s.society_id, v.ord;
