-- 114 · Persist the shared extra accounts (ACCOUNTS_TO_ADD) that existing societies only had ON SCREEN.
-- GENERATED by scripts/gen-migration-114.mjs from the code's own ACCOUNTS_TO_ADD list — do not edit by hand.
--
-- WHY: on every load the app merges ACCOUNTS_TO_ADD (purchase / sales heads 5110-5116 and 4104-4108, Closing Stock
-- 5150, Wages Payable 2109, Overdue Interest Reserve 2211, EPF EDLI 5209, Scheme Income 4300 …) into LOCAL state
-- only — the load path never writes (RM-01). So a society whose chart was seeded before these existed sees a
-- complete chart that its database does not hold, and the server refuses the first voucher on them
-- (post_voucher:account_not_found). Rania 2026-10-07: 16 accounts; 13 of 31 societies, 58 rows.
-- New and reset societies are seeded with the full chart (fullChartForType); this fixes the existing ones.
--
-- WHAT: for every society, add each ACCOUNTS_TO_ADD account it lacks — the SAME rule the app uses on screen: skip when
-- the id already exists OR an account with the same name and type exists; and (database rule) only when its parent
-- group exists. Groups first, then ledgers (so a ledger under a group added in this run finds its parent).
-- Opening balance 0. INSERT only, "on conflict do nothing": no existing row is changed or removed.
-- Run supabase/diagnostics/preview_114_extra_accounts.sql first. Undo: 114_..._down.sql (removes only
-- rows this migration added that nothing references).
-- NO temp tables — the SQL Editor's "Run and enable RLS" splits statements.

begin;

-- 1. groups
insert into public.accounts (id, society_id, name, "nameHi", type, "openingBalance", "openingBalanceType", "isSystem", "isGroup", "parentId", subtype, jurisdiction)
select v.id, s.society_id, v.name, v."nameHi", v.type, 0, v."openingBalanceType", v."isSystem", v."isGroup", v."parentId", v.subtype,
       (select a.jurisdiction from public.accounts a where a.society_id = s.society_id and a.jurisdiction is not null limit 1)
  from (select distinct society_id from public.accounts) s
 cross join (values
    ('4200', 'Commission Income', 'कमीशन आय', 'income', 'credit', false, true, '4000', null, 0),
    ('4300', 'Scheme Income', 'योजना आय', 'income', 'credit', false, true, '4000', null, 1),
    ('3104', 'Vehicle', 'वाहन', 'asset', 'debit', false, false, '3100', 'fixed_asset', 2),
    ('3400', 'Inventory', 'माल-सूची', 'asset', 'debit', false, true, '3000', null, 3),
    ('4100', 'Trading Income', 'व्यापारिक आय', 'income', 'credit', false, true, '4000', null, 4),
    ('4101', 'Fertilizer Sales', 'उर्वरक बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 5),
    ('4102', 'Seed Sales', 'बीज बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 6),
    ('5100', 'Direct Expenses', 'प्रत्यक्ष व्यय', 'expense', 'debit', false, true, '5000', null, 7),
    ('5101', 'Purchase', 'क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 8),
    ('2107', 'Member Deposits', 'सदस्य जमाराशि', 'liability', 'credit', false, false, '2100', 'deposit', 9),
    ('2109', 'Wages Payable', 'देय मज़दूरी', 'liability', 'credit', false, false, '2100', 'current_liability', 10),
    ('3307', 'TDS / TCS Receivable', 'प्राप्य TDS / TCS', 'asset', 'debit', false, false, '3300', 'current_asset', 11),
    ('2203', 'EPF Payable', 'देय EPF', 'liability', 'credit', false, false, '2200', 'statutory_liability', 12),
    ('2204', 'ESI Payable', 'देय ESI', 'liability', 'credit', false, false, '2200', 'statutory_liability', 13),
    ('5203', 'PF', 'भविष्य निधि (PF)', 'expense', 'debit', false, false, '5200', 'employee_expense', 14),
    ('5204', 'ESI', 'कर्मचारी बीमा (ESI)', 'expense', 'debit', false, false, '5200', 'employee_expense', 15),
    ('5209', 'EPF EDLI & Admin Charges', 'EPF EDLI व प्रशासनिक प्रभार', 'expense', 'debit', false, false, '5200', 'employee_expense', 16),
    ('2205', 'HRDF Payable', 'देय HRDF', 'liability', 'credit', false, false, '2200', 'statutory_liability', 17),
    ('3108', 'Accum. Dep. - Building', 'संचित ह्रास - भवन', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 18),
    ('3109', 'Accum. Dep. - Furniture', 'संचित ह्रास - फर्नीचर', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 19),
    ('3110', 'Accum. Dep. - Vehicle', 'संचित ह्रास - वाहन', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 20),
    ('3111', 'Accum. Dep. - Plant', 'संचित ह्रास - संयंत्र', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 21),
    ('3112', 'Accum. Dep. - Office Equip', 'संचित ह्रास - उपकरण', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 22),
    ('3310', 'GST Input Credit (ITC)', 'GST इनपुट क्रेडिट (ITC)', 'asset', 'debit', false, false, '3300', 'current_asset', 23),
    ('3311', 'Prepaid Expenses', 'अग्रिम व्यय', 'asset', 'debit', false, false, '3300', 'current_asset', 24),
    ('5308', 'Rent', 'किराया व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 25),
    ('5309', 'Travelling Expenses', 'यात्रा व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 26),
    ('5310', 'Meeting / AGM Expenses', 'बैठक / AGM व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 27),
    ('5311', 'Education Fund Contribution', 'शिक्षा निधि अंशदान', 'expense', 'debit', false, false, '5300', 'admin_expense', 28),
    ('5505', 'Computer / Office Equip', 'कंप्यूटर / उपकरण ह्रास', 'expense', 'debit', false, false, '5500', 'depreciation_expense', 29),
    ('1209', 'Price Stabilization Fund', 'मूल्य स्थिरता निधि', 'equity', 'credit', false, false, '1200', 'reserve', 30),
    ('1210', 'Social / Cooperative Dev Fund', 'सहकारी विकास निधि', 'equity', 'credit', false, false, '1200', 'reserve', 31),
    ('1211', 'Dividend Distribution', 'लाभांश वितरण', 'equity', 'debit', false, false, '1200', 'reserve', 32),
    ('2206', 'Income Tax Payable', 'देय आयकर', 'liability', 'credit', false, false, '2200', 'statutory_liability', 33),
    ('2207', 'Professional Tax Payable', 'देय व्यावसायिक कर', 'liability', 'credit', false, false, '2200', 'statutory_liability', 34),
    ('2208', 'Interest Payable', 'देय ब्याज', 'liability', 'credit', false, false, '2100', 'current_liability', 35),
    ('2209', 'Audit Fee Payable', 'देय लेखा परीक्षण शुल्क', 'liability', 'credit', false, false, '2100', 'current_liability', 36),
    ('2210', 'Advance from Members', 'सदस्यों से अग्रिम', 'liability', 'credit', false, false, '2100', 'current_liability', 37),
    ('2211', 'Overdue Interest Reserve', 'अतिदेय ब्याज संचय', 'liability', 'credit', false, false, '2100', 'current_liability', 38),
    ('2304', 'Loan from DCCB/NABARD', 'DCCB/नाबार्ड से ऋण', 'liability', 'credit', false, false, '2300', 'long_term_loan', 39),
    ('2305', 'KCC / Crop Loan (DCCB)', 'KCC / फसल ऋण (DCCB)', 'liability', 'credit', false, false, '2300', 'long_term_loan', 40),
    ('3107', 'Computer / IT Equipment', 'कंप्यूटर / IT उपकरण', 'asset', 'debit', false, false, '3100', 'fixed_asset', 41),
    ('3207', 'NSC / Post Office Deposits', 'NSC / डाकघर जमा', 'asset', 'debit', false, false, '3200', 'investment', 42),
    ('3208', 'Cooperative Society Shares', 'सहकारी समिति शेयर', 'asset', 'debit', false, false, '3200', 'investment', 43),
    ('3312', 'Interest Receivable', 'प्राप्य ब्याज', 'asset', 'debit', false, false, '3300', 'current_asset', 44),
    ('3313', 'Member Loan Interest Rec.', 'सदस्य ऋण ब्याज प्राप्य', 'asset', 'debit', false, false, '3300', 'current_asset', 45),
    ('3314', 'Commission Receivable', 'प्राप्य कमीशन', 'asset', 'debit', false, false, '3300', 'current_asset', 46),
    ('3315', 'Advance to Employees', 'कर्मचारियों को अग्रिम', 'asset', 'debit', false, false, '3300', 'current_asset', 47),
    ('3316', 'Stock in Transit', 'पारगमन में माल', 'asset', 'debit', false, false, '3300', 'current_asset', 48),
    ('3406', 'Packing Material', 'पैकिंग सामग्री', 'asset', 'debit', false, false, '3400', 'inventory', 49),
    ('4207', 'Storage / Cold Storage Income', 'गोदाम / शीत भंडार आय', 'income', 'credit', false, false, '4200', 'commission_income', 50),
    ('4208', 'Service Charges', 'सेवा प्रभार', 'income', 'credit', false, false, '4200', 'commission_income', 51),
    ('4304', 'PM Kisan / DBT Income', 'पीएम किसान / DBT आय', 'income', 'credit', false, false, '4300', 'scheme_income', 52),
    ('4305', 'FPO / Farmer Group Income', 'FPO / कृषक समूह आय', 'income', 'credit', false, false, '4300', 'scheme_income', 53),
    ('4408', 'Interest on Member Loans', 'सदस्य ऋण पर ब्याज', 'income', 'credit', false, false, '4400', 'other_income', 54),
    ('4409', 'Bad Debt Recovery', 'अशोध्य ऋण वसूली', 'income', 'credit', false, false, '4400', 'other_income', 55),
    ('4410', 'Profit on Sale of Assets', 'संपत्ति बिक्री पर लाभ', 'income', 'credit', false, false, '4400', 'other_income', 56),
    ('5206', 'Gratuity Provision', 'उपदान प्रावधान', 'expense', 'debit', false, false, '5200', 'employee_expense', 57),
    ('5207', 'Employee Bonus', 'कर्मचारी बोनस', 'expense', 'debit', false, false, '5200', 'employee_expense', 58),
    ('5208', 'HRA / DA Allowance', 'HRA / DA भत्ता', 'expense', 'debit', false, false, '5200', 'employee_expense', 59),
    ('5312', 'Advertisement', 'विज्ञापन व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 60),
    ('5313', 'Postage / Courier', 'डाक / कूरियर व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 61),
    ('5314', 'Bank Charges', 'बैंक प्रभार', 'expense', 'debit', false, false, '5300', 'admin_expense', 62),
    ('5315', 'Filing / Registration Fees', 'दाखिल / पंजीकरण शुल्क', 'expense', 'debit', false, false, '5300', 'admin_expense', 63),
    ('5404', 'Bad Debt Written Off', 'अशोध्य ऋण अपलेखन', 'expense', 'debit', false, false, '5400', 'operational_expense', 64),
    ('5405', 'Donation / CSR', 'दान / CSR व्यय', 'expense', 'debit', false, false, '5400', 'operational_expense', 65),
    ('5406', 'Loss on Sale of Assets', 'संपत्ति बिक्री पर हानि', 'expense', 'debit', false, false, '5400', 'operational_expense', 66),
    ('5407', 'Prior Period Adjustments', 'पूर्व अवधि समायोजन', 'expense', 'debit', false, false, '5400', 'operational_expense', 67),
    ('5603', 'Income Tax', 'आयकर व्यय', 'expense', 'debit', false, false, '5600', 'statutory_expense', 68),
    ('5604', 'Interest on Borrowings', 'उधार पर ब्याज व्यय', 'expense', 'debit', false, false, '5600', 'statutory_expense', 69),
    ('5605', 'Penalty / Fine', 'जुर्माना / दंड व्यय', 'expense', 'debit', false, false, '5600', 'statutory_expense', 70),
    ('4104', 'Pesticides Sales', 'कीटनाशक बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 71),
    ('4105', 'Animal Feed Sales', 'पशु आहार बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 72),
    ('4106', 'Agricultural Implements Sales', 'कृषि यंत्र बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 73),
    ('4107', 'PDS / Ration Goods Sales', 'सार्वजनिक वितरण बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 74),
    ('4108', 'Govt Procurement Sales', 'सरकारी खरीद बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 75),
    ('5110', 'Fertilizer Purchase', 'उर्वरक क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 76),
    ('5111', 'Seed Purchase', 'बीज क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 77),
    ('5112', 'Consumer Goods Purchase', 'उपभोक्ता वस्तु क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 78),
    ('5113', 'Pesticides Purchase', 'कीटनाशक क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 79),
    ('5114', 'Animal Feed Purchase', 'पशु आहार क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 80),
    ('5115', 'PDS / Ration Goods Purchase', 'सार्वजनिक वितरण क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 81),
    ('5116', 'Govt Procurement Purchase', 'सरकारी खरीद क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 82),
    ('5150', 'Closing Stock (Trading A/c)', 'समापन माल (व्यापार खाता)', 'expense', 'credit', true, false, '5100', 'closing_stock', 83)
  ) as v(id, name, "nameHi", type, "openingBalanceType", "isSystem", "isGroup", "parentId", subtype, ord)
 where v."isGroup"
   and not exists (select 1 from public.accounts a where a.society_id = s.society_id and a.id = v.id)
   and not exists (select 1 from public.accounts a where a.society_id = s.society_id and lower(trim(a.name)) = lower(trim(v.name)) and a.type = v.type)
   and (v."parentId" is null or exists (select 1 from public.accounts p where p.society_id = s.society_id and p.id = v."parentId"))
on conflict do nothing;

-- 2. ledgers
insert into public.accounts (id, society_id, name, "nameHi", type, "openingBalance", "openingBalanceType", "isSystem", "isGroup", "parentId", subtype, jurisdiction)
select v.id, s.society_id, v.name, v."nameHi", v.type, 0, v."openingBalanceType", v."isSystem", v."isGroup", v."parentId", v.subtype,
       (select a.jurisdiction from public.accounts a where a.society_id = s.society_id and a.jurisdiction is not null limit 1)
  from (select distinct society_id from public.accounts) s
 cross join (values
    ('4200', 'Commission Income', 'कमीशन आय', 'income', 'credit', false, true, '4000', null, 0),
    ('4300', 'Scheme Income', 'योजना आय', 'income', 'credit', false, true, '4000', null, 1),
    ('3104', 'Vehicle', 'वाहन', 'asset', 'debit', false, false, '3100', 'fixed_asset', 2),
    ('3400', 'Inventory', 'माल-सूची', 'asset', 'debit', false, true, '3000', null, 3),
    ('4100', 'Trading Income', 'व्यापारिक आय', 'income', 'credit', false, true, '4000', null, 4),
    ('4101', 'Fertilizer Sales', 'उर्वरक बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 5),
    ('4102', 'Seed Sales', 'बीज बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 6),
    ('5100', 'Direct Expenses', 'प्रत्यक्ष व्यय', 'expense', 'debit', false, true, '5000', null, 7),
    ('5101', 'Purchase', 'क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 8),
    ('2107', 'Member Deposits', 'सदस्य जमाराशि', 'liability', 'credit', false, false, '2100', 'deposit', 9),
    ('2109', 'Wages Payable', 'देय मज़दूरी', 'liability', 'credit', false, false, '2100', 'current_liability', 10),
    ('3307', 'TDS / TCS Receivable', 'प्राप्य TDS / TCS', 'asset', 'debit', false, false, '3300', 'current_asset', 11),
    ('2203', 'EPF Payable', 'देय EPF', 'liability', 'credit', false, false, '2200', 'statutory_liability', 12),
    ('2204', 'ESI Payable', 'देय ESI', 'liability', 'credit', false, false, '2200', 'statutory_liability', 13),
    ('5203', 'PF', 'भविष्य निधि (PF)', 'expense', 'debit', false, false, '5200', 'employee_expense', 14),
    ('5204', 'ESI', 'कर्मचारी बीमा (ESI)', 'expense', 'debit', false, false, '5200', 'employee_expense', 15),
    ('5209', 'EPF EDLI & Admin Charges', 'EPF EDLI व प्रशासनिक प्रभार', 'expense', 'debit', false, false, '5200', 'employee_expense', 16),
    ('2205', 'HRDF Payable', 'देय HRDF', 'liability', 'credit', false, false, '2200', 'statutory_liability', 17),
    ('3108', 'Accum. Dep. - Building', 'संचित ह्रास - भवन', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 18),
    ('3109', 'Accum. Dep. - Furniture', 'संचित ह्रास - फर्नीचर', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 19),
    ('3110', 'Accum. Dep. - Vehicle', 'संचित ह्रास - वाहन', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 20),
    ('3111', 'Accum. Dep. - Plant', 'संचित ह्रास - संयंत्र', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 21),
    ('3112', 'Accum. Dep. - Office Equip', 'संचित ह्रास - उपकरण', 'asset', 'credit', false, false, '3100', 'accumulated_dep', 22),
    ('3310', 'GST Input Credit (ITC)', 'GST इनपुट क्रेडिट (ITC)', 'asset', 'debit', false, false, '3300', 'current_asset', 23),
    ('3311', 'Prepaid Expenses', 'अग्रिम व्यय', 'asset', 'debit', false, false, '3300', 'current_asset', 24),
    ('5308', 'Rent', 'किराया व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 25),
    ('5309', 'Travelling Expenses', 'यात्रा व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 26),
    ('5310', 'Meeting / AGM Expenses', 'बैठक / AGM व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 27),
    ('5311', 'Education Fund Contribution', 'शिक्षा निधि अंशदान', 'expense', 'debit', false, false, '5300', 'admin_expense', 28),
    ('5505', 'Computer / Office Equip', 'कंप्यूटर / उपकरण ह्रास', 'expense', 'debit', false, false, '5500', 'depreciation_expense', 29),
    ('1209', 'Price Stabilization Fund', 'मूल्य स्थिरता निधि', 'equity', 'credit', false, false, '1200', 'reserve', 30),
    ('1210', 'Social / Cooperative Dev Fund', 'सहकारी विकास निधि', 'equity', 'credit', false, false, '1200', 'reserve', 31),
    ('1211', 'Dividend Distribution', 'लाभांश वितरण', 'equity', 'debit', false, false, '1200', 'reserve', 32),
    ('2206', 'Income Tax Payable', 'देय आयकर', 'liability', 'credit', false, false, '2200', 'statutory_liability', 33),
    ('2207', 'Professional Tax Payable', 'देय व्यावसायिक कर', 'liability', 'credit', false, false, '2200', 'statutory_liability', 34),
    ('2208', 'Interest Payable', 'देय ब्याज', 'liability', 'credit', false, false, '2100', 'current_liability', 35),
    ('2209', 'Audit Fee Payable', 'देय लेखा परीक्षण शुल्क', 'liability', 'credit', false, false, '2100', 'current_liability', 36),
    ('2210', 'Advance from Members', 'सदस्यों से अग्रिम', 'liability', 'credit', false, false, '2100', 'current_liability', 37),
    ('2211', 'Overdue Interest Reserve', 'अतिदेय ब्याज संचय', 'liability', 'credit', false, false, '2100', 'current_liability', 38),
    ('2304', 'Loan from DCCB/NABARD', 'DCCB/नाबार्ड से ऋण', 'liability', 'credit', false, false, '2300', 'long_term_loan', 39),
    ('2305', 'KCC / Crop Loan (DCCB)', 'KCC / फसल ऋण (DCCB)', 'liability', 'credit', false, false, '2300', 'long_term_loan', 40),
    ('3107', 'Computer / IT Equipment', 'कंप्यूटर / IT उपकरण', 'asset', 'debit', false, false, '3100', 'fixed_asset', 41),
    ('3207', 'NSC / Post Office Deposits', 'NSC / डाकघर जमा', 'asset', 'debit', false, false, '3200', 'investment', 42),
    ('3208', 'Cooperative Society Shares', 'सहकारी समिति शेयर', 'asset', 'debit', false, false, '3200', 'investment', 43),
    ('3312', 'Interest Receivable', 'प्राप्य ब्याज', 'asset', 'debit', false, false, '3300', 'current_asset', 44),
    ('3313', 'Member Loan Interest Rec.', 'सदस्य ऋण ब्याज प्राप्य', 'asset', 'debit', false, false, '3300', 'current_asset', 45),
    ('3314', 'Commission Receivable', 'प्राप्य कमीशन', 'asset', 'debit', false, false, '3300', 'current_asset', 46),
    ('3315', 'Advance to Employees', 'कर्मचारियों को अग्रिम', 'asset', 'debit', false, false, '3300', 'current_asset', 47),
    ('3316', 'Stock in Transit', 'पारगमन में माल', 'asset', 'debit', false, false, '3300', 'current_asset', 48),
    ('3406', 'Packing Material', 'पैकिंग सामग्री', 'asset', 'debit', false, false, '3400', 'inventory', 49),
    ('4207', 'Storage / Cold Storage Income', 'गोदाम / शीत भंडार आय', 'income', 'credit', false, false, '4200', 'commission_income', 50),
    ('4208', 'Service Charges', 'सेवा प्रभार', 'income', 'credit', false, false, '4200', 'commission_income', 51),
    ('4304', 'PM Kisan / DBT Income', 'पीएम किसान / DBT आय', 'income', 'credit', false, false, '4300', 'scheme_income', 52),
    ('4305', 'FPO / Farmer Group Income', 'FPO / कृषक समूह आय', 'income', 'credit', false, false, '4300', 'scheme_income', 53),
    ('4408', 'Interest on Member Loans', 'सदस्य ऋण पर ब्याज', 'income', 'credit', false, false, '4400', 'other_income', 54),
    ('4409', 'Bad Debt Recovery', 'अशोध्य ऋण वसूली', 'income', 'credit', false, false, '4400', 'other_income', 55),
    ('4410', 'Profit on Sale of Assets', 'संपत्ति बिक्री पर लाभ', 'income', 'credit', false, false, '4400', 'other_income', 56),
    ('5206', 'Gratuity Provision', 'उपदान प्रावधान', 'expense', 'debit', false, false, '5200', 'employee_expense', 57),
    ('5207', 'Employee Bonus', 'कर्मचारी बोनस', 'expense', 'debit', false, false, '5200', 'employee_expense', 58),
    ('5208', 'HRA / DA Allowance', 'HRA / DA भत्ता', 'expense', 'debit', false, false, '5200', 'employee_expense', 59),
    ('5312', 'Advertisement', 'विज्ञापन व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 60),
    ('5313', 'Postage / Courier', 'डाक / कूरियर व्यय', 'expense', 'debit', false, false, '5300', 'admin_expense', 61),
    ('5314', 'Bank Charges', 'बैंक प्रभार', 'expense', 'debit', false, false, '5300', 'admin_expense', 62),
    ('5315', 'Filing / Registration Fees', 'दाखिल / पंजीकरण शुल्क', 'expense', 'debit', false, false, '5300', 'admin_expense', 63),
    ('5404', 'Bad Debt Written Off', 'अशोध्य ऋण अपलेखन', 'expense', 'debit', false, false, '5400', 'operational_expense', 64),
    ('5405', 'Donation / CSR', 'दान / CSR व्यय', 'expense', 'debit', false, false, '5400', 'operational_expense', 65),
    ('5406', 'Loss on Sale of Assets', 'संपत्ति बिक्री पर हानि', 'expense', 'debit', false, false, '5400', 'operational_expense', 66),
    ('5407', 'Prior Period Adjustments', 'पूर्व अवधि समायोजन', 'expense', 'debit', false, false, '5400', 'operational_expense', 67),
    ('5603', 'Income Tax', 'आयकर व्यय', 'expense', 'debit', false, false, '5600', 'statutory_expense', 68),
    ('5604', 'Interest on Borrowings', 'उधार पर ब्याज व्यय', 'expense', 'debit', false, false, '5600', 'statutory_expense', 69),
    ('5605', 'Penalty / Fine', 'जुर्माना / दंड व्यय', 'expense', 'debit', false, false, '5600', 'statutory_expense', 70),
    ('4104', 'Pesticides Sales', 'कीटनाशक बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 71),
    ('4105', 'Animal Feed Sales', 'पशु आहार बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 72),
    ('4106', 'Agricultural Implements Sales', 'कृषि यंत्र बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 73),
    ('4107', 'PDS / Ration Goods Sales', 'सार्वजनिक वितरण बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 74),
    ('4108', 'Govt Procurement Sales', 'सरकारी खरीद बिक्री', 'income', 'credit', false, false, '4100', 'trading_income', 75),
    ('5110', 'Fertilizer Purchase', 'उर्वरक क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 76),
    ('5111', 'Seed Purchase', 'बीज क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 77),
    ('5112', 'Consumer Goods Purchase', 'उपभोक्ता वस्तु क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 78),
    ('5113', 'Pesticides Purchase', 'कीटनाशक क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 79),
    ('5114', 'Animal Feed Purchase', 'पशु आहार क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 80),
    ('5115', 'PDS / Ration Goods Purchase', 'सार्वजनिक वितरण क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 81),
    ('5116', 'Govt Procurement Purchase', 'सरकारी खरीद क्रय', 'expense', 'debit', false, false, '5100', 'direct_expense', 82),
    ('5150', 'Closing Stock (Trading A/c)', 'समापन माल (व्यापार खाता)', 'expense', 'credit', true, false, '5100', 'closing_stock', 83)
  ) as v(id, name, "nameHi", type, "openingBalanceType", "isSystem", "isGroup", "parentId", subtype, ord)
 where not v."isGroup"
   and not exists (select 1 from public.accounts a where a.society_id = s.society_id and a.id = v.id)
   and not exists (select 1 from public.accounts a where a.society_id = s.society_id and lower(trim(a.name)) = lower(trim(v.name)) and a.type = v.type)
   and (v."parentId" is null or exists (select 1 from public.accounts p where p.society_id = s.society_id and p.id = v."parentId"))
on conflict do nothing;

insert into public.app_migrations (version, name) values ('114', 'persist_shared_extra_accounts')
  on conflict (version) do nothing;

commit;

notify pgrst, 'reload schema';
