-- 115 · Round off (sales + purchases) and cash discount (purchases): 3 columns + 2 accounts.
-- GENERATED by scripts/gen-migration-115.mjs from the code's own ACCOUNTS_TO_ADD_115 list — do not edit by hand.
--
-- WHY: a sale can now be rounded to the rupee, and a purchase bill can carry a cash discount AFTER GST (GST / ITC
-- unchanged) plus a round off. The amounts are stored on the bill (step-2 extras, RULE 1) and posted to two new
-- accounts — 4499 Discount Received (other income) and 5499 Round Off (indirect expense) — which the app merges on
-- screen for every society; this persists them so the server accepts the first voucher on them.
--
-- WHAT: (1) add the columns sales."roundOff", purchases."cashDiscount", purchases."roundOff" (numeric default 0);
-- (2) for every society, add each account it lacks — skip when the id exists, when another account already shows
-- that code, or when an account with the same name and type exists; only where the parent group exists.
-- Opening balance 0. INSERT only, "on conflict do nothing": no existing row is changed or removed.
-- Run supabase/diagnostics/preview_115_round_off_cash_discount.sql first. Undo: 115_..._down.sql.
-- NO temp tables — the SQL Editor's "Run and enable RLS" splits statements.

begin;

alter table public.sales     add column if not exists "roundOff"     numeric default 0;
alter table public.purchases add column if not exists "cashDiscount" numeric default 0;
alter table public.purchases add column if not exists "roundOff"     numeric default 0;

insert into public.accounts (id, society_id, name, "nameHi", type, "openingBalance", "openingBalanceType", "isSystem", "isGroup", "parentId", subtype, jurisdiction)
select v.id, s.society_id, v.name, v."nameHi", v.type, 0, v."openingBalanceType", v."isSystem", v."isGroup", v."parentId", v.subtype,
       (select a.jurisdiction from public.accounts a where a.society_id = s.society_id and a.jurisdiction is not null limit 1)
  from (select distinct society_id from public.accounts) s
 cross join (values
    ('4499', 'Discount Received', 'प्राप्त छूट', 'income', 'credit', false, false, '4400', 'discount_received', 0),
    ('5499', 'Round Off', 'राउंड ऑफ', 'expense', 'debit', false, false, '5400', 'round_off', 1)
  ) as v(id, name, "nameHi", type, "openingBalanceType", "isSystem", "isGroup", "parentId", subtype, ord)
 where not exists (select 1 from public.accounts a where a.society_id = s.society_id and a.id = v.id)
   and not exists (select 1 from public.accounts a where a.society_id = s.society_id and a.code = v.id)
   and not exists (select 1 from public.accounts a where a.society_id = s.society_id and lower(trim(a.name)) = lower(trim(v.name)) and a.type = v.type)
   and exists (select 1 from public.accounts p where p.society_id = s.society_id and p.id = v."parentId")
on conflict do nothing;

insert into public.app_migrations (version, name) values ('115', 'round_off_cash_discount')
  on conflict (version) do nothing;

commit;

notify pgrst, 'reload schema';
