// AUTO-GENERATED by SahakarLekha_Book/split_guide.py — do not edit by hand.
// Single source of truth: the same markdown also builds the Word/PDF book.
export interface GuideEntry {
  slug: string;
  title: string;
  shortTitle: string;
  summary: string;
  kind: 'front' | 'chapter' | 'appendix' | 'back';
  num?: number;
}
export interface GuidePart { id: string; title: string; chapters: GuideEntry[]; }

export const FRONT_MATTER: GuideEntry = {
  "slug": "introduction",
  "title": "भूमिका",
  "shortTitle": "भूमिका",
  "summary": "💡 तीन सूत्र याद रखें: (1) ऐप औज़ार है, समझ आपकी; (2) छोटी सही आदतें किताबें बचाती हैं; (3) पारदर्शिता ही सहकारिता है।",
  "kind": "front"
};
export const GUIDE_PARTS: GuidePart[] = [
  {
    "id": "part-1",
    "title": "भाग 1 — लेखांकन की नींव",
    "chapters": [
      {
        "slug": "accounting-foundations",
        "title": "अध्याय 1 — लेखांकन की नींव: सहकारी समिति का हिसाब-किताब",
        "shortTitle": "लेखांकन की नींव: सहकारी समिति का हिसाब-किताब",
        "summary": "इस अध्याय के बाद आप कर पाएँगे: हिसाब-किताब का महत्व बताना; डेबिट-क्रेडिट लगाना; खातों के पाँच प्रकार पहचानना; लेखांकन समीकरण व चक्र समझना।",
        "kind": "chapter",
        "num": 1
      }
    ]
  },
  {
    "id": "part-2",
    "title": "भाग 2 — सहकार लेखा से शुरुआत",
    "chapters": [
      {
        "slug": "society-setup-and-roles",
        "title": "अध्याय 2 — पंजीकरण, समिति सेटअप व भूमिकाएँ",
        "shortTitle": "पंजीकरण, समिति सेटअप व भूमिकाएँ",
        "summary": "पंजीकरण, समिति सेटअप, 16 भूमिकाएँ व शाखा-सीमा, Maker-Checker, FY-लॉक, ऑनलाइन-only नियम व Dashboard।",
        "kind": "chapter",
        "num": 2
      },
      {
        "slug": "chart-of-accounts",
        "title": "अध्याय 3 — लेजर हेड (Chart of Accounts)",
        "shortTitle": "लेजर हेड (Chart of Accounts)",
        "summary": "ग्रुप बनाम खाता, समिति-प्रकार अनुसार कोड, नया खाता (प्रकार बाद में नहीं बदलता), खाता कब नहीं हटता व merge।",
        "kind": "chapter",
        "num": 3
      },
      {
        "slug": "opening-balances",
        "title": "अध्याय 4 — ओपनिंग बैलेंस (Opening Balances)",
        "shortTitle": "ओपनिंग बैलेंस (Opening Balances)",
        "summary": "सहकार लेखा पर आते समय एक बार opening डालना — Dr = Cr, समूह खाते की रोक, स्टॉक व पार्टी opening।",
        "kind": "chapter",
        "num": 4
      },
      {
        "slug": "member-management",
        "title": "अध्याय 5 — सदस्य व सदस्यता प्रबंधन",
        "shortTitle": "सदस्य व सदस्यता प्रबंधन",
        "summary": "सदस्य सीधे या आवेदन से जोड़ना, शेयर व प्रवेश शुल्क की अलग रसीद, पुराने सदस्य का opening, शेयर जोड़ना/वापसी/स्थानांतरण व प्रमाणपत्र-रिकॉर्ड।",
        "kind": "chapter",
        "num": 5
      }
    ]
  },
  {
    "id": "part-3",
    "title": "भाग 3 — दैनिक संचालन",
    "chapters": [
      {
        "slug": "voucher-types",
        "title": "अध्याय 6 — वाउचर प्रणाली: रसीद, भुगतान, जर्नल व कोंट्रा",
        "shortTitle": "वाउचर प्रणाली: रसीद, भुगतान, जर्नल व कोंट्रा",
        "summary": "चारों वाउचर प्रकार, आसान/विशेषज्ञ मोड, सर्वर से वाउचर नंबर, Maker-Checker अनुमोदन और edit/रद्द/रिवर्स के नियम।",
        "kind": "chapter",
        "num": 6
      },
      {
        "slug": "sales-entries",
        "title": "अध्याय 7 — बिक्री प्रबंधन (Sales)",
        "shortTitle": "बिक्री प्रबंधन (Sales)",
        "summary": "नकद/बैंक/उधार बिक्री, हर वस्तु का बिक्री खाता, GST व HSN, स्टॉक से ज़्यादा बिक्री पर रोक, Credit Note से बिक्री वापसी और शुद्ध बिक्री।",
        "kind": "chapter",
        "num": 7
      },
      {
        "slug": "purchase-entries",
        "title": "अध्याय 8 — खरीद प्रबंधन (Purchases)",
        "shortTitle": "खरीद प्रबंधन (Purchases)",
        "summary": "नकद/बैंक/उधार खरीद, हर वस्तु का खरीद खाता, ITC व HSN, TDS सिर्फ़ एक बार (194Q शर्तें), Debit Note से खरीद वापसी और शुद्ध क्रय।",
        "kind": "chapter",
        "num": 8
      },
      {
        "slug": "inventory-management",
        "title": "अध्याय 9 — स्टॉक (Inventory)",
        "shortTitle": "स्टॉक (Inventory)",
        "summary": "वस्तु बनाना (बिक्री/खरीद खाता ज़रूरी), माल समूह, प्रारंभिक स्टॉक, आवाजाही, मैनुअल समायोजन और समापन माल का एक ही नियम।",
        "kind": "chapter",
        "num": 9
      },
      {
        "slug": "bill-wise-settlement",
        "title": "अध्याय 10 — बिल-वार निपटान",
        "shortTitle": "बिल-वार निपटान",
        "summary": "उधार बिल पर वसूली/भुगतान लगाना, आंशिक व पुराने-पहले बँटवारा, अग्रिम/On Account, बकाया बिल की उम्र।",
        "kind": "chapter",
        "num": 10
      },
      {
        "slug": "salary-management",
        "title": "अध्याय 11 — वेतन प्रबंधन (Salary)",
        "shortTitle": "वेतन प्रबंधन (Salary)",
        "summary": "वेतन प्रोसेसिंग (accrual journal), \"भुगतान चिह्नित करें\" से भुगतान, cumulative TDS, PT हाथ से, Form 24Q व स्लिप PDF।",
        "kind": "chapter",
        "num": 11
      }
    ]
  },
  {
    "id": "part-4",
    "title": "भाग 4 — बहियाँ व ट्रायल बैलेंस",
    "chapters": [
      {
        "slug": "daybook-and-ledger",
        "title": "अध्याय 12 — डे बुक (Day Book) व लेजर (Ledger)",
        "shortTitle": "डे बुक (Day Book) व लेजर (Ledger)",
        "summary": "रोजनामचा (Day Book) व खाता-बही पढ़ना, तिथि फ़िल्टर, चालू शेष और ऑडिट ट्रेल में बदलाव खोजना।",
        "kind": "chapter",
        "num": 12
      },
      {
        "slug": "trial-balance",
        "title": "अध्याय 13 — ट्रायल बैलेंस (Trial Balance)",
        "shortTitle": "ट्रायल बैलेंस (Trial Balance)",
        "summary": "इस अध्याय के बाद आप: ट्रायल बैलेंस बनाना व पढ़ना; Dr=Cr का महत्व; NCDC दो-खंड प्रारूप; न मिलने पर निदान।",
        "kind": "chapter",
        "num": 13
      }
    ]
  },
  {
    "id": "part-5",
    "title": "भाग 5 — अंतिम खाते",
    "chapters": [
      {
        "slug": "trading-account",
        "title": "अध्याय 14 — व्यापार खाता (Trading Account)",
        "shortTitle": "व्यापार खाता (Trading Account)",
        "summary": "इस अध्याय के बाद आप: ग्रॉस प्रॉफ़िट; प्रारंभिक+खरीद−समापन; गतिविधि-वार ब्योरा; क्लोज़िंग स्टॉक का सही मूल्य।",
        "kind": "chapter",
        "num": 14
      },
      {
        "slug": "income-and-expenditure",
        "title": "अध्याय 15 — आमदनी-खर्च खाता (Income & Expenditure)",
        "shortTitle": "आमदनी-खर्च खाता (Income & Expenditure)",
        "summary": "इस अध्याय के बाद आप: नेट प्रॉफ़िट/घाटा; ग्रॉस प्रॉफ़िट का अंतरण; प्रत्यक्ष व अप्रत्यक्ष व्यय; पूँजी बनाम राजस्व।",
        "kind": "chapter",
        "num": 15
      },
      {
        "slug": "balance-sheet",
        "title": "अध्याय 16 — बैलेंस शीट (Balance Sheet)",
        "shortTitle": "बैलेंस शीट (Balance Sheet)",
        "summary": "बैलेंस शीट — संपत्ति = पूँजी + देनदारी, समापन माल का एक नियम, दिनांक तक/अंतरिम, सारांश/पूर्ण विवरण, सत्यापन बॉक्स और हिंदी/द्विभाषी रिपोर्ट PDF।",
        "kind": "chapter",
        "num": 16
      },
      {
        "slug": "receipts-and-payments",
        "title": "अध्याय 17 — रसीद-भुगतान खाता (Receipts & Payments)",
        "shortTitle": "रसीद-भुगतान खाता (Receipts & Payments)",
        "summary": "इस अध्याय के बाद आप: नकदी-आधार सारांश; पूँजी बनाम राजस्व; कोंट्रा का बहिष्करण; प्रारंभिक/समापन नकद-बैंक।",
        "kind": "chapter",
        "num": 17
      }
    ]
  },
  {
    "id": "part-6",
    "title": "भाग 6 — कर अनुपालन",
    "chapters": [
      {
        "slug": "gst-management",
        "title": "अध्याय 18 — GST प्रबंधन",
        "shortTitle": "GST प्रबंधन",
        "summary": "GST सारांश पेज — GSTR-1/3B/माह-वार मिलान, PDF/JSON निर्यात, HSN/SAC चेतावनी, Credit/Debit Note का असर।",
        "kind": "chapter",
        "num": 18
      },
      {
        "slug": "tds-and-26q",
        "title": "अध्याय 19 — TDS व क्वार्टरली रिटर्न (26Q)",
        "shortTitle": "TDS व क्वार्टरली रिटर्न (26Q)",
        "summary": "TDS कब बनता है और कितना — आयकर अधिनियम 2025 (धारा 393) की मुख्य पंक्तियाँ, दरें व सीमाएँ; एक-बार कटौती; देय TDS जमा; TDS रजिस्टर व तिमाही विवरण।",
        "kind": "chapter",
        "num": 19
      }
    ]
  },
  {
    "id": "part-7",
    "title": "भाग 7 — विशेष लेखांकन",
    "chapters": [
      {
        "slug": "depreciation",
        "title": "अध्याय 20 — डेप्रिसिएशन (Depreciation)",
        "shortTitle": "डेप्रिसिएशन (Depreciation)",
        "summary": "SLM/WDV, पहले साल समय-अनुपात ह्रास, संपत्ति रजिस्टर से \"ह्रास पोस्ट करें\", ह्रास अनुसूची, निपटान एंट्री।",
        "kind": "chapter",
        "num": 20
      },
      {
        "slug": "stock-valuation",
        "title": "अध्याय 21 — स्टॉक वैल्यूएशन (Stock Valuation)",
        "shortTitle": "स्टॉक वैल्यूएशन (Stock Valuation)",
        "summary": "भारित औसत बनाम FIFO, ऐप का एक नियम (मात्रा × भारित औसत लागत), स्टॉक वैल्यूएशन व समापन माल रिपोर्ट, ₹0 मूल्य की जाँच।",
        "kind": "chapter",
        "num": 21
      },
      {
        "slug": "profit-distribution",
        "title": "अध्याय 22 — लाभ का बँटवारा (Profit Distribution)",
        "shortTitle": "लाभ का बँटवारा (Profit Distribution)",
        "summary": "शुद्ध लाभ (कर्मचारी बोनस घटाकर); संचय, अशोध्य ऋण व शिक्षा निधि; लाभांश सीमा — हरियाणा के स्रोत-सहित आँकड़े; बँटवारे की एंट्री।",
        "kind": "chapter",
        "num": 22
      },
      {
        "slug": "statutory-returns",
        "title": "अध्याय 23 — कानूनी रिटर्न व संघ रिपोर्ट",
        "shortTitle": "कानूनी रिटर्न व संघ रिपोर्ट",
        "summary": "सहकारी वार्षिक विवरणी के 8 भाग, सदस्य/NPA/उधार-फंड नियम, और ऐप के बाकी कानूनी प्रपत्र व अनुपालन कैलेंडर।",
        "kind": "chapter",
        "num": 23
      }
    ]
  },
  {
    "id": "part-8",
    "title": "भाग 8 — साल के अंत व सुरक्षा",
    "chapters": [
      {
        "slug": "year-end-and-fy-lock",
        "title": "अध्याय 24 — साल के अंत प्रक्रिया व FY-लॉक",
        "shortTitle": "साल के अंत प्रक्रिया व FY-लॉक",
        "summary": "साल के अंत के चार कदम — चेकलिस्ट, FY-लॉक, रोलओवर से नया वर्ष, और पुराने वर्ष को close करना (समापन माल व शुद्ध अधिशेष सहित); opening अपने-आप।",
        "kind": "chapter",
        "num": 24
      },
      {
        "slug": "audit-preparation",
        "title": "अध्याय 25 — ऑडिट तैयारी",
        "shortTitle": "ऑडिट तैयारी",
        "summary": "ऑडिट-फ़ाइल, ऑडिट रजिस्टर में आपत्तियाँ, ऑडिट प्रमाणपत्र व राज्य-वार ऑडिट अनुसूचियाँ, हिंदी/द्विभाषी रिपोर्ट PDF और सामान्य आपत्तियों से बचाव।",
        "kind": "chapter",
        "num": 25
      },
      {
        "slug": "data-security-and-backup",
        "title": "अध्याय 26 — डेटा सुरक्षा व बैकअप",
        "shortTitle": "डेटा सुरक्षा व बैकअप",
        "summary": "डेटा कैसे अलग व सुरक्षित रहता है, 16 भूमिकाएँ व अलग लॉगिन, 2FA व पासवर्ड रीसेट, online-only नियम, और डेटा एक्सपोर्ट / पूर्ण आर्काइव (.slbak) / रिस्टोर सेंटर का सही इस्तेमाल।",
        "kind": "chapter",
        "num": 26
      }
    ]
  },
  {
    "id": "part-9",
    "title": "भाग 9 — संदर्भ व अभ्यास",
    "chapters": [
      {
        "slug": "golden-rules",
        "title": "अध्याय 27 — सहकारी लेखांकन के सुनहरे नियम",
        "shortTitle": "सहकारी लेखांकन के सुनहरे नियम",
        "summary": "इस अध्याय के बाद आप: रोज़मर्रा के लिए याद रखने योग्य सिद्धांत व चेतावनियाँ।",
        "kind": "chapter",
        "num": 27
      },
      {
        "slug": "case-study-full-year",
        "title": "अध्याय 28 — समग्र केस-स्टडी: रानिया सहकारी समिति (पूर्ण वर्ष)",
        "shortTitle": "समग्र केस-स्टडी: रानिया सहकारी समिति (पूर्ण वर्ष)",
        "summary": "उद्देश्य: एक पूरे वर्ष का लेखांकन — ओपनिंग बैलेंस से अंतिम खातों व बँटवारा तक — एक सूत्र में, जो ₹5,42,500 पर मिलता है।",
        "kind": "chapter",
        "num": 28
      },
      {
        "slug": "special-registers",
        "title": "अध्याय 29 — विशिष्ट रजिस्टर व रिकॉर्ड",
        "shortTitle": "विशिष्ट रजिस्टर व रिकॉर्ड",
        "summary": "सहकारी रजिस्टर ऐप में कहाँ, खाते से मासिक मिलान, निर्यात व खाली प्रारूप।",
        "kind": "chapter",
        "num": 29
      },
      {
        "slug": "comprehensive-faq",
        "title": "अध्याय 30 — समग्र FAQ (सबसे आम 30 प्रश्न)",
        "shortTitle": "समग्र FAQ (सबसे आम 30 प्रश्न)",
        "summary": "सहकार लेखा उपयोग में पूछे जाने वाले शीर्ष प्रश्न-उत्तर — त्वरित संदर्भ।",
        "kind": "chapter",
        "num": 30
      }
    ]
  },
  {
    "id": "part-10",
    "title": "भाग 10 — वाउचर एंट्री: गहन संदर्भ",
    "chapters": [
      {
        "slug": "msp-procurement-entries",
        "title": "अध्याय 31 — विपणन/MSP समिति एंट्री (HAFED, बारदाना, सूखत)",
        "shortTitle": "विपणन/MSP समिति एंट्री (HAFED, बारदाना, सूखत)",
        "summary": "MSP एजेंट मॉडल — लॉट → J-Form → पोस्ट (3308/2105) → निपटान → भुगतान → कमीशन (3314/4206) → एजेंसी रसीद; बारदाना/सूखत हाथ से।",
        "kind": "chapter",
        "num": 31
      },
      {
        "slug": "society-type-entries",
        "title": "अध्याय 32 — समिति-प्रकार-वार एंट्री (दुग्ध, उपभोक्ता, बुनकर, मत्स्य, श्रमिक, SHG)",
        "shortTitle": "समिति-प्रकार-वार एंट्री (दुग्ध, उपभोक्ता, बुनकर, मत्स्य, श्रमिक, SHG)",
        "summary": "दुग्ध, उपभोक्ता, श्रमिक, आवास के ऐप-मॉड्यूल की एंट्री व बुनकर/मत्स्य/SHG की सामान्य-वाउचर एंट्री।",
        "kind": "chapter",
        "num": 32
      },
      {
        "slug": "error-rectification-entries",
        "title": "अध्याय 33 — त्रुटि-सुधार व जटिल/संदिग्ध एंट्री",
        "shortTitle": "त्रुटि-सुधार व जटिल/संदिग्ध एंट्री",
        "summary": "गलती का प्रकार पहचानना; edit, रद्द या रिवर्स चुनना; सुधार-जर्नल, Suspense व मिश्रित एंट्री।",
        "kind": "chapter",
        "num": 33
      },
      {
        "slug": "financial-ratios-and-lifecycle",
        "title": "अध्याय 34 — वित्तीय संकेतक, अनुपात व समिति-जीवनचक्र",
        "shortTitle": "वित्तीय संकेतक, अनुपात व समिति-जीवनचक्र",
        "summary": "वित्तीय अनुपात (शैक्षिक) — वसूली %, चालू अनुपात, मार्जिन, NPA, ऐप का विश्लेषण पेज व कैलकुलेटर; गठन से समापन तक की एंट्री।",
        "kind": "chapter",
        "num": 34
      },
      {
        "slug": "expense-dictionary",
        "title": "अध्याय 35 — विस्तृत व्यय-कोश व विविध सहकारी गतिविधियाँ",
        "shortTitle": "विस्तृत व्यय-कोश व विविध सहकारी गतिविधियाँ",
        "summary": "इस अध्याय के बाद आप: हर प्रकार के खर्च की सही एंट्री; और किराया/हायरिंग/भंडारण जैसी सेवा-आय।",
        "kind": "chapter",
        "num": 35
      }
    ]
  },
  {
    "id": "parishisht",
    "title": "परिशिष्ट · Appendices",
    "chapters": [
      {
        "slug": "standard-chart-of-accounts",
        "title": "परिशिष्ट A — मानक खाता-चार्ट (Chart of Accounts)",
        "shortTitle": "मानक खाता-चार्ट (Chart of Accounts)",
        "summary": "सहकार लेखा में तैयार मिलने वाले प्रमुख खाते — कोड, नाम, श्रेणी व रिपोर्ट।",
        "kind": "appendix"
      },
      {
        "slug": "glossary",
        "title": "परिशिष्ट B — शब्दावली (Glossary)",
        "shortTitle": "शब्दावली (Glossary)",
        "summary": "इस गाइड में आने वाले लेखांकन के मुख्य शब्दों (डेबिट, क्रेडिट, वाउचर, खाता-बही आदि) के आसान हिन्दी अर्थ — एक तालिका में।",
        "kind": "appendix"
      },
      {
        "slug": "report-to-statutory-form-map",
        "title": "परिशिष्ट C — रिपोर्ट → कानूनी प्रपत्र मानचित्र",
        "shortTitle": "रिपोर्ट → कानूनी प्रपत्र मानचित्र",
        "summary": "सहकार लेखा की कौन-सी रिपोर्ट किस कानूनी प्रपत्र या उपयोग में लगती है — ट्रायल बैलेंस, व्यापार खाता, आमदनी-खर्च, बैलेंस शीट आदि का मानचित्र।",
        "kind": "appendix"
      },
      {
        "slug": "quick-reference-card",
        "title": "परिशिष्ट D — त्वरित-संदर्भ कार्ड",
        "shortTitle": "त्वरित-संदर्भ कार्ड",
        "summary": "एक नज़र में: डेबिट-क्रेडिट के नियम, कौन-सा वाउचर चुनें, ज़रूरी सूत्र और नियत तारीख़ें — समिति के लेखाकार का त्वरित-संदर्भ कार्ड।",
        "kind": "appendix"
      },
      {
        "slug": "year-end-checklist",
        "title": "परिशिष्ट E — साल के अंत चेकलिस्ट (प्रिंट-योग्य)",
        "shortTitle": "साल के अंत चेकलिस्ट (प्रिंट-योग्य)",
        "summary": "साल के अंत की प्रिंट-योग्य चेकलिस्ट — वाउचर, बैंक मिलान, स्टॉक-गणना से लेकर FY लॉक तक, हर काम के आगे टिक करने का खाना।",
        "kind": "appendix"
      },
      {
        "slug": "exercise-answers",
        "title": "परिशिष्ट F — अभ्यास-उत्तर (चुनिंदा)",
        "shortTitle": "अभ्यास-उत्तर (चुनिंदा)",
        "summary": "स्वयं हल करने के बाद मिलाएँ; विधि महत्वपूर्ण है, केवल उत्तर नहीं।",
        "kind": "appendix"
      },
      {
        "slug": "voucher-entry-quick-reference",
        "title": "परिशिष्ट G — वाउचर एंट्री त्वरित-संदर्भ (विपणन व समिति-प्रकार)",
        "shortTitle": "वाउचर एंट्री त्वरित-संदर्भ (विपणन व समिति-प्रकार)",
        "summary": "अध्याय 31–35 की सबसे आम एंट्री एक नज़र में। (मूल बातें परिशिष्ट D में।)",
        "kind": "appendix"
      },
      {
        "slug": "account-name-glossary",
        "title": "परिशिष्ट H — खाता-नाम कोश (हिंदी ↔ English)",
        "shortTitle": "खाता-नाम कोश (हिंदी ↔ English)",
        "summary": "सॉफ़्टवेयर/रिपोर्ट में सही अंग्रेज़ी नाम। श्रेणी: सं=संपत्ति, दे=देनदारी, पूँ=पूँजी, आ=आय, व्य=व्यय।",
        "kind": "appendix"
      },
      {
        "slug": "troubleshooting-guide",
        "title": "परिशिष्ट I — समस्या-समाधान व संदिग्ध स्थितियाँ",
        "shortTitle": "समस्या-समाधान व संदिग्ध स्थितियाँ",
        "summary": "समस्या → कारण → समाधान तालिका: ट्रायल बैलेंस न मिलना, नकद ऋणात्मक होना जैसी दिक़्क़तें, और संदिग्ध एंट्रियों के लिए निर्णय-कुंजी।",
        "kind": "appendix"
      },
      {
        "slug": "society-type-quick-card",
        "title": "परिशिष्ट J — समिति-प्रकार Quick Card व अभ्यास-बैंक",
        "shortTitle": "समिति-प्रकार Quick Card व अभ्यास-बैंक",
        "summary": "1. MSP गेहूँ 100 क्विं × ₹2,275 खरीद + किसान भुगतान (₹40,000 ऋण-कटौती)।",
        "kind": "appendix"
      }
    ]
  }
];
export const BACK_MATTER: GuideEntry = {
  "slug": "conclusion",
  "title": "समापन — एक अंतिम शब्द",
  "shortTitle": "समापन",
  "summary": "💡 तीन सूत्र, फिर से: (1) ऐप औज़ार है, समझ आपकी — सहकार लेखा गणना करता है, पर सही एंट्री व सही वर्गीकरण आप तय करते हैं। (2) छोटी सही आदतें किताबें बचाती हैं — रोज़ एंट्री, माह-अंत मिलान, समय पर कर, नियमित बैकअप। (3) पारदर्शिता ही सहकारिता है — हर सदस्य का भरोसा सही, खुले, मिलते हुए खातों से बनता है।",
  "kind": "back"
};

// flat reading order (front -> all chapters -> appendices -> back), for prev/next nav
export const GUIDE_ORDER: { slug: string; shortTitle: string; title: string }[] = [
  {
    "slug": "introduction",
    "shortTitle": "भूमिका",
    "title": "भूमिका"
  },
  {
    "slug": "accounting-foundations",
    "shortTitle": "लेखांकन की नींव: सहकारी समिति का हिसाब-किताब",
    "title": "अध्याय 1 — लेखांकन की नींव: सहकारी समिति का हिसाब-किताब"
  },
  {
    "slug": "society-setup-and-roles",
    "shortTitle": "पंजीकरण, समिति सेटअप व भूमिकाएँ",
    "title": "अध्याय 2 — पंजीकरण, समिति सेटअप व भूमिकाएँ"
  },
  {
    "slug": "chart-of-accounts",
    "shortTitle": "लेजर हेड (Chart of Accounts)",
    "title": "अध्याय 3 — लेजर हेड (Chart of Accounts)"
  },
  {
    "slug": "opening-balances",
    "shortTitle": "ओपनिंग बैलेंस (Opening Balances)",
    "title": "अध्याय 4 — ओपनिंग बैलेंस (Opening Balances)"
  },
  {
    "slug": "member-management",
    "shortTitle": "सदस्य व सदस्यता प्रबंधन",
    "title": "अध्याय 5 — सदस्य व सदस्यता प्रबंधन"
  },
  {
    "slug": "voucher-types",
    "shortTitle": "वाउचर प्रणाली: रसीद, भुगतान, जर्नल व कोंट्रा",
    "title": "अध्याय 6 — वाउचर प्रणाली: रसीद, भुगतान, जर्नल व कोंट्रा"
  },
  {
    "slug": "sales-entries",
    "shortTitle": "बिक्री प्रबंधन (Sales)",
    "title": "अध्याय 7 — बिक्री प्रबंधन (Sales)"
  },
  {
    "slug": "purchase-entries",
    "shortTitle": "खरीद प्रबंधन (Purchases)",
    "title": "अध्याय 8 — खरीद प्रबंधन (Purchases)"
  },
  {
    "slug": "inventory-management",
    "shortTitle": "स्टॉक (Inventory)",
    "title": "अध्याय 9 — स्टॉक (Inventory)"
  },
  {
    "slug": "bill-wise-settlement",
    "shortTitle": "बिल-वार निपटान",
    "title": "अध्याय 10 — बिल-वार निपटान"
  },
  {
    "slug": "salary-management",
    "shortTitle": "वेतन प्रबंधन (Salary)",
    "title": "अध्याय 11 — वेतन प्रबंधन (Salary)"
  },
  {
    "slug": "daybook-and-ledger",
    "shortTitle": "डे बुक (Day Book) व लेजर (Ledger)",
    "title": "अध्याय 12 — डे बुक (Day Book) व लेजर (Ledger)"
  },
  {
    "slug": "trial-balance",
    "shortTitle": "ट्रायल बैलेंस (Trial Balance)",
    "title": "अध्याय 13 — ट्रायल बैलेंस (Trial Balance)"
  },
  {
    "slug": "trading-account",
    "shortTitle": "व्यापार खाता (Trading Account)",
    "title": "अध्याय 14 — व्यापार खाता (Trading Account)"
  },
  {
    "slug": "income-and-expenditure",
    "shortTitle": "आमदनी-खर्च खाता (Income & Expenditure)",
    "title": "अध्याय 15 — आमदनी-खर्च खाता (Income & Expenditure)"
  },
  {
    "slug": "balance-sheet",
    "shortTitle": "बैलेंस शीट (Balance Sheet)",
    "title": "अध्याय 16 — बैलेंस शीट (Balance Sheet)"
  },
  {
    "slug": "receipts-and-payments",
    "shortTitle": "रसीद-भुगतान खाता (Receipts & Payments)",
    "title": "अध्याय 17 — रसीद-भुगतान खाता (Receipts & Payments)"
  },
  {
    "slug": "gst-management",
    "shortTitle": "GST प्रबंधन",
    "title": "अध्याय 18 — GST प्रबंधन"
  },
  {
    "slug": "tds-and-26q",
    "shortTitle": "TDS व क्वार्टरली रिटर्न (26Q)",
    "title": "अध्याय 19 — TDS व क्वार्टरली रिटर्न (26Q)"
  },
  {
    "slug": "depreciation",
    "shortTitle": "डेप्रिसिएशन (Depreciation)",
    "title": "अध्याय 20 — डेप्रिसिएशन (Depreciation)"
  },
  {
    "slug": "stock-valuation",
    "shortTitle": "स्टॉक वैल्यूएशन (Stock Valuation)",
    "title": "अध्याय 21 — स्टॉक वैल्यूएशन (Stock Valuation)"
  },
  {
    "slug": "profit-distribution",
    "shortTitle": "लाभ का बँटवारा (Profit Distribution)",
    "title": "अध्याय 22 — लाभ का बँटवारा (Profit Distribution)"
  },
  {
    "slug": "statutory-returns",
    "shortTitle": "कानूनी रिटर्न व संघ रिपोर्ट",
    "title": "अध्याय 23 — कानूनी रिटर्न व संघ रिपोर्ट"
  },
  {
    "slug": "year-end-and-fy-lock",
    "shortTitle": "साल के अंत प्रक्रिया व FY-लॉक",
    "title": "अध्याय 24 — साल के अंत प्रक्रिया व FY-लॉक"
  },
  {
    "slug": "audit-preparation",
    "shortTitle": "ऑडिट तैयारी",
    "title": "अध्याय 25 — ऑडिट तैयारी"
  },
  {
    "slug": "data-security-and-backup",
    "shortTitle": "डेटा सुरक्षा व बैकअप",
    "title": "अध्याय 26 — डेटा सुरक्षा व बैकअप"
  },
  {
    "slug": "golden-rules",
    "shortTitle": "सहकारी लेखांकन के सुनहरे नियम",
    "title": "अध्याय 27 — सहकारी लेखांकन के सुनहरे नियम"
  },
  {
    "slug": "case-study-full-year",
    "shortTitle": "समग्र केस-स्टडी: रानिया सहकारी समिति (पूर्ण वर्ष)",
    "title": "अध्याय 28 — समग्र केस-स्टडी: रानिया सहकारी समिति (पूर्ण वर्ष)"
  },
  {
    "slug": "special-registers",
    "shortTitle": "विशिष्ट रजिस्टर व रिकॉर्ड",
    "title": "अध्याय 29 — विशिष्ट रजिस्टर व रिकॉर्ड"
  },
  {
    "slug": "comprehensive-faq",
    "shortTitle": "समग्र FAQ (सबसे आम 30 प्रश्न)",
    "title": "अध्याय 30 — समग्र FAQ (सबसे आम 30 प्रश्न)"
  },
  {
    "slug": "msp-procurement-entries",
    "shortTitle": "विपणन/MSP समिति एंट्री (HAFED, बारदाना, सूखत)",
    "title": "अध्याय 31 — विपणन/MSP समिति एंट्री (HAFED, बारदाना, सूखत)"
  },
  {
    "slug": "society-type-entries",
    "shortTitle": "समिति-प्रकार-वार एंट्री (दुग्ध, उपभोक्ता, बुनकर, मत्स्य, श्रमिक, SHG)",
    "title": "अध्याय 32 — समिति-प्रकार-वार एंट्री (दुग्ध, उपभोक्ता, बुनकर, मत्स्य, श्रमिक, SHG)"
  },
  {
    "slug": "error-rectification-entries",
    "shortTitle": "त्रुटि-सुधार व जटिल/संदिग्ध एंट्री",
    "title": "अध्याय 33 — त्रुटि-सुधार व जटिल/संदिग्ध एंट्री"
  },
  {
    "slug": "financial-ratios-and-lifecycle",
    "shortTitle": "वित्तीय संकेतक, अनुपात व समिति-जीवनचक्र",
    "title": "अध्याय 34 — वित्तीय संकेतक, अनुपात व समिति-जीवनचक्र"
  },
  {
    "slug": "expense-dictionary",
    "shortTitle": "विस्तृत व्यय-कोश व विविध सहकारी गतिविधियाँ",
    "title": "अध्याय 35 — विस्तृत व्यय-कोश व विविध सहकारी गतिविधियाँ"
  },
  {
    "slug": "standard-chart-of-accounts",
    "shortTitle": "मानक खाता-चार्ट (Chart of Accounts)",
    "title": "परिशिष्ट A — मानक खाता-चार्ट (Chart of Accounts)"
  },
  {
    "slug": "glossary",
    "shortTitle": "शब्दावली (Glossary)",
    "title": "परिशिष्ट B — शब्दावली (Glossary)"
  },
  {
    "slug": "report-to-statutory-form-map",
    "shortTitle": "रिपोर्ट → कानूनी प्रपत्र मानचित्र",
    "title": "परिशिष्ट C — रिपोर्ट → कानूनी प्रपत्र मानचित्र"
  },
  {
    "slug": "quick-reference-card",
    "shortTitle": "त्वरित-संदर्भ कार्ड",
    "title": "परिशिष्ट D — त्वरित-संदर्भ कार्ड"
  },
  {
    "slug": "year-end-checklist",
    "shortTitle": "साल के अंत चेकलिस्ट (प्रिंट-योग्य)",
    "title": "परिशिष्ट E — साल के अंत चेकलिस्ट (प्रिंट-योग्य)"
  },
  {
    "slug": "exercise-answers",
    "shortTitle": "अभ्यास-उत्तर (चुनिंदा)",
    "title": "परिशिष्ट F — अभ्यास-उत्तर (चुनिंदा)"
  },
  {
    "slug": "voucher-entry-quick-reference",
    "shortTitle": "वाउचर एंट्री त्वरित-संदर्भ (विपणन व समिति-प्रकार)",
    "title": "परिशिष्ट G — वाउचर एंट्री त्वरित-संदर्भ (विपणन व समिति-प्रकार)"
  },
  {
    "slug": "account-name-glossary",
    "shortTitle": "खाता-नाम कोश (हिंदी ↔ English)",
    "title": "परिशिष्ट H — खाता-नाम कोश (हिंदी ↔ English)"
  },
  {
    "slug": "troubleshooting-guide",
    "shortTitle": "समस्या-समाधान व संदिग्ध स्थितियाँ",
    "title": "परिशिष्ट I — समस्या-समाधान व संदिग्ध स्थितियाँ"
  },
  {
    "slug": "society-type-quick-card",
    "shortTitle": "समिति-प्रकार Quick Card व अभ्यास-बैंक",
    "title": "परिशिष्ट J — समिति-प्रकार Quick Card व अभ्यास-बैंक"
  },
  {
    "slug": "conclusion",
    "shortTitle": "समापन",
    "title": "समापन — एक अंतिम शब्द"
  }
];

// raw markdown for every entry, keyed by "./<slug>.md"
const RAW = import.meta.glob('./*.md', { query: '?raw', import: 'default', eager: true }) as Record<string, string>;
export function loadGuideRaw(slug: string): string | null {
  return RAW['./' + slug + '.md'] ?? null;
}
export function findEntry(slug: string): GuideEntry | null {
  if (FRONT_MATTER.slug === slug) return FRONT_MATTER;
  if (BACK_MATTER.slug === slug) return BACK_MATTER;
  for (const p of GUIDE_PARTS) {
    const f = p.chapters.find((c) => c.slug === slug);
    if (f) return f;
  }
  return null;
}
