// AUTO-GENERATED by SahakarLekha_Book/split_guide.py — do not edit by hand.
// Single source of truth: the same markdown also builds the Word/PDF book.
export interface GuideEntry {
  slug: string;
  title: string;
  shortTitle: string;
  summary: string;
  kind: 'front' | 'chapter' | 'appendix' | 'back';
  num?: number;
}
export interface GuidePart { id: string; title: string; chapters: GuideEntry[]; }

export const FRONT_MATTER: GuideEntry = {
  "slug": "bhumika",
  "title": "भूमिका",
  "shortTitle": "भूमिका",
  "summary": "💡 तीन सूत्र याद रखें: (1) ऐप औज़ार है, समझ आपकी; (2) छोटी सही आदतें किताबें बचाती हैं; (3) पारदर्शिता ही सहकारिता है।",
  "kind": "front"
};
export const GUIDE_PARTS: GuidePart[] = [
  {
    "id": "bhag-1",
    "title": "भाग 1 — लेखांकन की नींव",
    "chapters": [
      {
        "slug": "adhyay-1",
        "title": "अध्याय 1 — लेखांकन की नींव: सहकारी समिति का हिसाब-किताब",
        "shortTitle": "लेखांकन की नींव: सहकारी समिति का हिसाब-किताब",
        "summary": "इस अध्याय के बाद आप कर पाएँगे: हिसाब-किताब का महत्व बताना; डेबिट-क्रेडिट लगाना; खातों के पाँच प्रकार पहचानना; लेखांकन समीकरण व चक्र समझना।",
        "kind": "chapter",
        "num": 1
      }
    ]
  },
  {
    "id": "bhag-2",
    "title": "भाग 2 — सहकार लेखा से शुरुआत",
    "chapters": [
      {
        "slug": "adhyay-2",
        "title": "अध्याय 2 — पंजीकरण, समिति सेटअप व भूमिकाएँ",
        "shortTitle": "पंजीकरण, समिति सेटअप व भूमिकाएँ",
        "summary": "इस अध्याय के बाद आप: नई समिति बनाना; समिति-विवरण व वित्तीय वर्ष सेट करना; भूमिकाएँ व Maker-Checker; Dashboard पढ़ना।",
        "kind": "chapter",
        "num": 2
      },
      {
        "slug": "adhyay-3",
        "title": "अध्याय 3 — खाता-शीर्ष (Chart of Accounts)",
        "shortTitle": "खाता-शीर्ष (Chart of Accounts)",
        "summary": "इस अध्याय के बाद आप: समूह व उप-खाते का फ़र्क; कोड प्रणाली; मानक चार्ट; नया खाता जोड़ना।",
        "kind": "chapter",
        "num": 3
      },
      {
        "slug": "adhyay-4",
        "title": "अध्याय 4 — प्रारंभिक शेष (Opening Balances)",
        "shortTitle": "प्रारंभिक शेष (Opening Balances)",
        "summary": "इस अध्याय के बाद आप: पिछले वर्ष का समापन इस वर्ष के प्रारंभ में लाना; Dr=Cr मिलान; \"तुलन-पत्र क्यों नहीं मिल रहा\" की जड़।",
        "kind": "chapter",
        "num": 4
      },
      {
        "slug": "adhyay-5",
        "title": "अध्याय 5 — सदस्य व सदस्यता प्रबंधन",
        "shortTitle": "सदस्य व सदस्यता प्रबंधन",
        "summary": "इस अध्याय के बाद आप: सदस्य जोड़ना व अनुमोदन; शेयर पूँजी व प्रवेश शुल्क की अलग प्रविष्टि; सदस्य-बही; निकासी पर शेयर-वापसी।",
        "kind": "chapter",
        "num": 5
      }
    ]
  },
  {
    "id": "bhag-3",
    "title": "भाग 3 — दैनिक संचालन",
    "chapters": [
      {
        "slug": "adhyay-6",
        "title": "अध्याय 6 — वाउचर प्रणाली: रसीद, भुगतान, जर्नल व कोंट्रा",
        "shortTitle": "वाउचर प्रणाली: रसीद, भुगतान, जर्नल व कोंट्रा",
        "summary": "इस अध्याय के बाद आप: चारों वाउचर प्रकार; आसान व विशेषज्ञ मोड; अनुमोदन व सही ढंग से रद्द करना।",
        "kind": "chapter",
        "num": 6
      },
      {
        "slug": "adhyay-7",
        "title": "अध्याय 7 — बिक्री प्रबंधन (Sales)",
        "shortTitle": "बिक्री प्रबंधन (Sales)",
        "summary": "इस अध्याय के बाद आप: नकद/बैंक/उधार बिक्री; GST; स्टॉक-जुड़ाव व ओवरसेलिंग-रोक; बिक्री रजिस्टर।",
        "kind": "chapter",
        "num": 7
      },
      {
        "slug": "adhyay-8",
        "title": "अध्याय 8 — खरीद प्रबंधन (Purchases)",
        "shortTitle": "खरीद प्रबंधन (Purchases)",
        "summary": "इस अध्याय के बाद आप: नकद/उधार खरीद; GST इनपुट क्रेडिट; TDS कटौती (एक बार); क्रय रजिस्टर।",
        "kind": "chapter",
        "num": 8
      },
      {
        "slug": "adhyay-9",
        "title": "अध्याय 9 — माल भंडार (Inventory)",
        "shortTitle": "माल भंडार (Inventory)",
        "summary": "इस अध्याय के बाद आप: वस्तु/समूह/opening; स्टॉक मूवमेंट; एक-सूत्र नियम; भारित-औसत मूल्य।",
        "kind": "chapter",
        "num": 9
      },
      {
        "slug": "adhyay-10",
        "title": "अध्याय 10 — बिल-वार निपटान",
        "shortTitle": "बिल-वार निपटान",
        "summary": "इस अध्याय के बाद आप: भुगतान को बिल के विरुद्ध; आंशिक व पुराने-पहले; अग्रिम/On-Account; बकाया-उम्र।",
        "kind": "chapter",
        "num": 10
      },
      {
        "slug": "adhyay-11",
        "title": "अध्याय 11 — वेतन प्रबंधन (Salary)",
        "shortTitle": "वेतन प्रबंधन (Salary)",
        "summary": "इस अध्याय के बाद आप: कर्मचारी मास्टर व slip; सकल/कटौती/शुद्ध; वेतन की प्रविष्टि; EPF/ESI/PT/TDS जमा।",
        "kind": "chapter",
        "num": 11
      }
    ]
  },
  {
    "id": "bhag-4",
    "title": "भाग 4 — बहियाँ व तलपट",
    "chapters": [
      {
        "slug": "adhyay-12",
        "title": "अध्याय 12 — रोज़नामचा (Day Book) व खाता-बही (Ledger)",
        "shortTitle": "रोज़नामचा (Day Book) व खाता-बही (Ledger)",
        "summary": "इस अध्याय के बाद आप: Day Book पढ़ना; किसी खाते की बही व चालू-शेष; खोज/छानना; ऑडिट-ट्रेल।",
        "kind": "chapter",
        "num": 12
      },
      {
        "slug": "adhyay-13",
        "title": "अध्याय 13 — तलपट (Trial Balance)",
        "shortTitle": "तलपट (Trial Balance)",
        "summary": "इस अध्याय के बाद आप: तलपट बनाना व पढ़ना; Dr=Cr का महत्व; NCDC दो-खंड प्रारूप; न मिलने पर निदान।",
        "kind": "chapter",
        "num": 13
      }
    ]
  },
  {
    "id": "bhag-5",
    "title": "भाग 5 — अंतिम खाते",
    "chapters": [
      {
        "slug": "adhyay-14",
        "title": "अध्याय 14 — व्यापार खाता (Trading Account)",
        "shortTitle": "व्यापार खाता (Trading Account)",
        "summary": "इस अध्याय के बाद आप: सकल लाभ; प्रारंभिक+खरीद−समापन; गतिविधि-वार ब्योरा; समापन-स्टॉक का सही मूल्य।",
        "kind": "chapter",
        "num": 14
      },
      {
        "slug": "adhyay-15",
        "title": "अध्याय 15 — आय-व्यय खाता (Income & Expenditure)",
        "shortTitle": "आय-व्यय खाता (Income & Expenditure)",
        "summary": "इस अध्याय के बाद आप: शुद्ध अधिशेष/घाटा; सकल लाभ का अंतरण; प्रत्यक्ष व अप्रत्यक्ष व्यय; पूँजी बनाम राजस्व।",
        "kind": "chapter",
        "num": 15
      },
      {
        "slug": "adhyay-16",
        "title": "अध्याय 16 — तुलन-पत्र (Balance Sheet)",
        "shortTitle": "तुलन-पत्र (Balance Sheet)",
        "summary": "इस अध्याय के बाद आप: संपत्ति=देयता+पूँजी; समापन-स्टॉक की एकल गणना; डबल-काउंट से बचाव; पढ़ना।",
        "kind": "chapter",
        "num": 16
      },
      {
        "slug": "adhyay-17",
        "title": "अध्याय 17 — प्राप्ति व भुगतान खाता (Receipts & Payments)",
        "shortTitle": "प्राप्ति व भुगतान खाता (Receipts & Payments)",
        "summary": "इस अध्याय के बाद आप: नकदी-आधार सारांश; पूँजी बनाम राजस्व; कोंट्रा का बहिष्करण; प्रारंभिक/समापन नकद-बैंक।",
        "kind": "chapter",
        "num": 17
      }
    ]
  },
  {
    "id": "bhag-6",
    "title": "भाग 6 — कर अनुपालन",
    "chapters": [
      {
        "slug": "adhyay-18",
        "title": "अध्याय 18 — GST प्रबंधन",
        "shortTitle": "GST प्रबंधन",
        "summary": "इस अध्याय के बाद आप: आउटपुट/इनपुट GST; CGST-SGST-IGST; HSN सारांश; रियायती बिल पर सही कर; GSTR मिलान।",
        "kind": "chapter",
        "num": 18
      },
      {
        "slug": "adhyay-19",
        "title": "अध्याय 19 — TDS व त्रैमासिक रिटर्न (26Q)",
        "shortTitle": "TDS व त्रैमासिक रिटर्न (26Q)",
        "summary": "इस अध्याय के बाद आप: TDS कब/कितना; एक-बार कटौती; देय TDS जमा; TDS रजिस्टर व 26Q तिमाही।",
        "kind": "chapter",
        "num": 19
      }
    ]
  },
  {
    "id": "bhag-7",
    "title": "भाग 7 — विशेष लेखांकन",
    "chapters": [
      {
        "slug": "adhyay-20",
        "title": "अध्याय 20 — मूल्यह्रास (Depreciation)",
        "shortTitle": "मूल्यह्रास (Depreciation)",
        "summary": "इस अध्याय के बाद आप: SLM व WDV; प्रति-संपत्ति WDV; संचित ह्रास; जर्नल; तुलन-पत्र पर असर।",
        "kind": "chapter",
        "num": 20
      },
      {
        "slug": "adhyay-21",
        "title": "अध्याय 21 — स्टॉक मूल्यांकन (Stock Valuation)",
        "shortTitle": "स्टॉक मूल्यांकन (Stock Valuation)",
        "summary": "इस अध्याय के बाद आप: FIFO/भारित-औसत; canonical मात्रा×लागत; क्रम-असंवेदनशील मूल्य; \"₹0 क्यों\" का निदान।",
        "kind": "chapter",
        "num": 21
      },
      {
        "slug": "adhyay-22",
        "title": "अध्याय 22 — लाभ-विनियोग (Profit Distribution)",
        "shortTitle": "लाभ-विनियोग (Profit Distribution)",
        "summary": "इस अध्याय के बाद आप: वैधानिक संचय 25%; लाभांश व बोनस; संरक्षण-छूट; वितरण-योग्य अधिशेष; अति-विनियोग रोक।",
        "kind": "chapter",
        "num": 22
      },
      {
        "slug": "adhyay-23",
        "title": "अध्याय 23 — सांविधिक रिटर्न व संघ रिपोर्ट",
        "shortTitle": "सांविधिक रिटर्न व संघ रिपोर्ट",
        "summary": "इस अध्याय के बाद आप: Federation रिपोर्ट; सदस्य-वृद्धि (FY-सीमा); NPA वर्गीकरण; उधार-निधि; सांविधिक प्रपत्र।",
        "kind": "chapter",
        "num": 23
      }
    ]
  },
  {
    "id": "bhag-8",
    "title": "भाग 8 — वर्षांत व सुरक्षा",
    "chapters": [
      {
        "slug": "adhyay-24",
        "title": "अध्याय 24 — वर्षांत प्रक्रिया व FY-लॉक",
        "shortTitle": "वर्षांत प्रक्रिया व FY-लॉक",
        "summary": "इस अध्याय के बाद आप: वर्षांत-चेकलिस्ट; समापन-स्टॉक जर्नल; FY-लॉक; शेष आगे ले जाना।",
        "kind": "chapter",
        "num": 24
      },
      {
        "slug": "adhyay-25",
        "title": "अध्याय 25 — ऑडिट तैयारी",
        "shortTitle": "ऑडिट तैयारी",
        "summary": "इस अध्याय के बाद आप: ऑडिट प्रकार; दस्तावेज़-फ़ाइल; सामान्य आपत्तियाँ; ऑडिट-प्रमाणपत्र; पारदर्शिता।",
        "kind": "chapter",
        "num": 25
      },
      {
        "slug": "adhyay-26",
        "title": "अध्याय 26 — डेटा सुरक्षा व बैकअप",
        "shortTitle": "डेटा सुरक्षा व बैकअप",
        "summary": "इस अध्याय के बाद आप: क्लाउड-सुरक्षा व RLS; भूमिका-नियंत्रण; निर्यात-बैकअप; पासवर्ड-स्वच्छता; \"लोकल बनाम क्लाउड\" बचाव।",
        "kind": "chapter",
        "num": 26
      }
    ]
  },
  {
    "id": "bhag-9",
    "title": "भाग 9 — संदर्भ व अभ्यास",
    "chapters": [
      {
        "slug": "adhyay-27",
        "title": "अध्याय 27 — सहकारी लेखांकन के सुनहरे नियम",
        "shortTitle": "सहकारी लेखांकन के सुनहरे नियम",
        "summary": "इस अध्याय के बाद आप: रोज़मर्रा के लिए याद रखने योग्य सिद्धांत व चेतावनियाँ।",
        "kind": "chapter",
        "num": 27
      },
      {
        "slug": "adhyay-28",
        "title": "अध्याय 28 — समग्र केस-स्टडी: रानिया सहकारी समिति (पूर्ण वर्ष)",
        "shortTitle": "समग्र केस-स्टडी: रानिया सहकारी समिति (पूर्ण वर्ष)",
        "summary": "उद्देश्य: एक पूरे वर्ष का लेखांकन — प्रारंभिक शेष से अंतिम खातों व विनियोग तक — एक सूत्र में, जो ₹5,42,500 पर मिलता है।",
        "kind": "chapter",
        "num": 28
      },
      {
        "slug": "adhyay-29",
        "title": "अध्याय 29 — विशिष्ट रजिस्टर व अभिलेख",
        "shortTitle": "विशिष्ट रजिस्टर व अभिलेख",
        "summary": "इस अध्याय के बाद आप: सदस्य, शेयर, ऋण, स्टॉक, वेतन, GST/TDS रजिस्टर; उनका उद्देश्य व मिलान।",
        "kind": "chapter",
        "num": 29
      },
      {
        "slug": "adhyay-30",
        "title": "अध्याय 30 — समग्र FAQ (सबसे आम 30 प्रश्न)",
        "shortTitle": "समग्र FAQ (सबसे आम 30 प्रश्न)",
        "summary": "सहकार लेखा उपयोग में पूछे जाने वाले शीर्ष प्रश्न-उत्तर — त्वरित संदर्भ।",
        "kind": "chapter",
        "num": 30
      }
    ]
  },
  {
    "id": "parishisht",
    "title": "परिशिष्ट · Appendices",
    "chapters": [
      {
        "slug": "parishisht-a",
        "title": "परिशिष्ट A — मानक खाता-चार्ट (Chart of Accounts)",
        "shortTitle": "मानक खाता-चार्ट (Chart of Accounts)",
        "summary": "सहकार लेखा में तैयार मिलने वाले प्रमुख खाते — कोड, नाम, श्रेणी व रिपोर्ट।",
        "kind": "appendix"
      },
      {
        "slug": "parishisht-b",
        "title": "परिशिष्ट B — शब्दावली (Glossary)",
        "shortTitle": "शब्दावली (Glossary)",
        "summary": "",
        "kind": "appendix"
      },
      {
        "slug": "parishisht-c",
        "title": "परिशिष्ट C — रिपोर्ट → सांविधिक प्रपत्र मानचित्र",
        "shortTitle": "रिपोर्ट → सांविधिक प्रपत्र मानचित्र",
        "summary": "",
        "kind": "appendix"
      },
      {
        "slug": "parishisht-d",
        "title": "परिशिष्ट D — त्वरित-संदर्भ कार्ड",
        "shortTitle": "त्वरित-संदर्भ कार्ड",
        "summary": "",
        "kind": "appendix"
      },
      {
        "slug": "parishisht-e",
        "title": "परिशिष्ट E — वर्षांत चेकलिस्ट (प्रिंट-योग्य)",
        "shortTitle": "वर्षांत चेकलिस्ट (प्रिंट-योग्य)",
        "summary": "",
        "kind": "appendix"
      },
      {
        "slug": "parishisht-f",
        "title": "परिशिष्ट F — अभ्यास-उत्तर (चुनिंदा)",
        "shortTitle": "अभ्यास-उत्तर (चुनिंदा)",
        "summary": "स्वयं हल करने के बाद मिलाएँ; विधि महत्वपूर्ण है, केवल उत्तर नहीं।",
        "kind": "appendix"
      }
    ]
  }
];
export const BACK_MATTER: GuideEntry = {
  "slug": "samapan",
  "title": "समापन — एक अंतिम शब्द",
  "shortTitle": "समापन",
  "summary": "💡 तीन सूत्र, फिर से: (1) ऐप औज़ार है, समझ आपकी — सहकार लेखा गणना करता है, पर सही प्रविष्टि व सही वर्गीकरण आप तय करते हैं। (2) छोटी सही आदतें किताबें बचाती हैं — रोज़ प्रविष्टि, माह-अंत मिलान, समय पर कर, नियमित बैकअप। (3) पारदर्शिता ही सहकारिता है — हर सदस्य का भरोसा सही, खुले, मिलते हुए खातों से बनता है।",
  "kind": "back"
};

// flat reading order (front -> all chapters -> appendices -> back), for prev/next nav
export const GUIDE_ORDER: { slug: string; shortTitle: string; title: string }[] = [
  {
    "slug": "bhumika",
    "shortTitle": "भूमिका",
    "title": "भूमिका"
  },
  {
    "slug": "adhyay-1",
    "shortTitle": "लेखांकन की नींव: सहकारी समिति का हिसाब-किताब",
    "title": "अध्याय 1 — लेखांकन की नींव: सहकारी समिति का हिसाब-किताब"
  },
  {
    "slug": "adhyay-2",
    "shortTitle": "पंजीकरण, समिति सेटअप व भूमिकाएँ",
    "title": "अध्याय 2 — पंजीकरण, समिति सेटअप व भूमिकाएँ"
  },
  {
    "slug": "adhyay-3",
    "shortTitle": "खाता-शीर्ष (Chart of Accounts)",
    "title": "अध्याय 3 — खाता-शीर्ष (Chart of Accounts)"
  },
  {
    "slug": "adhyay-4",
    "shortTitle": "प्रारंभिक शेष (Opening Balances)",
    "title": "अध्याय 4 — प्रारंभिक शेष (Opening Balances)"
  },
  {
    "slug": "adhyay-5",
    "shortTitle": "सदस्य व सदस्यता प्रबंधन",
    "title": "अध्याय 5 — सदस्य व सदस्यता प्रबंधन"
  },
  {
    "slug": "adhyay-6",
    "shortTitle": "वाउचर प्रणाली: रसीद, भुगतान, जर्नल व कोंट्रा",
    "title": "अध्याय 6 — वाउचर प्रणाली: रसीद, भुगतान, जर्नल व कोंट्रा"
  },
  {
    "slug": "adhyay-7",
    "shortTitle": "बिक्री प्रबंधन (Sales)",
    "title": "अध्याय 7 — बिक्री प्रबंधन (Sales)"
  },
  {
    "slug": "adhyay-8",
    "shortTitle": "खरीद प्रबंधन (Purchases)",
    "title": "अध्याय 8 — खरीद प्रबंधन (Purchases)"
  },
  {
    "slug": "adhyay-9",
    "shortTitle": "माल भंडार (Inventory)",
    "title": "अध्याय 9 — माल भंडार (Inventory)"
  },
  {
    "slug": "adhyay-10",
    "shortTitle": "बिल-वार निपटान",
    "title": "अध्याय 10 — बिल-वार निपटान"
  },
  {
    "slug": "adhyay-11",
    "shortTitle": "वेतन प्रबंधन (Salary)",
    "title": "अध्याय 11 — वेतन प्रबंधन (Salary)"
  },
  {
    "slug": "adhyay-12",
    "shortTitle": "रोज़नामचा (Day Book) व खाता-बही (Ledger)",
    "title": "अध्याय 12 — रोज़नामचा (Day Book) व खाता-बही (Ledger)"
  },
  {
    "slug": "adhyay-13",
    "shortTitle": "तलपट (Trial Balance)",
    "title": "अध्याय 13 — तलपट (Trial Balance)"
  },
  {
    "slug": "adhyay-14",
    "shortTitle": "व्यापार खाता (Trading Account)",
    "title": "अध्याय 14 — व्यापार खाता (Trading Account)"
  },
  {
    "slug": "adhyay-15",
    "shortTitle": "आय-व्यय खाता (Income & Expenditure)",
    "title": "अध्याय 15 — आय-व्यय खाता (Income & Expenditure)"
  },
  {
    "slug": "adhyay-16",
    "shortTitle": "तुलन-पत्र (Balance Sheet)",
    "title": "अध्याय 16 — तुलन-पत्र (Balance Sheet)"
  },
  {
    "slug": "adhyay-17",
    "shortTitle": "प्राप्ति व भुगतान खाता (Receipts & Payments)",
    "title": "अध्याय 17 — प्राप्ति व भुगतान खाता (Receipts & Payments)"
  },
  {
    "slug": "adhyay-18",
    "shortTitle": "GST प्रबंधन",
    "title": "अध्याय 18 — GST प्रबंधन"
  },
  {
    "slug": "adhyay-19",
    "shortTitle": "TDS व त्रैमासिक रिटर्न (26Q)",
    "title": "अध्याय 19 — TDS व त्रैमासिक रिटर्न (26Q)"
  },
  {
    "slug": "adhyay-20",
    "shortTitle": "मूल्यह्रास (Depreciation)",
    "title": "अध्याय 20 — मूल्यह्रास (Depreciation)"
  },
  {
    "slug": "adhyay-21",
    "shortTitle": "स्टॉक मूल्यांकन (Stock Valuation)",
    "title": "अध्याय 21 — स्टॉक मूल्यांकन (Stock Valuation)"
  },
  {
    "slug": "adhyay-22",
    "shortTitle": "लाभ-विनियोग (Profit Distribution)",
    "title": "अध्याय 22 — लाभ-विनियोग (Profit Distribution)"
  },
  {
    "slug": "adhyay-23",
    "shortTitle": "सांविधिक रिटर्न व संघ रिपोर्ट",
    "title": "अध्याय 23 — सांविधिक रिटर्न व संघ रिपोर्ट"
  },
  {
    "slug": "adhyay-24",
    "shortTitle": "वर्षांत प्रक्रिया व FY-लॉक",
    "title": "अध्याय 24 — वर्षांत प्रक्रिया व FY-लॉक"
  },
  {
    "slug": "adhyay-25",
    "shortTitle": "ऑडिट तैयारी",
    "title": "अध्याय 25 — ऑडिट तैयारी"
  },
  {
    "slug": "adhyay-26",
    "shortTitle": "डेटा सुरक्षा व बैकअप",
    "title": "अध्याय 26 — डेटा सुरक्षा व बैकअप"
  },
  {
    "slug": "adhyay-27",
    "shortTitle": "सहकारी लेखांकन के सुनहरे नियम",
    "title": "अध्याय 27 — सहकारी लेखांकन के सुनहरे नियम"
  },
  {
    "slug": "adhyay-28",
    "shortTitle": "समग्र केस-स्टडी: रानिया सहकारी समिति (पूर्ण वर्ष)",
    "title": "अध्याय 28 — समग्र केस-स्टडी: रानिया सहकारी समिति (पूर्ण वर्ष)"
  },
  {
    "slug": "adhyay-29",
    "shortTitle": "विशिष्ट रजिस्टर व अभिलेख",
    "title": "अध्याय 29 — विशिष्ट रजिस्टर व अभिलेख"
  },
  {
    "slug": "adhyay-30",
    "shortTitle": "समग्र FAQ (सबसे आम 30 प्रश्न)",
    "title": "अध्याय 30 — समग्र FAQ (सबसे आम 30 प्रश्न)"
  },
  {
    "slug": "parishisht-a",
    "shortTitle": "मानक खाता-चार्ट (Chart of Accounts)",
    "title": "परिशिष्ट A — मानक खाता-चार्ट (Chart of Accounts)"
  },
  {
    "slug": "parishisht-b",
    "shortTitle": "शब्दावली (Glossary)",
    "title": "परिशिष्ट B — शब्दावली (Glossary)"
  },
  {
    "slug": "parishisht-c",
    "shortTitle": "रिपोर्ट → सांविधिक प्रपत्र मानचित्र",
    "title": "परिशिष्ट C — रिपोर्ट → सांविधिक प्रपत्र मानचित्र"
  },
  {
    "slug": "parishisht-d",
    "shortTitle": "त्वरित-संदर्भ कार्ड",
    "title": "परिशिष्ट D — त्वरित-संदर्भ कार्ड"
  },
  {
    "slug": "parishisht-e",
    "shortTitle": "वर्षांत चेकलिस्ट (प्रिंट-योग्य)",
    "title": "परिशिष्ट E — वर्षांत चेकलिस्ट (प्रिंट-योग्य)"
  },
  {
    "slug": "parishisht-f",
    "shortTitle": "अभ्यास-उत्तर (चुनिंदा)",
    "title": "परिशिष्ट F — अभ्यास-उत्तर (चुनिंदा)"
  },
  {
    "slug": "samapan",
    "shortTitle": "समापन",
    "title": "समापन — एक अंतिम शब्द"
  }
];

// raw markdown for every entry, keyed by "./<slug>.md"
const RAW = import.meta.glob('./*.md', { query: '?raw', import: 'default', eager: true }) as Record<string, string>;
export function loadGuideRaw(slug: string): string | null {
  return RAW['./' + slug + '.md'] ?? null;
}
export function findEntry(slug: string): GuideEntry | null {
  if (FRONT_MATTER.slug === slug) return FRONT_MATTER;
  if (BACK_MATTER.slug === slug) return BACK_MATTER;
  for (const p of GUIDE_PARTS) {
    const f = p.chapters.find((c) => c.slug === slug);
    if (f) return f;
  }
  return null;
}
